// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.20.3
// source: build.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Attribute, AttributeType, attributeTypeFromJSON, attributeTypeToJSON } from "./attribute";
import { Character, characterFromJSON, characterToJSON } from "./character";
import { Suit } from "./suit";
import { Weapon, weaponFromJSON, weaponToJSON } from "./weapon";

export const protobufPackage = "io.leishi.genshin.proto";

export interface Build {
  name: string;
  character: Character;
  weapons: Weapon[];
  suits: Suit[];
  flowerAttributes: AttributeType[];
  plumeAttributes: AttributeType[];
  sandsAttributes: AttributeType[];
  gobletAttributes: AttributeType[];
  circletAttributes: AttributeType[];
  subAttributes: Attribute[];
}

function createBaseBuild(): Build {
  return {
    name: "",
    character: 0,
    weapons: [],
    suits: [],
    flowerAttributes: [],
    plumeAttributes: [],
    sandsAttributes: [],
    gobletAttributes: [],
    circletAttributes: [],
    subAttributes: [],
  };
}

export const Build = {
  encode(message: Build, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.character !== 0) {
      writer.uint32(16).int32(message.character);
    }
    writer.uint32(26).fork();
    for (const v of message.weapons) {
      writer.int32(v);
    }
    writer.ldelim();
    for (const v of message.suits) {
      Suit.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    writer.uint32(42).fork();
    for (const v of message.flowerAttributes) {
      writer.int32(v);
    }
    writer.ldelim();
    writer.uint32(50).fork();
    for (const v of message.plumeAttributes) {
      writer.int32(v);
    }
    writer.ldelim();
    writer.uint32(58).fork();
    for (const v of message.sandsAttributes) {
      writer.int32(v);
    }
    writer.ldelim();
    writer.uint32(66).fork();
    for (const v of message.gobletAttributes) {
      writer.int32(v);
    }
    writer.ldelim();
    writer.uint32(74).fork();
    for (const v of message.circletAttributes) {
      writer.int32(v);
    }
    writer.ldelim();
    for (const v of message.subAttributes) {
      Attribute.encode(v!, writer.uint32(82).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Build {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBuild();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.character = reader.int32() as any;
          continue;
        case 3:
          if (tag === 24) {
            message.weapons.push(reader.int32() as any);

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.weapons.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.suits.push(Suit.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag === 40) {
            message.flowerAttributes.push(reader.int32() as any);

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.flowerAttributes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 6:
          if (tag === 48) {
            message.plumeAttributes.push(reader.int32() as any);

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.plumeAttributes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 7:
          if (tag === 56) {
            message.sandsAttributes.push(reader.int32() as any);

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.sandsAttributes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 8:
          if (tag === 64) {
            message.gobletAttributes.push(reader.int32() as any);

            continue;
          }

          if (tag === 66) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.gobletAttributes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 9:
          if (tag === 72) {
            message.circletAttributes.push(reader.int32() as any);

            continue;
          }

          if (tag === 74) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.circletAttributes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.subAttributes.push(Attribute.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Build {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      character: isSet(object.character) ? characterFromJSON(object.character) : 0,
      weapons: globalThis.Array.isArray(object?.weapons) ? object.weapons.map((e: any) => weaponFromJSON(e)) : [],
      suits: globalThis.Array.isArray(object?.suits) ? object.suits.map((e: any) => Suit.fromJSON(e)) : [],
      flowerAttributes: globalThis.Array.isArray(object?.flowerAttributes)
        ? object.flowerAttributes.map((e: any) => attributeTypeFromJSON(e))
        : [],
      plumeAttributes: globalThis.Array.isArray(object?.plumeAttributes)
        ? object.plumeAttributes.map((e: any) => attributeTypeFromJSON(e))
        : [],
      sandsAttributes: globalThis.Array.isArray(object?.sandsAttributes)
        ? object.sandsAttributes.map((e: any) => attributeTypeFromJSON(e))
        : [],
      gobletAttributes: globalThis.Array.isArray(object?.gobletAttributes)
        ? object.gobletAttributes.map((e: any) => attributeTypeFromJSON(e))
        : [],
      circletAttributes: globalThis.Array.isArray(object?.circletAttributes)
        ? object.circletAttributes.map((e: any) => attributeTypeFromJSON(e))
        : [],
      subAttributes: globalThis.Array.isArray(object?.subAttributes)
        ? object.subAttributes.map((e: any) => Attribute.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Build): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.character !== 0) {
      obj.character = characterToJSON(message.character);
    }
    if (message.weapons?.length) {
      obj.weapons = message.weapons.map((e) => weaponToJSON(e));
    }
    if (message.suits?.length) {
      obj.suits = message.suits.map((e) => Suit.toJSON(e));
    }
    if (message.flowerAttributes?.length) {
      obj.flowerAttributes = message.flowerAttributes.map((e) => attributeTypeToJSON(e));
    }
    if (message.plumeAttributes?.length) {
      obj.plumeAttributes = message.plumeAttributes.map((e) => attributeTypeToJSON(e));
    }
    if (message.sandsAttributes?.length) {
      obj.sandsAttributes = message.sandsAttributes.map((e) => attributeTypeToJSON(e));
    }
    if (message.gobletAttributes?.length) {
      obj.gobletAttributes = message.gobletAttributes.map((e) => attributeTypeToJSON(e));
    }
    if (message.circletAttributes?.length) {
      obj.circletAttributes = message.circletAttributes.map((e) => attributeTypeToJSON(e));
    }
    if (message.subAttributes?.length) {
      obj.subAttributes = message.subAttributes.map((e) => Attribute.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Build>, I>>(base?: I): Build {
    return Build.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Build>, I>>(object: I): Build {
    const message = createBaseBuild();
    message.name = object.name ?? "";
    message.character = object.character ?? 0;
    message.weapons = object.weapons?.map((e) => e) || [];
    message.suits = object.suits?.map((e) => Suit.fromPartial(e)) || [];
    message.flowerAttributes = object.flowerAttributes?.map((e) => e) || [];
    message.plumeAttributes = object.plumeAttributes?.map((e) => e) || [];
    message.sandsAttributes = object.sandsAttributes?.map((e) => e) || [];
    message.gobletAttributes = object.gobletAttributes?.map((e) => e) || [];
    message.circletAttributes = object.circletAttributes?.map((e) => e) || [];
    message.subAttributes = object.subAttributes?.map((e) => Attribute.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
