/* eslint-disable */

export const protobufPackage = "io.leishi.genshin.proto";

export enum Enemy {
  ENEMY_UNSPECIFIED = 0,
  ABYSSHERALDFROSTFALL = 1,
  ABYSSHERALDWICKEDTORRENTS = 2,
  ABYSSLECTORFATHOMLESSFLAMES = 3,
  ABYSSLECTORVIOLETLIGHTNING = 4,
  ADVANCEDDEFENSIVEANEMOTOWER = 5,
  ADVANCEDDEFENSIVECRYOTOWER = 6,
  ADVANCEDDEFENSIVEELECTROTOWER = 7,
  ADVANCEDDEFENSIVEHYDROTOWER = 8,
  ADVANCEDDEFENSIVEPYROTOWER = 9,
  AEONBLIGHTDRAKE = 10,
  ALGORITHMOFSEMIINTRANSIENTMATRIXOFOVERSEERNETWORK = 11,
  ALLDEVOURINGNARWHAL = 12,
  ANEMOHILICHURLROGUE = 13,
  ANEMOHYPOSTASIS = 14,
  ANEMOSAMACHURL = 15,
  ANEMOSLIME = 16,
  ANEMOSPECTER = 17,
  ANGELICSEAHARE = 18,
  ANNIHILATIONSPECIALISTMEK = 19,
  AREAALERTMEK = 20,
  ARITHMETICENHANCERMEK = 21,
  ARMOREDCRAB = 22,
  ASCENDEDKING = 23,
  ASSAULTSPECIALISTMEK = 24,
  AUTOMATONFUNGUSBALLOON = 25,
  AUTOMATONLARGESLIMEBALLOON = 26,
  AUTOMATONSMALLSLIMEBALLOON = 27,
  AZHDAHA = 28,
  BALLOCTOPUS = 29,
  BASICDEFENSIVEANEMOTOWER = 30,
  BASICDEFENSIVECRYOTOWER = 31,
  BASICDEFENSIVEELECTROTOWER = 32,
  BASICDEFENSIVEHYDROTOWER = 33,
  BASICDEFENSIVEPYROTOWER = 34,
  BATTLEHARDENEDBITINGCOLDWAYOBMANIFESTATION = 35,
  BATTLEHARDENEDBURNINGAFLAMEWAYOBMANIFESTATION = 36,
  BATTLEHARDENEDFLOWINVERTEDWAYOBMANIFESTATION = 37,
  BATTLEHARDENEDFOLIARSWIFTWAYOBMANIFESTATION = 38,
  BATTLEHARDENEDIKTOMISAURUS = 39,
  BATTLEHARDENEDPRIMORDIALBATHYSMALVISHAP = 40,
  BATTLEHARDENEDROCKCAVERNOUSWAYOBMANIFESTATION = 41,
  BATTLEHARDENEDRUINDRAKEEARTHGUARD = 42,
  BATTLEHARDENEDTATANKASAURUS = 43,
  BATTLEHARDENEDTHUNDERINGWAYOBMANIFESTATION = 44,
  BEISHT = 45,
  BITINGCOLDWAYOBMANIFESTATION = 46,
  BLACKSERPENTKNIGHTROCKBREAKERAX = 47,
  BLACKSERPENTKNIGHTWINDCUTTER = 48,
  BLAZINGAXEMITACHURL = 49,
  BLUBBERBEAST = 50,
  BOLTEATERBATHYSMALVISHAP = 51,
  BUBBLERSEAHORSE = 52,
  BUBBLYSEAHORSE = 53,
  BURNINGAFLAMEWAYOBMANIFESTATION = 54,
  CHERUBICSEAHARE = 55,
  CHILDE = 56,
  CONSECRATEDFANGEDBEAST = 57,
  CONSECRATEDFLYINGSERPENT = 58,
  CONSECRATEDHORNEDCROCODILE = 59,
  CONSECRATEDREDVULTURE = 60,
  CONSECRATEDSCORPION = 61,
  CONSTRUCTIONSPECIALISTMEK = 62,
  CRACKLINGAXEMITACHURL = 63,
  CRYOABYSSMAGE = 64,
  CRYOCICIN = 65,
  CRYOHILICHURLGRENADIER = 66,
  CRYOHILICHURLSHOOTER = 67,
  CRYOHYPOSTASIS = 68,
  CRYOREGISVINE = 69,
  CRYOSAMACHURL = 70,
  CRYOSLIME = 71,
  CRYOSPECTER = 72,
  CRYOWHOPPERFLOWER = 73,
  DEEPWATERASSAULTMEK = 74,
  DEFENSIVEPHYSICALTOWER = 75,
  DEFENSIVEPOINT56PUSHCONTESTDEFENSE = 76,
  DENDROHYPOSTASIS = 77,
  DENDROSAMACHURL = 78,
  DENDROSLIME = 79,
  DENDROSPECTER = 80,
  ELECTROABYSSMAGE = 81,
  ELECTROCICIN = 82,
  ELECTROHILICHURLGRENADIER = 83,
  ELECTROHILICHURLSHOOTER = 84,
  ELECTROHYPOSTASIS = 85,
  ELECTROREGISVINE = 86,
  ELECTROSAMACHURL = 87,
  ELECTROSLIME = 88,
  ELECTROSPECTER = 89,
  ELECTROWHOPPERFLOWER = 90,
  EMPEROROFFIREANDIRON = 91,
  EREMITEAXEVANGUARD = 92,
  EREMITECROSSBOW = 93,
  EREMITEDAYTHUNDER = 94,
  EREMITEDESERTCLEARWATER = 95,
  EREMITEFLORALRINGDANCER = 96,
  EREMITEGALEHUNTER = 97,
  EREMITELINEBREAKER = 98,
  EREMITERAVENBEAKHALBERDIER = 99,
  EREMITESCORCHINGLOREMASTER = 100,
  EREMITESTONEENCHANTER = 101,
  EREMITESUNFROST = 102,
  EREMITESWORDDANCER = 103,
  ERODINGAVATAROFLAVA = 104,
  EXPERIMENTALFIELDGENERATOR = 105,
  EYEOFTHESTORM = 106,
  FATUICRYOCICINMAGE = 107,
  FATUIELECTROCICINMAGE = 108,
  FATUIPYROAGENT = 109,
  FATUISKIRMISHERANEMOBOXERVANGUARD = 110,
  FATUISKIRMISHERCRYOGUNNERLEGIONNAIRE = 111,
  FATUISKIRMISHERELECTROHAMMERVANGUARD = 112,
  FATUISKIRMISHERGEOCHANTERBRACER = 113,
  FATUISKIRMISHERHYDROGUNNERLEGIONNAIRE = 114,
  FATUISKIRMISHERPYROSLINGERBRACER = 115,
  FEROCIOUSWARRIORGRAPPLER = 116,
  FEROCIOUSWARRIORHUMANRAM = 117,
  FEROCIOUSWARRIORWRESTLER = 118,
  FLOATINGANEMOFUNGUS = 119,
  FLOATINGDENDROFUNGUS = 120,
  FLOATINGHYDROFUNGUS = 121,
  FLOWINGBLADEGREASESAW = 122,
  FLOWINGBLADEHARPOONTHROWER = 123,
  FLOWINGBLADESKIRMISHER = 124,
  FLOWINVERTEDWAYOBMANIFESTATION = 125,
  FLUIDAVATAROFLAVA = 126,
  FOLIARSWIFTWAYOBMANIFESTATION = 127,
  FORGEDSANDINTERROGATOR = 128,
  FORGEDSANDJAVELINEER = 129,
  FORGEDSANDSHIELDBREAKER = 130,
  FROSTARMLAWACHURL = 131,
  FROSTOPERATIVE = 132,
  FURNACESHELLMOUNTAINWEASEL = 133,
  GEOHYPOSTASIS = 134,
  GEOLOGICALSURVEYMEK = 135,
  GEOSAMACHURL = 136,
  GEOSLIME = 137,
  GEOSPECTER = 138,
  GEOVISHAP = 139,
  GEOVISHAPHATCHLING = 140,
  GLUTTONOUSYUMKASAURMOUNTAINKING = 141,
  GOLDENWOLFLORD = 142,
  GOLDFLAMEQUCUSAURTYRANT = 143,
  GROUNDEDGEOSHROOM = 144,
  GROUNDEDHYDROSHROOM = 145,
  GUARDIANOFAPEPSOASIS = 146,
  HALFTULPA = 147,
  HATJELLYFISH = 148,
  HILICHURL = 149,
  HILICHURLBERSERKER = 150,
  HILICHURLFIGHTER = 151,
  HILICHURLGRENADIER = 152,
  HILICHURLSHOOTER = 153,
  HUNTERSRAY = 154,
  HYDROABYSSMAGE = 155,
  HYDROCICIN = 156,
  HYDROHILICHURLROGUE = 157,
  HYDROHYPOSTASIS = 158,
  HYDROHYPOSTASISSUMMON = 159,
  HYDROMIMICBOAR = 160,
  HYDROMIMICCRAB = 161,
  HYDROMIMICCRANE = 162,
  HYDROMIMICFINCH = 163,
  HYDROMIMICFROG = 164,
  HYDROMIMICMALLARD = 165,
  HYDROMIMICRAPTOR = 166,
  HYDROMIMICSQUIRREL = 167,
  HYDROSAMACHURL = 168,
  HYDROSLIME = 169,
  HYDROSPECTER = 170,
  HYDROTULPA = 171,
  ICESHIELDHILICHURLGUARD = 172,
  ICESHIELDWALLMITACHURL = 173,
  ICEWINDSUITE = 174,
  IKTOMISAURUS = 175,
  IKTOMISAURUSCHICK = 176,
  IKTOMISAURUSWARRIORCRYOCRYSTALCANNON = 177,
  IKTOMISAURUSWARRIORICYTIDEBEARER = 178,
  INIQUITOUSBAPTIST = 179,
  JADEPLUMETERRORSHROOM = 180,
  KAIRAGIDANCINGTHUNDER = 181,
  KAIRAGIFIERYMIGHT = 182,
  KOHOLASAURUS = 183,
  KOHOLASAURUSWARRIORREEFSPLITTER = 184,
  KOHOLASAURUSWARRIORWAVESHUTTLER = 185,
  KOHOLASAURWHELP = 186,
  LARGEANEMOSLIME = 187,
  LARGECRYOSLIME = 188,
  LARGEDENDROSLIME = 189,
  LARGEELECTROSLIME = 190,
  LARGEGEOSLIME = 191,
  LARGEHYDROSLIME = 192,
  LARGEOVERGROWNBREACHERPRIMUS = 193,
  LARGEPYROSLIME = 194,
  LARGESHATTERSTONEBREACHERPRIMUS = 195,
  LASIGNORA = 196,
  LAVADRAGONSTATUE = 197,
  LEGATUSGOLEM = 198,
  LOCALLEGENDARMOREDCRAB = 199,
  LOCALLEGENDBLUBBERBEAST = 200,
  LOCALLEGENDCHERUBICSEAHARE = 201,
  LOCALLEGENDHATJELLYFISH = 202,
  LOCALLEGENDHUNTERSRAY = 203,
  LORDOFERODEDPRIMALFIRE = 204,
  LUPUSBOREASDOMINATOROFWOLVES = 205,
  MAGATSUMITAKENARUKAMINOMIKOTO = 206,
  MAGUUKENKI = 207,
  MAGUUKENKIGALLOPINGFROST = 208,
  MAGUUKENKILONEGALE = 209,
  MAGUUKENKIMASKOFTERROR = 210,
  MILLELITHSERGEANT = 211,
  MILLELITHSOLDIER = 212,
  MILLENNIALPEARLSEAHORSE = 213,
  MIRRORMAIDEN = 214,
  MUTANTELECTROSLIME = 215,
  NIMBLEHARVESTERMEK = 216,
  NOBUSHIHITSUKEBAN = 217,
  NOBUSHIJINTOUBAN = 218,
  NOBUSHIKIKOUBAN = 219,
  OCEANID = 220,
  OCHIMUSHACANKEREDFLAME = 221,
  OCHIMUSHAENSORCELLEDTHUNDER = 222,
  OVERGROWNBREACHERPRIMUS = 223,
  PERPETUALMECHANICALARRAY = 224,
  PRAETORIANGOLEM = 225,
  PRIMALCONSTRUCTPROSPECTOR = 226,
  PRIMALCONSTRUCTREPULSOR = 227,
  PRIMALCONSTRUCTRESHAPER = 228,
  PRIMOGEOVISHAP = 229,
  PRIMORDIALBATHYSMALVISHAP = 230,
  PYROABYSSMAGE = 231,
  PYROHILICHURLSHOOTER = 232,
  PYROHYPOSTASIS = 233,
  PYROREGISVINE = 234,
  PYROSLIME = 235,
  PYROSPECTER = 236,
  PYROWHOPPERFLOWER = 237,
  QUCUSAURUS = 238,
  QUCUSAURUSCHICK = 239,
  QUCUSAURUSWARRIORBLAZINGSKY = 240,
  QUCUSAURUSWARRIORHEARTSTARHAMMER = 241,
  RECONLOGMEK = 242,
  RIMEBITERBATHYSMALVISHAP = 243,
  ROCKCAVERNOUSWAYOBMANIFESTATION = 244,
  ROCKFONDRIFTHOUND = 245,
  ROCKFONDRIFTHOUNDWHELP = 246,
  ROCKSHIELDHILICHURLGUARD = 247,
  ROCKSHIELDWALLMITACHURL = 248,
  RUINCRUISER = 249,
  RUINDEFENDER = 250,
  RUINDESTROYER = 251,
  RUINDRAKEEARTHGUARD = 252,
  RUINDRAKESKYWATCH = 253,
  RUINGRADER = 254,
  RUINGUARD = 255,
  RUINHUNTER = 256,
  RUINSCOUT = 257,
  RUINSERPENT = 258,
  RULEROFTHECHIZHANGMOUNTAINSTIANYU = 259,
  RULEROFTHECHIZHANGMOUNTAINSYIJI = 260,
  SAMACHURLBOSS = 261,
  SANGONOMIYACOHORT = 262,
  SECRETSOURCEAUTOMATONCONFIGURATIONDEVICE = 263,
  SECRETSOURCEAUTOMATONHUNTERSEEKER = 264,
  SECRETSOURCEAUTOMATONOVERSEERDEVICE = 265,
  SETEKHWENUT = 266,
  SHADOWYHUSKDEFENDER = 267,
  SHADOWYHUSKLINEBREAKER = 268,
  SHADOWYHUSKSTANDARDBEARER = 269,
  SHATTERSTONEBREACHERPRIMUS = 270,
  SHOGUNATEINFANTRY = 271,
  SHOGUNATEINFANTRYCAPTAIN = 272,
  SHOUKINOKAMITHEPRODIGAL = 273,
  SOLITARYSUANNI = 274,
  SPIRITOFOMENDENDROSPIRITSERPENT = 275,
  SPIRITOFOMENPYROSCORPION = 276,
  SPIRITOFOMENSTONEDRAKE = 277,
  SPIRITOFOMENWINDGLEDE = 278,
  SPIRITSPEAKERWARRIORCONTEMPLATOR = 279,
  SPIRITSPEAKERWARRIORDETERMINATOR = 280,
  SPIRITSPEAKERWARRIORPSYCHOKINETIC = 281,
  STERNSHIELDCRAB = 282,
  STONEHIDELAWACHURL = 283,
  STORMTERROR = 284,
  STRETCHYANEMOFUNGUS = 285,
  STRETCHYELECTROFUNGUS = 286,
  STRETCHYGEOFUNGUS = 287,
  STRETCHYPYROFUNGUS = 288,
  SUBLIMATEDQUEEN = 289,
  SUPPRESSIONSPECIALISTMEK = 290,
  SWIFTSTEPARMEDCOURIER = 291,
  SWIFTSTEPSEEKER = 292,
  SWIFTSTEPSTORMSCOUT = 293,
  TAINTEDWATERSPLITTINGPHANTASM = 294,
  TAINTEDWATERSPOUTINGPHANTASM = 295,
  TATANKASAURUS = 296,
  TATANKASAURUSWARRIORSKYBREAKER = 297,
  TATANKASAURUSWARRIORSPIRITLIGHTCHASER = 298,
  TATANKASAURWHELP = 299,
  TENEBROUSMIMIFLORA = 300,
  TENEBROUSPAPILLATYPEI = 301,
  TEPETLISAURUS = 302,
  TEPETLISAURUSTRIBECHIEF = 303,
  TEPETLISAURUSWARRIORROCKBREAKERBLADE = 304,
  TEPETLISAURUSWARRIORSHARDSTRIKER = 305,
  TEPETLISAURWHELP = 306,
  THEGAMEBEFORETHEGATE = 307,
  THEKNAVE = 308,
  THUNDERCRAVENRIFTHOUND = 309,
  THUNDERCRAVENRIFTHOUNDWHELP = 310,
  THUNDERHELMLAWACHURL = 311,
  THUNDERINGWAYOBMANIFESTATION = 312,
  THUNDERMANIFESTATION = 313,
  TREASUREHOARDERSBOSS = 314,
  TREASUREHOARDERSCARMEN = 315,
  TREASUREHOARDERSCRUSHER = 316,
  TREASUREHOARDERSCRYOPOTIONEER = 317,
  TREASUREHOARDERSELECTROPOTIONEER = 318,
  TREASUREHOARDERSGRAVEDIGGER = 319,
  TREASUREHOARDERSHANDYMAN = 320,
  TREASUREHOARDERSHYDROPOTIONEER = 321,
  TREASUREHOARDERSLIULIU = 322,
  TREASUREHOARDERSMARKSMAN = 323,
  TREASUREHOARDERSPUGILIST = 324,
  TREASUREHOARDERSPYROPOTIONEER = 325,
  TREASUREHOARDERSRAPTOR = 326,
  TREASUREHOARDERSSCOUT = 327,
  TREASUREHOARDERSSEAMAN = 328,
  TREASUREHOARDERSWALLENSTEIN = 329,
  UNDERWATERPATROLMEK = 330,
  UNDERWATERSURVEYMEK = 331,
  UNUSUALHILICHURL = 332,
  VETERANARITHMETICENHANCERMEK = 333,
  VETERANFATUIPYROAGENT = 334,
  VETERANFATUISKIRMISHERCRYOGUNNERLEGIONNAIRE = 335,
  VETERANFATUISKIRMISHERELECTROHAMMERVANGUARD = 336,
  VETERANFATUISKIRMISHERPYROSLINGERBRACER = 337,
  VETERANFROSTOPERATIVE = 338,
  VETERANTAINTEDWATERSPLITTINGPHANTASM = 339,
  VETERANTAINTEDWATERSPOUTINGPHANTASM = 340,
  VETERANWINDOPERATIVE = 341,
  WAYWARDHERMETICSPIRITSPEAKER = 342,
  WHIRLINGCRYOFUNGUS = 343,
  WHIRLINGELECTROFUNGUS = 344,
  WHIRLINGPYROFUNGUS = 345,
  WINDOPERATIVE = 346,
  WINGEDCRYOSHROOM = 347,
  WINGEDDENDROSHROOM = 348,
  WINGEDWARRIORFEATHERSHEDDER = 349,
  WINGEDWARRIORSKYMASTER = 350,
  WINGEDWARRIORSKYSOARER = 351,
  WOODENSHIELDHILICHURLGUARD = 352,
  WOODENSHIELDWALLMITACHURL = 353,
  XUANWENBEAST = 354,
  YORIKISAMURAI = 355,
  YUMKASAURUS = 356,
  YUMKASAURUSWARRIORFLOWINGSKYFIRE = 357,
  YUMKASAURUSWARRIORWHIRLINGLEAVES = 358,
  YUMKASAURWHELP = 359,
  UNRECOGNIZED = -1,
}

export function enemyFromJSON(object: any): Enemy {
  switch (object) {
    case 0:
    case "ENEMY_UNSPECIFIED":
      return Enemy.ENEMY_UNSPECIFIED;
    case 1:
    case "ABYSSHERALDFROSTFALL":
      return Enemy.ABYSSHERALDFROSTFALL;
    case 2:
    case "ABYSSHERALDWICKEDTORRENTS":
      return Enemy.ABYSSHERALDWICKEDTORRENTS;
    case 3:
    case "ABYSSLECTORFATHOMLESSFLAMES":
      return Enemy.ABYSSLECTORFATHOMLESSFLAMES;
    case 4:
    case "ABYSSLECTORVIOLETLIGHTNING":
      return Enemy.ABYSSLECTORVIOLETLIGHTNING;
    case 5:
    case "ADVANCEDDEFENSIVEANEMOTOWER":
      return Enemy.ADVANCEDDEFENSIVEANEMOTOWER;
    case 6:
    case "ADVANCEDDEFENSIVECRYOTOWER":
      return Enemy.ADVANCEDDEFENSIVECRYOTOWER;
    case 7:
    case "ADVANCEDDEFENSIVEELECTROTOWER":
      return Enemy.ADVANCEDDEFENSIVEELECTROTOWER;
    case 8:
    case "ADVANCEDDEFENSIVEHYDROTOWER":
      return Enemy.ADVANCEDDEFENSIVEHYDROTOWER;
    case 9:
    case "ADVANCEDDEFENSIVEPYROTOWER":
      return Enemy.ADVANCEDDEFENSIVEPYROTOWER;
    case 10:
    case "AEONBLIGHTDRAKE":
      return Enemy.AEONBLIGHTDRAKE;
    case 11:
    case "ALGORITHMOFSEMIINTRANSIENTMATRIXOFOVERSEERNETWORK":
      return Enemy.ALGORITHMOFSEMIINTRANSIENTMATRIXOFOVERSEERNETWORK;
    case 12:
    case "ALLDEVOURINGNARWHAL":
      return Enemy.ALLDEVOURINGNARWHAL;
    case 13:
    case "ANEMOHILICHURLROGUE":
      return Enemy.ANEMOHILICHURLROGUE;
    case 14:
    case "ANEMOHYPOSTASIS":
      return Enemy.ANEMOHYPOSTASIS;
    case 15:
    case "ANEMOSAMACHURL":
      return Enemy.ANEMOSAMACHURL;
    case 16:
    case "ANEMOSLIME":
      return Enemy.ANEMOSLIME;
    case 17:
    case "ANEMOSPECTER":
      return Enemy.ANEMOSPECTER;
    case 18:
    case "ANGELICSEAHARE":
      return Enemy.ANGELICSEAHARE;
    case 19:
    case "ANNIHILATIONSPECIALISTMEK":
      return Enemy.ANNIHILATIONSPECIALISTMEK;
    case 20:
    case "AREAALERTMEK":
      return Enemy.AREAALERTMEK;
    case 21:
    case "ARITHMETICENHANCERMEK":
      return Enemy.ARITHMETICENHANCERMEK;
    case 22:
    case "ARMOREDCRAB":
      return Enemy.ARMOREDCRAB;
    case 23:
    case "ASCENDEDKING":
      return Enemy.ASCENDEDKING;
    case 24:
    case "ASSAULTSPECIALISTMEK":
      return Enemy.ASSAULTSPECIALISTMEK;
    case 25:
    case "AUTOMATONFUNGUSBALLOON":
      return Enemy.AUTOMATONFUNGUSBALLOON;
    case 26:
    case "AUTOMATONLARGESLIMEBALLOON":
      return Enemy.AUTOMATONLARGESLIMEBALLOON;
    case 27:
    case "AUTOMATONSMALLSLIMEBALLOON":
      return Enemy.AUTOMATONSMALLSLIMEBALLOON;
    case 28:
    case "AZHDAHA":
      return Enemy.AZHDAHA;
    case 29:
    case "BALLOCTOPUS":
      return Enemy.BALLOCTOPUS;
    case 30:
    case "BASICDEFENSIVEANEMOTOWER":
      return Enemy.BASICDEFENSIVEANEMOTOWER;
    case 31:
    case "BASICDEFENSIVECRYOTOWER":
      return Enemy.BASICDEFENSIVECRYOTOWER;
    case 32:
    case "BASICDEFENSIVEELECTROTOWER":
      return Enemy.BASICDEFENSIVEELECTROTOWER;
    case 33:
    case "BASICDEFENSIVEHYDROTOWER":
      return Enemy.BASICDEFENSIVEHYDROTOWER;
    case 34:
    case "BASICDEFENSIVEPYROTOWER":
      return Enemy.BASICDEFENSIVEPYROTOWER;
    case 35:
    case "BATTLEHARDENEDBITINGCOLDWAYOBMANIFESTATION":
      return Enemy.BATTLEHARDENEDBITINGCOLDWAYOBMANIFESTATION;
    case 36:
    case "BATTLEHARDENEDBURNINGAFLAMEWAYOBMANIFESTATION":
      return Enemy.BATTLEHARDENEDBURNINGAFLAMEWAYOBMANIFESTATION;
    case 37:
    case "BATTLEHARDENEDFLOWINVERTEDWAYOBMANIFESTATION":
      return Enemy.BATTLEHARDENEDFLOWINVERTEDWAYOBMANIFESTATION;
    case 38:
    case "BATTLEHARDENEDFOLIARSWIFTWAYOBMANIFESTATION":
      return Enemy.BATTLEHARDENEDFOLIARSWIFTWAYOBMANIFESTATION;
    case 39:
    case "BATTLEHARDENEDIKTOMISAURUS":
      return Enemy.BATTLEHARDENEDIKTOMISAURUS;
    case 40:
    case "BATTLEHARDENEDPRIMORDIALBATHYSMALVISHAP":
      return Enemy.BATTLEHARDENEDPRIMORDIALBATHYSMALVISHAP;
    case 41:
    case "BATTLEHARDENEDROCKCAVERNOUSWAYOBMANIFESTATION":
      return Enemy.BATTLEHARDENEDROCKCAVERNOUSWAYOBMANIFESTATION;
    case 42:
    case "BATTLEHARDENEDRUINDRAKEEARTHGUARD":
      return Enemy.BATTLEHARDENEDRUINDRAKEEARTHGUARD;
    case 43:
    case "BATTLEHARDENEDTATANKASAURUS":
      return Enemy.BATTLEHARDENEDTATANKASAURUS;
    case 44:
    case "BATTLEHARDENEDTHUNDERINGWAYOBMANIFESTATION":
      return Enemy.BATTLEHARDENEDTHUNDERINGWAYOBMANIFESTATION;
    case 45:
    case "BEISHT":
      return Enemy.BEISHT;
    case 46:
    case "BITINGCOLDWAYOBMANIFESTATION":
      return Enemy.BITINGCOLDWAYOBMANIFESTATION;
    case 47:
    case "BLACKSERPENTKNIGHTROCKBREAKERAX":
      return Enemy.BLACKSERPENTKNIGHTROCKBREAKERAX;
    case 48:
    case "BLACKSERPENTKNIGHTWINDCUTTER":
      return Enemy.BLACKSERPENTKNIGHTWINDCUTTER;
    case 49:
    case "BLAZINGAXEMITACHURL":
      return Enemy.BLAZINGAXEMITACHURL;
    case 50:
    case "BLUBBERBEAST":
      return Enemy.BLUBBERBEAST;
    case 51:
    case "BOLTEATERBATHYSMALVISHAP":
      return Enemy.BOLTEATERBATHYSMALVISHAP;
    case 52:
    case "BUBBLERSEAHORSE":
      return Enemy.BUBBLERSEAHORSE;
    case 53:
    case "BUBBLYSEAHORSE":
      return Enemy.BUBBLYSEAHORSE;
    case 54:
    case "BURNINGAFLAMEWAYOBMANIFESTATION":
      return Enemy.BURNINGAFLAMEWAYOBMANIFESTATION;
    case 55:
    case "CHERUBICSEAHARE":
      return Enemy.CHERUBICSEAHARE;
    case 56:
    case "CHILDE":
      return Enemy.CHILDE;
    case 57:
    case "CONSECRATEDFANGEDBEAST":
      return Enemy.CONSECRATEDFANGEDBEAST;
    case 58:
    case "CONSECRATEDFLYINGSERPENT":
      return Enemy.CONSECRATEDFLYINGSERPENT;
    case 59:
    case "CONSECRATEDHORNEDCROCODILE":
      return Enemy.CONSECRATEDHORNEDCROCODILE;
    case 60:
    case "CONSECRATEDREDVULTURE":
      return Enemy.CONSECRATEDREDVULTURE;
    case 61:
    case "CONSECRATEDSCORPION":
      return Enemy.CONSECRATEDSCORPION;
    case 62:
    case "CONSTRUCTIONSPECIALISTMEK":
      return Enemy.CONSTRUCTIONSPECIALISTMEK;
    case 63:
    case "CRACKLINGAXEMITACHURL":
      return Enemy.CRACKLINGAXEMITACHURL;
    case 64:
    case "CRYOABYSSMAGE":
      return Enemy.CRYOABYSSMAGE;
    case 65:
    case "CRYOCICIN":
      return Enemy.CRYOCICIN;
    case 66:
    case "CRYOHILICHURLGRENADIER":
      return Enemy.CRYOHILICHURLGRENADIER;
    case 67:
    case "CRYOHILICHURLSHOOTER":
      return Enemy.CRYOHILICHURLSHOOTER;
    case 68:
    case "CRYOHYPOSTASIS":
      return Enemy.CRYOHYPOSTASIS;
    case 69:
    case "CRYOREGISVINE":
      return Enemy.CRYOREGISVINE;
    case 70:
    case "CRYOSAMACHURL":
      return Enemy.CRYOSAMACHURL;
    case 71:
    case "CRYOSLIME":
      return Enemy.CRYOSLIME;
    case 72:
    case "CRYOSPECTER":
      return Enemy.CRYOSPECTER;
    case 73:
    case "CRYOWHOPPERFLOWER":
      return Enemy.CRYOWHOPPERFLOWER;
    case 74:
    case "DEEPWATERASSAULTMEK":
      return Enemy.DEEPWATERASSAULTMEK;
    case 75:
    case "DEFENSIVEPHYSICALTOWER":
      return Enemy.DEFENSIVEPHYSICALTOWER;
    case 76:
    case "DEFENSIVEPOINT56PUSHCONTESTDEFENSE":
      return Enemy.DEFENSIVEPOINT56PUSHCONTESTDEFENSE;
    case 77:
    case "DENDROHYPOSTASIS":
      return Enemy.DENDROHYPOSTASIS;
    case 78:
    case "DENDROSAMACHURL":
      return Enemy.DENDROSAMACHURL;
    case 79:
    case "DENDROSLIME":
      return Enemy.DENDROSLIME;
    case 80:
    case "DENDROSPECTER":
      return Enemy.DENDROSPECTER;
    case 81:
    case "ELECTROABYSSMAGE":
      return Enemy.ELECTROABYSSMAGE;
    case 82:
    case "ELECTROCICIN":
      return Enemy.ELECTROCICIN;
    case 83:
    case "ELECTROHILICHURLGRENADIER":
      return Enemy.ELECTROHILICHURLGRENADIER;
    case 84:
    case "ELECTROHILICHURLSHOOTER":
      return Enemy.ELECTROHILICHURLSHOOTER;
    case 85:
    case "ELECTROHYPOSTASIS":
      return Enemy.ELECTROHYPOSTASIS;
    case 86:
    case "ELECTROREGISVINE":
      return Enemy.ELECTROREGISVINE;
    case 87:
    case "ELECTROSAMACHURL":
      return Enemy.ELECTROSAMACHURL;
    case 88:
    case "ELECTROSLIME":
      return Enemy.ELECTROSLIME;
    case 89:
    case "ELECTROSPECTER":
      return Enemy.ELECTROSPECTER;
    case 90:
    case "ELECTROWHOPPERFLOWER":
      return Enemy.ELECTROWHOPPERFLOWER;
    case 91:
    case "EMPEROROFFIREANDIRON":
      return Enemy.EMPEROROFFIREANDIRON;
    case 92:
    case "EREMITEAXEVANGUARD":
      return Enemy.EREMITEAXEVANGUARD;
    case 93:
    case "EREMITECROSSBOW":
      return Enemy.EREMITECROSSBOW;
    case 94:
    case "EREMITEDAYTHUNDER":
      return Enemy.EREMITEDAYTHUNDER;
    case 95:
    case "EREMITEDESERTCLEARWATER":
      return Enemy.EREMITEDESERTCLEARWATER;
    case 96:
    case "EREMITEFLORALRINGDANCER":
      return Enemy.EREMITEFLORALRINGDANCER;
    case 97:
    case "EREMITEGALEHUNTER":
      return Enemy.EREMITEGALEHUNTER;
    case 98:
    case "EREMITELINEBREAKER":
      return Enemy.EREMITELINEBREAKER;
    case 99:
    case "EREMITERAVENBEAKHALBERDIER":
      return Enemy.EREMITERAVENBEAKHALBERDIER;
    case 100:
    case "EREMITESCORCHINGLOREMASTER":
      return Enemy.EREMITESCORCHINGLOREMASTER;
    case 101:
    case "EREMITESTONEENCHANTER":
      return Enemy.EREMITESTONEENCHANTER;
    case 102:
    case "EREMITESUNFROST":
      return Enemy.EREMITESUNFROST;
    case 103:
    case "EREMITESWORDDANCER":
      return Enemy.EREMITESWORDDANCER;
    case 104:
    case "ERODINGAVATAROFLAVA":
      return Enemy.ERODINGAVATAROFLAVA;
    case 105:
    case "EXPERIMENTALFIELDGENERATOR":
      return Enemy.EXPERIMENTALFIELDGENERATOR;
    case 106:
    case "EYEOFTHESTORM":
      return Enemy.EYEOFTHESTORM;
    case 107:
    case "FATUICRYOCICINMAGE":
      return Enemy.FATUICRYOCICINMAGE;
    case 108:
    case "FATUIELECTROCICINMAGE":
      return Enemy.FATUIELECTROCICINMAGE;
    case 109:
    case "FATUIPYROAGENT":
      return Enemy.FATUIPYROAGENT;
    case 110:
    case "FATUISKIRMISHERANEMOBOXERVANGUARD":
      return Enemy.FATUISKIRMISHERANEMOBOXERVANGUARD;
    case 111:
    case "FATUISKIRMISHERCRYOGUNNERLEGIONNAIRE":
      return Enemy.FATUISKIRMISHERCRYOGUNNERLEGIONNAIRE;
    case 112:
    case "FATUISKIRMISHERELECTROHAMMERVANGUARD":
      return Enemy.FATUISKIRMISHERELECTROHAMMERVANGUARD;
    case 113:
    case "FATUISKIRMISHERGEOCHANTERBRACER":
      return Enemy.FATUISKIRMISHERGEOCHANTERBRACER;
    case 114:
    case "FATUISKIRMISHERHYDROGUNNERLEGIONNAIRE":
      return Enemy.FATUISKIRMISHERHYDROGUNNERLEGIONNAIRE;
    case 115:
    case "FATUISKIRMISHERPYROSLINGERBRACER":
      return Enemy.FATUISKIRMISHERPYROSLINGERBRACER;
    case 116:
    case "FEROCIOUSWARRIORGRAPPLER":
      return Enemy.FEROCIOUSWARRIORGRAPPLER;
    case 117:
    case "FEROCIOUSWARRIORHUMANRAM":
      return Enemy.FEROCIOUSWARRIORHUMANRAM;
    case 118:
    case "FEROCIOUSWARRIORWRESTLER":
      return Enemy.FEROCIOUSWARRIORWRESTLER;
    case 119:
    case "FLOATINGANEMOFUNGUS":
      return Enemy.FLOATINGANEMOFUNGUS;
    case 120:
    case "FLOATINGDENDROFUNGUS":
      return Enemy.FLOATINGDENDROFUNGUS;
    case 121:
    case "FLOATINGHYDROFUNGUS":
      return Enemy.FLOATINGHYDROFUNGUS;
    case 122:
    case "FLOWINGBLADEGREASESAW":
      return Enemy.FLOWINGBLADEGREASESAW;
    case 123:
    case "FLOWINGBLADEHARPOONTHROWER":
      return Enemy.FLOWINGBLADEHARPOONTHROWER;
    case 124:
    case "FLOWINGBLADESKIRMISHER":
      return Enemy.FLOWINGBLADESKIRMISHER;
    case 125:
    case "FLOWINVERTEDWAYOBMANIFESTATION":
      return Enemy.FLOWINVERTEDWAYOBMANIFESTATION;
    case 126:
    case "FLUIDAVATAROFLAVA":
      return Enemy.FLUIDAVATAROFLAVA;
    case 127:
    case "FOLIARSWIFTWAYOBMANIFESTATION":
      return Enemy.FOLIARSWIFTWAYOBMANIFESTATION;
    case 128:
    case "FORGEDSANDINTERROGATOR":
      return Enemy.FORGEDSANDINTERROGATOR;
    case 129:
    case "FORGEDSANDJAVELINEER":
      return Enemy.FORGEDSANDJAVELINEER;
    case 130:
    case "FORGEDSANDSHIELDBREAKER":
      return Enemy.FORGEDSANDSHIELDBREAKER;
    case 131:
    case "FROSTARMLAWACHURL":
      return Enemy.FROSTARMLAWACHURL;
    case 132:
    case "FROSTOPERATIVE":
      return Enemy.FROSTOPERATIVE;
    case 133:
    case "FURNACESHELLMOUNTAINWEASEL":
      return Enemy.FURNACESHELLMOUNTAINWEASEL;
    case 134:
    case "GEOHYPOSTASIS":
      return Enemy.GEOHYPOSTASIS;
    case 135:
    case "GEOLOGICALSURVEYMEK":
      return Enemy.GEOLOGICALSURVEYMEK;
    case 136:
    case "GEOSAMACHURL":
      return Enemy.GEOSAMACHURL;
    case 137:
    case "GEOSLIME":
      return Enemy.GEOSLIME;
    case 138:
    case "GEOSPECTER":
      return Enemy.GEOSPECTER;
    case 139:
    case "GEOVISHAP":
      return Enemy.GEOVISHAP;
    case 140:
    case "GEOVISHAPHATCHLING":
      return Enemy.GEOVISHAPHATCHLING;
    case 141:
    case "GLUTTONOUSYUMKASAURMOUNTAINKING":
      return Enemy.GLUTTONOUSYUMKASAURMOUNTAINKING;
    case 142:
    case "GOLDENWOLFLORD":
      return Enemy.GOLDENWOLFLORD;
    case 143:
    case "GOLDFLAMEQUCUSAURTYRANT":
      return Enemy.GOLDFLAMEQUCUSAURTYRANT;
    case 144:
    case "GROUNDEDGEOSHROOM":
      return Enemy.GROUNDEDGEOSHROOM;
    case 145:
    case "GROUNDEDHYDROSHROOM":
      return Enemy.GROUNDEDHYDROSHROOM;
    case 146:
    case "GUARDIANOFAPEPSOASIS":
      return Enemy.GUARDIANOFAPEPSOASIS;
    case 147:
    case "HALFTULPA":
      return Enemy.HALFTULPA;
    case 148:
    case "HATJELLYFISH":
      return Enemy.HATJELLYFISH;
    case 149:
    case "HILICHURL":
      return Enemy.HILICHURL;
    case 150:
    case "HILICHURLBERSERKER":
      return Enemy.HILICHURLBERSERKER;
    case 151:
    case "HILICHURLFIGHTER":
      return Enemy.HILICHURLFIGHTER;
    case 152:
    case "HILICHURLGRENADIER":
      return Enemy.HILICHURLGRENADIER;
    case 153:
    case "HILICHURLSHOOTER":
      return Enemy.HILICHURLSHOOTER;
    case 154:
    case "HUNTERSRAY":
      return Enemy.HUNTERSRAY;
    case 155:
    case "HYDROABYSSMAGE":
      return Enemy.HYDROABYSSMAGE;
    case 156:
    case "HYDROCICIN":
      return Enemy.HYDROCICIN;
    case 157:
    case "HYDROHILICHURLROGUE":
      return Enemy.HYDROHILICHURLROGUE;
    case 158:
    case "HYDROHYPOSTASIS":
      return Enemy.HYDROHYPOSTASIS;
    case 159:
    case "HYDROHYPOSTASISSUMMON":
      return Enemy.HYDROHYPOSTASISSUMMON;
    case 160:
    case "HYDROMIMICBOAR":
      return Enemy.HYDROMIMICBOAR;
    case 161:
    case "HYDROMIMICCRAB":
      return Enemy.HYDROMIMICCRAB;
    case 162:
    case "HYDROMIMICCRANE":
      return Enemy.HYDROMIMICCRANE;
    case 163:
    case "HYDROMIMICFINCH":
      return Enemy.HYDROMIMICFINCH;
    case 164:
    case "HYDROMIMICFROG":
      return Enemy.HYDROMIMICFROG;
    case 165:
    case "HYDROMIMICMALLARD":
      return Enemy.HYDROMIMICMALLARD;
    case 166:
    case "HYDROMIMICRAPTOR":
      return Enemy.HYDROMIMICRAPTOR;
    case 167:
    case "HYDROMIMICSQUIRREL":
      return Enemy.HYDROMIMICSQUIRREL;
    case 168:
    case "HYDROSAMACHURL":
      return Enemy.HYDROSAMACHURL;
    case 169:
    case "HYDROSLIME":
      return Enemy.HYDROSLIME;
    case 170:
    case "HYDROSPECTER":
      return Enemy.HYDROSPECTER;
    case 171:
    case "HYDROTULPA":
      return Enemy.HYDROTULPA;
    case 172:
    case "ICESHIELDHILICHURLGUARD":
      return Enemy.ICESHIELDHILICHURLGUARD;
    case 173:
    case "ICESHIELDWALLMITACHURL":
      return Enemy.ICESHIELDWALLMITACHURL;
    case 174:
    case "ICEWINDSUITE":
      return Enemy.ICEWINDSUITE;
    case 175:
    case "IKTOMISAURUS":
      return Enemy.IKTOMISAURUS;
    case 176:
    case "IKTOMISAURUSCHICK":
      return Enemy.IKTOMISAURUSCHICK;
    case 177:
    case "IKTOMISAURUSWARRIORCRYOCRYSTALCANNON":
      return Enemy.IKTOMISAURUSWARRIORCRYOCRYSTALCANNON;
    case 178:
    case "IKTOMISAURUSWARRIORICYTIDEBEARER":
      return Enemy.IKTOMISAURUSWARRIORICYTIDEBEARER;
    case 179:
    case "INIQUITOUSBAPTIST":
      return Enemy.INIQUITOUSBAPTIST;
    case 180:
    case "JADEPLUMETERRORSHROOM":
      return Enemy.JADEPLUMETERRORSHROOM;
    case 181:
    case "KAIRAGIDANCINGTHUNDER":
      return Enemy.KAIRAGIDANCINGTHUNDER;
    case 182:
    case "KAIRAGIFIERYMIGHT":
      return Enemy.KAIRAGIFIERYMIGHT;
    case 183:
    case "KOHOLASAURUS":
      return Enemy.KOHOLASAURUS;
    case 184:
    case "KOHOLASAURUSWARRIORREEFSPLITTER":
      return Enemy.KOHOLASAURUSWARRIORREEFSPLITTER;
    case 185:
    case "KOHOLASAURUSWARRIORWAVESHUTTLER":
      return Enemy.KOHOLASAURUSWARRIORWAVESHUTTLER;
    case 186:
    case "KOHOLASAURWHELP":
      return Enemy.KOHOLASAURWHELP;
    case 187:
    case "LARGEANEMOSLIME":
      return Enemy.LARGEANEMOSLIME;
    case 188:
    case "LARGECRYOSLIME":
      return Enemy.LARGECRYOSLIME;
    case 189:
    case "LARGEDENDROSLIME":
      return Enemy.LARGEDENDROSLIME;
    case 190:
    case "LARGEELECTROSLIME":
      return Enemy.LARGEELECTROSLIME;
    case 191:
    case "LARGEGEOSLIME":
      return Enemy.LARGEGEOSLIME;
    case 192:
    case "LARGEHYDROSLIME":
      return Enemy.LARGEHYDROSLIME;
    case 193:
    case "LARGEOVERGROWNBREACHERPRIMUS":
      return Enemy.LARGEOVERGROWNBREACHERPRIMUS;
    case 194:
    case "LARGEPYROSLIME":
      return Enemy.LARGEPYROSLIME;
    case 195:
    case "LARGESHATTERSTONEBREACHERPRIMUS":
      return Enemy.LARGESHATTERSTONEBREACHERPRIMUS;
    case 196:
    case "LASIGNORA":
      return Enemy.LASIGNORA;
    case 197:
    case "LAVADRAGONSTATUE":
      return Enemy.LAVADRAGONSTATUE;
    case 198:
    case "LEGATUSGOLEM":
      return Enemy.LEGATUSGOLEM;
    case 199:
    case "LOCALLEGENDARMOREDCRAB":
      return Enemy.LOCALLEGENDARMOREDCRAB;
    case 200:
    case "LOCALLEGENDBLUBBERBEAST":
      return Enemy.LOCALLEGENDBLUBBERBEAST;
    case 201:
    case "LOCALLEGENDCHERUBICSEAHARE":
      return Enemy.LOCALLEGENDCHERUBICSEAHARE;
    case 202:
    case "LOCALLEGENDHATJELLYFISH":
      return Enemy.LOCALLEGENDHATJELLYFISH;
    case 203:
    case "LOCALLEGENDHUNTERSRAY":
      return Enemy.LOCALLEGENDHUNTERSRAY;
    case 204:
    case "LORDOFERODEDPRIMALFIRE":
      return Enemy.LORDOFERODEDPRIMALFIRE;
    case 205:
    case "LUPUSBOREASDOMINATOROFWOLVES":
      return Enemy.LUPUSBOREASDOMINATOROFWOLVES;
    case 206:
    case "MAGATSUMITAKENARUKAMINOMIKOTO":
      return Enemy.MAGATSUMITAKENARUKAMINOMIKOTO;
    case 207:
    case "MAGUUKENKI":
      return Enemy.MAGUUKENKI;
    case 208:
    case "MAGUUKENKIGALLOPINGFROST":
      return Enemy.MAGUUKENKIGALLOPINGFROST;
    case 209:
    case "MAGUUKENKILONEGALE":
      return Enemy.MAGUUKENKILONEGALE;
    case 210:
    case "MAGUUKENKIMASKOFTERROR":
      return Enemy.MAGUUKENKIMASKOFTERROR;
    case 211:
    case "MILLELITHSERGEANT":
      return Enemy.MILLELITHSERGEANT;
    case 212:
    case "MILLELITHSOLDIER":
      return Enemy.MILLELITHSOLDIER;
    case 213:
    case "MILLENNIALPEARLSEAHORSE":
      return Enemy.MILLENNIALPEARLSEAHORSE;
    case 214:
    case "MIRRORMAIDEN":
      return Enemy.MIRRORMAIDEN;
    case 215:
    case "MUTANTELECTROSLIME":
      return Enemy.MUTANTELECTROSLIME;
    case 216:
    case "NIMBLEHARVESTERMEK":
      return Enemy.NIMBLEHARVESTERMEK;
    case 217:
    case "NOBUSHIHITSUKEBAN":
      return Enemy.NOBUSHIHITSUKEBAN;
    case 218:
    case "NOBUSHIJINTOUBAN":
      return Enemy.NOBUSHIJINTOUBAN;
    case 219:
    case "NOBUSHIKIKOUBAN":
      return Enemy.NOBUSHIKIKOUBAN;
    case 220:
    case "OCEANID":
      return Enemy.OCEANID;
    case 221:
    case "OCHIMUSHACANKEREDFLAME":
      return Enemy.OCHIMUSHACANKEREDFLAME;
    case 222:
    case "OCHIMUSHAENSORCELLEDTHUNDER":
      return Enemy.OCHIMUSHAENSORCELLEDTHUNDER;
    case 223:
    case "OVERGROWNBREACHERPRIMUS":
      return Enemy.OVERGROWNBREACHERPRIMUS;
    case 224:
    case "PERPETUALMECHANICALARRAY":
      return Enemy.PERPETUALMECHANICALARRAY;
    case 225:
    case "PRAETORIANGOLEM":
      return Enemy.PRAETORIANGOLEM;
    case 226:
    case "PRIMALCONSTRUCTPROSPECTOR":
      return Enemy.PRIMALCONSTRUCTPROSPECTOR;
    case 227:
    case "PRIMALCONSTRUCTREPULSOR":
      return Enemy.PRIMALCONSTRUCTREPULSOR;
    case 228:
    case "PRIMALCONSTRUCTRESHAPER":
      return Enemy.PRIMALCONSTRUCTRESHAPER;
    case 229:
    case "PRIMOGEOVISHAP":
      return Enemy.PRIMOGEOVISHAP;
    case 230:
    case "PRIMORDIALBATHYSMALVISHAP":
      return Enemy.PRIMORDIALBATHYSMALVISHAP;
    case 231:
    case "PYROABYSSMAGE":
      return Enemy.PYROABYSSMAGE;
    case 232:
    case "PYROHILICHURLSHOOTER":
      return Enemy.PYROHILICHURLSHOOTER;
    case 233:
    case "PYROHYPOSTASIS":
      return Enemy.PYROHYPOSTASIS;
    case 234:
    case "PYROREGISVINE":
      return Enemy.PYROREGISVINE;
    case 235:
    case "PYROSLIME":
      return Enemy.PYROSLIME;
    case 236:
    case "PYROSPECTER":
      return Enemy.PYROSPECTER;
    case 237:
    case "PYROWHOPPERFLOWER":
      return Enemy.PYROWHOPPERFLOWER;
    case 238:
    case "QUCUSAURUS":
      return Enemy.QUCUSAURUS;
    case 239:
    case "QUCUSAURUSCHICK":
      return Enemy.QUCUSAURUSCHICK;
    case 240:
    case "QUCUSAURUSWARRIORBLAZINGSKY":
      return Enemy.QUCUSAURUSWARRIORBLAZINGSKY;
    case 241:
    case "QUCUSAURUSWARRIORHEARTSTARHAMMER":
      return Enemy.QUCUSAURUSWARRIORHEARTSTARHAMMER;
    case 242:
    case "RECONLOGMEK":
      return Enemy.RECONLOGMEK;
    case 243:
    case "RIMEBITERBATHYSMALVISHAP":
      return Enemy.RIMEBITERBATHYSMALVISHAP;
    case 244:
    case "ROCKCAVERNOUSWAYOBMANIFESTATION":
      return Enemy.ROCKCAVERNOUSWAYOBMANIFESTATION;
    case 245:
    case "ROCKFONDRIFTHOUND":
      return Enemy.ROCKFONDRIFTHOUND;
    case 246:
    case "ROCKFONDRIFTHOUNDWHELP":
      return Enemy.ROCKFONDRIFTHOUNDWHELP;
    case 247:
    case "ROCKSHIELDHILICHURLGUARD":
      return Enemy.ROCKSHIELDHILICHURLGUARD;
    case 248:
    case "ROCKSHIELDWALLMITACHURL":
      return Enemy.ROCKSHIELDWALLMITACHURL;
    case 249:
    case "RUINCRUISER":
      return Enemy.RUINCRUISER;
    case 250:
    case "RUINDEFENDER":
      return Enemy.RUINDEFENDER;
    case 251:
    case "RUINDESTROYER":
      return Enemy.RUINDESTROYER;
    case 252:
    case "RUINDRAKEEARTHGUARD":
      return Enemy.RUINDRAKEEARTHGUARD;
    case 253:
    case "RUINDRAKESKYWATCH":
      return Enemy.RUINDRAKESKYWATCH;
    case 254:
    case "RUINGRADER":
      return Enemy.RUINGRADER;
    case 255:
    case "RUINGUARD":
      return Enemy.RUINGUARD;
    case 256:
    case "RUINHUNTER":
      return Enemy.RUINHUNTER;
    case 257:
    case "RUINSCOUT":
      return Enemy.RUINSCOUT;
    case 258:
    case "RUINSERPENT":
      return Enemy.RUINSERPENT;
    case 259:
    case "RULEROFTHECHIZHANGMOUNTAINSTIANYU":
      return Enemy.RULEROFTHECHIZHANGMOUNTAINSTIANYU;
    case 260:
    case "RULEROFTHECHIZHANGMOUNTAINSYIJI":
      return Enemy.RULEROFTHECHIZHANGMOUNTAINSYIJI;
    case 261:
    case "SAMACHURLBOSS":
      return Enemy.SAMACHURLBOSS;
    case 262:
    case "SANGONOMIYACOHORT":
      return Enemy.SANGONOMIYACOHORT;
    case 263:
    case "SECRETSOURCEAUTOMATONCONFIGURATIONDEVICE":
      return Enemy.SECRETSOURCEAUTOMATONCONFIGURATIONDEVICE;
    case 264:
    case "SECRETSOURCEAUTOMATONHUNTERSEEKER":
      return Enemy.SECRETSOURCEAUTOMATONHUNTERSEEKER;
    case 265:
    case "SECRETSOURCEAUTOMATONOVERSEERDEVICE":
      return Enemy.SECRETSOURCEAUTOMATONOVERSEERDEVICE;
    case 266:
    case "SETEKHWENUT":
      return Enemy.SETEKHWENUT;
    case 267:
    case "SHADOWYHUSKDEFENDER":
      return Enemy.SHADOWYHUSKDEFENDER;
    case 268:
    case "SHADOWYHUSKLINEBREAKER":
      return Enemy.SHADOWYHUSKLINEBREAKER;
    case 269:
    case "SHADOWYHUSKSTANDARDBEARER":
      return Enemy.SHADOWYHUSKSTANDARDBEARER;
    case 270:
    case "SHATTERSTONEBREACHERPRIMUS":
      return Enemy.SHATTERSTONEBREACHERPRIMUS;
    case 271:
    case "SHOGUNATEINFANTRY":
      return Enemy.SHOGUNATEINFANTRY;
    case 272:
    case "SHOGUNATEINFANTRYCAPTAIN":
      return Enemy.SHOGUNATEINFANTRYCAPTAIN;
    case 273:
    case "SHOUKINOKAMITHEPRODIGAL":
      return Enemy.SHOUKINOKAMITHEPRODIGAL;
    case 274:
    case "SOLITARYSUANNI":
      return Enemy.SOLITARYSUANNI;
    case 275:
    case "SPIRITOFOMENDENDROSPIRITSERPENT":
      return Enemy.SPIRITOFOMENDENDROSPIRITSERPENT;
    case 276:
    case "SPIRITOFOMENPYROSCORPION":
      return Enemy.SPIRITOFOMENPYROSCORPION;
    case 277:
    case "SPIRITOFOMENSTONEDRAKE":
      return Enemy.SPIRITOFOMENSTONEDRAKE;
    case 278:
    case "SPIRITOFOMENWINDGLEDE":
      return Enemy.SPIRITOFOMENWINDGLEDE;
    case 279:
    case "SPIRITSPEAKERWARRIORCONTEMPLATOR":
      return Enemy.SPIRITSPEAKERWARRIORCONTEMPLATOR;
    case 280:
    case "SPIRITSPEAKERWARRIORDETERMINATOR":
      return Enemy.SPIRITSPEAKERWARRIORDETERMINATOR;
    case 281:
    case "SPIRITSPEAKERWARRIORPSYCHOKINETIC":
      return Enemy.SPIRITSPEAKERWARRIORPSYCHOKINETIC;
    case 282:
    case "STERNSHIELDCRAB":
      return Enemy.STERNSHIELDCRAB;
    case 283:
    case "STONEHIDELAWACHURL":
      return Enemy.STONEHIDELAWACHURL;
    case 284:
    case "STORMTERROR":
      return Enemy.STORMTERROR;
    case 285:
    case "STRETCHYANEMOFUNGUS":
      return Enemy.STRETCHYANEMOFUNGUS;
    case 286:
    case "STRETCHYELECTROFUNGUS":
      return Enemy.STRETCHYELECTROFUNGUS;
    case 287:
    case "STRETCHYGEOFUNGUS":
      return Enemy.STRETCHYGEOFUNGUS;
    case 288:
    case "STRETCHYPYROFUNGUS":
      return Enemy.STRETCHYPYROFUNGUS;
    case 289:
    case "SUBLIMATEDQUEEN":
      return Enemy.SUBLIMATEDQUEEN;
    case 290:
    case "SUPPRESSIONSPECIALISTMEK":
      return Enemy.SUPPRESSIONSPECIALISTMEK;
    case 291:
    case "SWIFTSTEPARMEDCOURIER":
      return Enemy.SWIFTSTEPARMEDCOURIER;
    case 292:
    case "SWIFTSTEPSEEKER":
      return Enemy.SWIFTSTEPSEEKER;
    case 293:
    case "SWIFTSTEPSTORMSCOUT":
      return Enemy.SWIFTSTEPSTORMSCOUT;
    case 294:
    case "TAINTEDWATERSPLITTINGPHANTASM":
      return Enemy.TAINTEDWATERSPLITTINGPHANTASM;
    case 295:
    case "TAINTEDWATERSPOUTINGPHANTASM":
      return Enemy.TAINTEDWATERSPOUTINGPHANTASM;
    case 296:
    case "TATANKASAURUS":
      return Enemy.TATANKASAURUS;
    case 297:
    case "TATANKASAURUSWARRIORSKYBREAKER":
      return Enemy.TATANKASAURUSWARRIORSKYBREAKER;
    case 298:
    case "TATANKASAURUSWARRIORSPIRITLIGHTCHASER":
      return Enemy.TATANKASAURUSWARRIORSPIRITLIGHTCHASER;
    case 299:
    case "TATANKASAURWHELP":
      return Enemy.TATANKASAURWHELP;
    case 300:
    case "TENEBROUSMIMIFLORA":
      return Enemy.TENEBROUSMIMIFLORA;
    case 301:
    case "TENEBROUSPAPILLATYPEI":
      return Enemy.TENEBROUSPAPILLATYPEI;
    case 302:
    case "TEPETLISAURUS":
      return Enemy.TEPETLISAURUS;
    case 303:
    case "TEPETLISAURUSTRIBECHIEF":
      return Enemy.TEPETLISAURUSTRIBECHIEF;
    case 304:
    case "TEPETLISAURUSWARRIORROCKBREAKERBLADE":
      return Enemy.TEPETLISAURUSWARRIORROCKBREAKERBLADE;
    case 305:
    case "TEPETLISAURUSWARRIORSHARDSTRIKER":
      return Enemy.TEPETLISAURUSWARRIORSHARDSTRIKER;
    case 306:
    case "TEPETLISAURWHELP":
      return Enemy.TEPETLISAURWHELP;
    case 307:
    case "THEGAMEBEFORETHEGATE":
      return Enemy.THEGAMEBEFORETHEGATE;
    case 308:
    case "THEKNAVE":
      return Enemy.THEKNAVE;
    case 309:
    case "THUNDERCRAVENRIFTHOUND":
      return Enemy.THUNDERCRAVENRIFTHOUND;
    case 310:
    case "THUNDERCRAVENRIFTHOUNDWHELP":
      return Enemy.THUNDERCRAVENRIFTHOUNDWHELP;
    case 311:
    case "THUNDERHELMLAWACHURL":
      return Enemy.THUNDERHELMLAWACHURL;
    case 312:
    case "THUNDERINGWAYOBMANIFESTATION":
      return Enemy.THUNDERINGWAYOBMANIFESTATION;
    case 313:
    case "THUNDERMANIFESTATION":
      return Enemy.THUNDERMANIFESTATION;
    case 314:
    case "TREASUREHOARDERSBOSS":
      return Enemy.TREASUREHOARDERSBOSS;
    case 315:
    case "TREASUREHOARDERSCARMEN":
      return Enemy.TREASUREHOARDERSCARMEN;
    case 316:
    case "TREASUREHOARDERSCRUSHER":
      return Enemy.TREASUREHOARDERSCRUSHER;
    case 317:
    case "TREASUREHOARDERSCRYOPOTIONEER":
      return Enemy.TREASUREHOARDERSCRYOPOTIONEER;
    case 318:
    case "TREASUREHOARDERSELECTROPOTIONEER":
      return Enemy.TREASUREHOARDERSELECTROPOTIONEER;
    case 319:
    case "TREASUREHOARDERSGRAVEDIGGER":
      return Enemy.TREASUREHOARDERSGRAVEDIGGER;
    case 320:
    case "TREASUREHOARDERSHANDYMAN":
      return Enemy.TREASUREHOARDERSHANDYMAN;
    case 321:
    case "TREASUREHOARDERSHYDROPOTIONEER":
      return Enemy.TREASUREHOARDERSHYDROPOTIONEER;
    case 322:
    case "TREASUREHOARDERSLIULIU":
      return Enemy.TREASUREHOARDERSLIULIU;
    case 323:
    case "TREASUREHOARDERSMARKSMAN":
      return Enemy.TREASUREHOARDERSMARKSMAN;
    case 324:
    case "TREASUREHOARDERSPUGILIST":
      return Enemy.TREASUREHOARDERSPUGILIST;
    case 325:
    case "TREASUREHOARDERSPYROPOTIONEER":
      return Enemy.TREASUREHOARDERSPYROPOTIONEER;
    case 326:
    case "TREASUREHOARDERSRAPTOR":
      return Enemy.TREASUREHOARDERSRAPTOR;
    case 327:
    case "TREASUREHOARDERSSCOUT":
      return Enemy.TREASUREHOARDERSSCOUT;
    case 328:
    case "TREASUREHOARDERSSEAMAN":
      return Enemy.TREASUREHOARDERSSEAMAN;
    case 329:
    case "TREASUREHOARDERSWALLENSTEIN":
      return Enemy.TREASUREHOARDERSWALLENSTEIN;
    case 330:
    case "UNDERWATERPATROLMEK":
      return Enemy.UNDERWATERPATROLMEK;
    case 331:
    case "UNDERWATERSURVEYMEK":
      return Enemy.UNDERWATERSURVEYMEK;
    case 332:
    case "UNUSUALHILICHURL":
      return Enemy.UNUSUALHILICHURL;
    case 333:
    case "VETERANARITHMETICENHANCERMEK":
      return Enemy.VETERANARITHMETICENHANCERMEK;
    case 334:
    case "VETERANFATUIPYROAGENT":
      return Enemy.VETERANFATUIPYROAGENT;
    case 335:
    case "VETERANFATUISKIRMISHERCRYOGUNNERLEGIONNAIRE":
      return Enemy.VETERANFATUISKIRMISHERCRYOGUNNERLEGIONNAIRE;
    case 336:
    case "VETERANFATUISKIRMISHERELECTROHAMMERVANGUARD":
      return Enemy.VETERANFATUISKIRMISHERELECTROHAMMERVANGUARD;
    case 337:
    case "VETERANFATUISKIRMISHERPYROSLINGERBRACER":
      return Enemy.VETERANFATUISKIRMISHERPYROSLINGERBRACER;
    case 338:
    case "VETERANFROSTOPERATIVE":
      return Enemy.VETERANFROSTOPERATIVE;
    case 339:
    case "VETERANTAINTEDWATERSPLITTINGPHANTASM":
      return Enemy.VETERANTAINTEDWATERSPLITTINGPHANTASM;
    case 340:
    case "VETERANTAINTEDWATERSPOUTINGPHANTASM":
      return Enemy.VETERANTAINTEDWATERSPOUTINGPHANTASM;
    case 341:
    case "VETERANWINDOPERATIVE":
      return Enemy.VETERANWINDOPERATIVE;
    case 342:
    case "WAYWARDHERMETICSPIRITSPEAKER":
      return Enemy.WAYWARDHERMETICSPIRITSPEAKER;
    case 343:
    case "WHIRLINGCRYOFUNGUS":
      return Enemy.WHIRLINGCRYOFUNGUS;
    case 344:
    case "WHIRLINGELECTROFUNGUS":
      return Enemy.WHIRLINGELECTROFUNGUS;
    case 345:
    case "WHIRLINGPYROFUNGUS":
      return Enemy.WHIRLINGPYROFUNGUS;
    case 346:
    case "WINDOPERATIVE":
      return Enemy.WINDOPERATIVE;
    case 347:
    case "WINGEDCRYOSHROOM":
      return Enemy.WINGEDCRYOSHROOM;
    case 348:
    case "WINGEDDENDROSHROOM":
      return Enemy.WINGEDDENDROSHROOM;
    case 349:
    case "WINGEDWARRIORFEATHERSHEDDER":
      return Enemy.WINGEDWARRIORFEATHERSHEDDER;
    case 350:
    case "WINGEDWARRIORSKYMASTER":
      return Enemy.WINGEDWARRIORSKYMASTER;
    case 351:
    case "WINGEDWARRIORSKYSOARER":
      return Enemy.WINGEDWARRIORSKYSOARER;
    case 352:
    case "WOODENSHIELDHILICHURLGUARD":
      return Enemy.WOODENSHIELDHILICHURLGUARD;
    case 353:
    case "WOODENSHIELDWALLMITACHURL":
      return Enemy.WOODENSHIELDWALLMITACHURL;
    case 354:
    case "XUANWENBEAST":
      return Enemy.XUANWENBEAST;
    case 355:
    case "YORIKISAMURAI":
      return Enemy.YORIKISAMURAI;
    case 356:
    case "YUMKASAURUS":
      return Enemy.YUMKASAURUS;
    case 357:
    case "YUMKASAURUSWARRIORFLOWINGSKYFIRE":
      return Enemy.YUMKASAURUSWARRIORFLOWINGSKYFIRE;
    case 358:
    case "YUMKASAURUSWARRIORWHIRLINGLEAVES":
      return Enemy.YUMKASAURUSWARRIORWHIRLINGLEAVES;
    case 359:
    case "YUMKASAURWHELP":
      return Enemy.YUMKASAURWHELP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Enemy.UNRECOGNIZED;
  }
}

export function enemyToJSON(object: Enemy): string {
  switch (object) {
    case Enemy.ENEMY_UNSPECIFIED:
      return "ENEMY_UNSPECIFIED";
    case Enemy.ABYSSHERALDFROSTFALL:
      return "ABYSSHERALDFROSTFALL";
    case Enemy.ABYSSHERALDWICKEDTORRENTS:
      return "ABYSSHERALDWICKEDTORRENTS";
    case Enemy.ABYSSLECTORFATHOMLESSFLAMES:
      return "ABYSSLECTORFATHOMLESSFLAMES";
    case Enemy.ABYSSLECTORVIOLETLIGHTNING:
      return "ABYSSLECTORVIOLETLIGHTNING";
    case Enemy.ADVANCEDDEFENSIVEANEMOTOWER:
      return "ADVANCEDDEFENSIVEANEMOTOWER";
    case Enemy.ADVANCEDDEFENSIVECRYOTOWER:
      return "ADVANCEDDEFENSIVECRYOTOWER";
    case Enemy.ADVANCEDDEFENSIVEELECTROTOWER:
      return "ADVANCEDDEFENSIVEELECTROTOWER";
    case Enemy.ADVANCEDDEFENSIVEHYDROTOWER:
      return "ADVANCEDDEFENSIVEHYDROTOWER";
    case Enemy.ADVANCEDDEFENSIVEPYROTOWER:
      return "ADVANCEDDEFENSIVEPYROTOWER";
    case Enemy.AEONBLIGHTDRAKE:
      return "AEONBLIGHTDRAKE";
    case Enemy.ALGORITHMOFSEMIINTRANSIENTMATRIXOFOVERSEERNETWORK:
      return "ALGORITHMOFSEMIINTRANSIENTMATRIXOFOVERSEERNETWORK";
    case Enemy.ALLDEVOURINGNARWHAL:
      return "ALLDEVOURINGNARWHAL";
    case Enemy.ANEMOHILICHURLROGUE:
      return "ANEMOHILICHURLROGUE";
    case Enemy.ANEMOHYPOSTASIS:
      return "ANEMOHYPOSTASIS";
    case Enemy.ANEMOSAMACHURL:
      return "ANEMOSAMACHURL";
    case Enemy.ANEMOSLIME:
      return "ANEMOSLIME";
    case Enemy.ANEMOSPECTER:
      return "ANEMOSPECTER";
    case Enemy.ANGELICSEAHARE:
      return "ANGELICSEAHARE";
    case Enemy.ANNIHILATIONSPECIALISTMEK:
      return "ANNIHILATIONSPECIALISTMEK";
    case Enemy.AREAALERTMEK:
      return "AREAALERTMEK";
    case Enemy.ARITHMETICENHANCERMEK:
      return "ARITHMETICENHANCERMEK";
    case Enemy.ARMOREDCRAB:
      return "ARMOREDCRAB";
    case Enemy.ASCENDEDKING:
      return "ASCENDEDKING";
    case Enemy.ASSAULTSPECIALISTMEK:
      return "ASSAULTSPECIALISTMEK";
    case Enemy.AUTOMATONFUNGUSBALLOON:
      return "AUTOMATONFUNGUSBALLOON";
    case Enemy.AUTOMATONLARGESLIMEBALLOON:
      return "AUTOMATONLARGESLIMEBALLOON";
    case Enemy.AUTOMATONSMALLSLIMEBALLOON:
      return "AUTOMATONSMALLSLIMEBALLOON";
    case Enemy.AZHDAHA:
      return "AZHDAHA";
    case Enemy.BALLOCTOPUS:
      return "BALLOCTOPUS";
    case Enemy.BASICDEFENSIVEANEMOTOWER:
      return "BASICDEFENSIVEANEMOTOWER";
    case Enemy.BASICDEFENSIVECRYOTOWER:
      return "BASICDEFENSIVECRYOTOWER";
    case Enemy.BASICDEFENSIVEELECTROTOWER:
      return "BASICDEFENSIVEELECTROTOWER";
    case Enemy.BASICDEFENSIVEHYDROTOWER:
      return "BASICDEFENSIVEHYDROTOWER";
    case Enemy.BASICDEFENSIVEPYROTOWER:
      return "BASICDEFENSIVEPYROTOWER";
    case Enemy.BATTLEHARDENEDBITINGCOLDWAYOBMANIFESTATION:
      return "BATTLEHARDENEDBITINGCOLDWAYOBMANIFESTATION";
    case Enemy.BATTLEHARDENEDBURNINGAFLAMEWAYOBMANIFESTATION:
      return "BATTLEHARDENEDBURNINGAFLAMEWAYOBMANIFESTATION";
    case Enemy.BATTLEHARDENEDFLOWINVERTEDWAYOBMANIFESTATION:
      return "BATTLEHARDENEDFLOWINVERTEDWAYOBMANIFESTATION";
    case Enemy.BATTLEHARDENEDFOLIARSWIFTWAYOBMANIFESTATION:
      return "BATTLEHARDENEDFOLIARSWIFTWAYOBMANIFESTATION";
    case Enemy.BATTLEHARDENEDIKTOMISAURUS:
      return "BATTLEHARDENEDIKTOMISAURUS";
    case Enemy.BATTLEHARDENEDPRIMORDIALBATHYSMALVISHAP:
      return "BATTLEHARDENEDPRIMORDIALBATHYSMALVISHAP";
    case Enemy.BATTLEHARDENEDROCKCAVERNOUSWAYOBMANIFESTATION:
      return "BATTLEHARDENEDROCKCAVERNOUSWAYOBMANIFESTATION";
    case Enemy.BATTLEHARDENEDRUINDRAKEEARTHGUARD:
      return "BATTLEHARDENEDRUINDRAKEEARTHGUARD";
    case Enemy.BATTLEHARDENEDTATANKASAURUS:
      return "BATTLEHARDENEDTATANKASAURUS";
    case Enemy.BATTLEHARDENEDTHUNDERINGWAYOBMANIFESTATION:
      return "BATTLEHARDENEDTHUNDERINGWAYOBMANIFESTATION";
    case Enemy.BEISHT:
      return "BEISHT";
    case Enemy.BITINGCOLDWAYOBMANIFESTATION:
      return "BITINGCOLDWAYOBMANIFESTATION";
    case Enemy.BLACKSERPENTKNIGHTROCKBREAKERAX:
      return "BLACKSERPENTKNIGHTROCKBREAKERAX";
    case Enemy.BLACKSERPENTKNIGHTWINDCUTTER:
      return "BLACKSERPENTKNIGHTWINDCUTTER";
    case Enemy.BLAZINGAXEMITACHURL:
      return "BLAZINGAXEMITACHURL";
    case Enemy.BLUBBERBEAST:
      return "BLUBBERBEAST";
    case Enemy.BOLTEATERBATHYSMALVISHAP:
      return "BOLTEATERBATHYSMALVISHAP";
    case Enemy.BUBBLERSEAHORSE:
      return "BUBBLERSEAHORSE";
    case Enemy.BUBBLYSEAHORSE:
      return "BUBBLYSEAHORSE";
    case Enemy.BURNINGAFLAMEWAYOBMANIFESTATION:
      return "BURNINGAFLAMEWAYOBMANIFESTATION";
    case Enemy.CHERUBICSEAHARE:
      return "CHERUBICSEAHARE";
    case Enemy.CHILDE:
      return "CHILDE";
    case Enemy.CONSECRATEDFANGEDBEAST:
      return "CONSECRATEDFANGEDBEAST";
    case Enemy.CONSECRATEDFLYINGSERPENT:
      return "CONSECRATEDFLYINGSERPENT";
    case Enemy.CONSECRATEDHORNEDCROCODILE:
      return "CONSECRATEDHORNEDCROCODILE";
    case Enemy.CONSECRATEDREDVULTURE:
      return "CONSECRATEDREDVULTURE";
    case Enemy.CONSECRATEDSCORPION:
      return "CONSECRATEDSCORPION";
    case Enemy.CONSTRUCTIONSPECIALISTMEK:
      return "CONSTRUCTIONSPECIALISTMEK";
    case Enemy.CRACKLINGAXEMITACHURL:
      return "CRACKLINGAXEMITACHURL";
    case Enemy.CRYOABYSSMAGE:
      return "CRYOABYSSMAGE";
    case Enemy.CRYOCICIN:
      return "CRYOCICIN";
    case Enemy.CRYOHILICHURLGRENADIER:
      return "CRYOHILICHURLGRENADIER";
    case Enemy.CRYOHILICHURLSHOOTER:
      return "CRYOHILICHURLSHOOTER";
    case Enemy.CRYOHYPOSTASIS:
      return "CRYOHYPOSTASIS";
    case Enemy.CRYOREGISVINE:
      return "CRYOREGISVINE";
    case Enemy.CRYOSAMACHURL:
      return "CRYOSAMACHURL";
    case Enemy.CRYOSLIME:
      return "CRYOSLIME";
    case Enemy.CRYOSPECTER:
      return "CRYOSPECTER";
    case Enemy.CRYOWHOPPERFLOWER:
      return "CRYOWHOPPERFLOWER";
    case Enemy.DEEPWATERASSAULTMEK:
      return "DEEPWATERASSAULTMEK";
    case Enemy.DEFENSIVEPHYSICALTOWER:
      return "DEFENSIVEPHYSICALTOWER";
    case Enemy.DEFENSIVEPOINT56PUSHCONTESTDEFENSE:
      return "DEFENSIVEPOINT56PUSHCONTESTDEFENSE";
    case Enemy.DENDROHYPOSTASIS:
      return "DENDROHYPOSTASIS";
    case Enemy.DENDROSAMACHURL:
      return "DENDROSAMACHURL";
    case Enemy.DENDROSLIME:
      return "DENDROSLIME";
    case Enemy.DENDROSPECTER:
      return "DENDROSPECTER";
    case Enemy.ELECTROABYSSMAGE:
      return "ELECTROABYSSMAGE";
    case Enemy.ELECTROCICIN:
      return "ELECTROCICIN";
    case Enemy.ELECTROHILICHURLGRENADIER:
      return "ELECTROHILICHURLGRENADIER";
    case Enemy.ELECTROHILICHURLSHOOTER:
      return "ELECTROHILICHURLSHOOTER";
    case Enemy.ELECTROHYPOSTASIS:
      return "ELECTROHYPOSTASIS";
    case Enemy.ELECTROREGISVINE:
      return "ELECTROREGISVINE";
    case Enemy.ELECTROSAMACHURL:
      return "ELECTROSAMACHURL";
    case Enemy.ELECTROSLIME:
      return "ELECTROSLIME";
    case Enemy.ELECTROSPECTER:
      return "ELECTROSPECTER";
    case Enemy.ELECTROWHOPPERFLOWER:
      return "ELECTROWHOPPERFLOWER";
    case Enemy.EMPEROROFFIREANDIRON:
      return "EMPEROROFFIREANDIRON";
    case Enemy.EREMITEAXEVANGUARD:
      return "EREMITEAXEVANGUARD";
    case Enemy.EREMITECROSSBOW:
      return "EREMITECROSSBOW";
    case Enemy.EREMITEDAYTHUNDER:
      return "EREMITEDAYTHUNDER";
    case Enemy.EREMITEDESERTCLEARWATER:
      return "EREMITEDESERTCLEARWATER";
    case Enemy.EREMITEFLORALRINGDANCER:
      return "EREMITEFLORALRINGDANCER";
    case Enemy.EREMITEGALEHUNTER:
      return "EREMITEGALEHUNTER";
    case Enemy.EREMITELINEBREAKER:
      return "EREMITELINEBREAKER";
    case Enemy.EREMITERAVENBEAKHALBERDIER:
      return "EREMITERAVENBEAKHALBERDIER";
    case Enemy.EREMITESCORCHINGLOREMASTER:
      return "EREMITESCORCHINGLOREMASTER";
    case Enemy.EREMITESTONEENCHANTER:
      return "EREMITESTONEENCHANTER";
    case Enemy.EREMITESUNFROST:
      return "EREMITESUNFROST";
    case Enemy.EREMITESWORDDANCER:
      return "EREMITESWORDDANCER";
    case Enemy.ERODINGAVATAROFLAVA:
      return "ERODINGAVATAROFLAVA";
    case Enemy.EXPERIMENTALFIELDGENERATOR:
      return "EXPERIMENTALFIELDGENERATOR";
    case Enemy.EYEOFTHESTORM:
      return "EYEOFTHESTORM";
    case Enemy.FATUICRYOCICINMAGE:
      return "FATUICRYOCICINMAGE";
    case Enemy.FATUIELECTROCICINMAGE:
      return "FATUIELECTROCICINMAGE";
    case Enemy.FATUIPYROAGENT:
      return "FATUIPYROAGENT";
    case Enemy.FATUISKIRMISHERANEMOBOXERVANGUARD:
      return "FATUISKIRMISHERANEMOBOXERVANGUARD";
    case Enemy.FATUISKIRMISHERCRYOGUNNERLEGIONNAIRE:
      return "FATUISKIRMISHERCRYOGUNNERLEGIONNAIRE";
    case Enemy.FATUISKIRMISHERELECTROHAMMERVANGUARD:
      return "FATUISKIRMISHERELECTROHAMMERVANGUARD";
    case Enemy.FATUISKIRMISHERGEOCHANTERBRACER:
      return "FATUISKIRMISHERGEOCHANTERBRACER";
    case Enemy.FATUISKIRMISHERHYDROGUNNERLEGIONNAIRE:
      return "FATUISKIRMISHERHYDROGUNNERLEGIONNAIRE";
    case Enemy.FATUISKIRMISHERPYROSLINGERBRACER:
      return "FATUISKIRMISHERPYROSLINGERBRACER";
    case Enemy.FEROCIOUSWARRIORGRAPPLER:
      return "FEROCIOUSWARRIORGRAPPLER";
    case Enemy.FEROCIOUSWARRIORHUMANRAM:
      return "FEROCIOUSWARRIORHUMANRAM";
    case Enemy.FEROCIOUSWARRIORWRESTLER:
      return "FEROCIOUSWARRIORWRESTLER";
    case Enemy.FLOATINGANEMOFUNGUS:
      return "FLOATINGANEMOFUNGUS";
    case Enemy.FLOATINGDENDROFUNGUS:
      return "FLOATINGDENDROFUNGUS";
    case Enemy.FLOATINGHYDROFUNGUS:
      return "FLOATINGHYDROFUNGUS";
    case Enemy.FLOWINGBLADEGREASESAW:
      return "FLOWINGBLADEGREASESAW";
    case Enemy.FLOWINGBLADEHARPOONTHROWER:
      return "FLOWINGBLADEHARPOONTHROWER";
    case Enemy.FLOWINGBLADESKIRMISHER:
      return "FLOWINGBLADESKIRMISHER";
    case Enemy.FLOWINVERTEDWAYOBMANIFESTATION:
      return "FLOWINVERTEDWAYOBMANIFESTATION";
    case Enemy.FLUIDAVATAROFLAVA:
      return "FLUIDAVATAROFLAVA";
    case Enemy.FOLIARSWIFTWAYOBMANIFESTATION:
      return "FOLIARSWIFTWAYOBMANIFESTATION";
    case Enemy.FORGEDSANDINTERROGATOR:
      return "FORGEDSANDINTERROGATOR";
    case Enemy.FORGEDSANDJAVELINEER:
      return "FORGEDSANDJAVELINEER";
    case Enemy.FORGEDSANDSHIELDBREAKER:
      return "FORGEDSANDSHIELDBREAKER";
    case Enemy.FROSTARMLAWACHURL:
      return "FROSTARMLAWACHURL";
    case Enemy.FROSTOPERATIVE:
      return "FROSTOPERATIVE";
    case Enemy.FURNACESHELLMOUNTAINWEASEL:
      return "FURNACESHELLMOUNTAINWEASEL";
    case Enemy.GEOHYPOSTASIS:
      return "GEOHYPOSTASIS";
    case Enemy.GEOLOGICALSURVEYMEK:
      return "GEOLOGICALSURVEYMEK";
    case Enemy.GEOSAMACHURL:
      return "GEOSAMACHURL";
    case Enemy.GEOSLIME:
      return "GEOSLIME";
    case Enemy.GEOSPECTER:
      return "GEOSPECTER";
    case Enemy.GEOVISHAP:
      return "GEOVISHAP";
    case Enemy.GEOVISHAPHATCHLING:
      return "GEOVISHAPHATCHLING";
    case Enemy.GLUTTONOUSYUMKASAURMOUNTAINKING:
      return "GLUTTONOUSYUMKASAURMOUNTAINKING";
    case Enemy.GOLDENWOLFLORD:
      return "GOLDENWOLFLORD";
    case Enemy.GOLDFLAMEQUCUSAURTYRANT:
      return "GOLDFLAMEQUCUSAURTYRANT";
    case Enemy.GROUNDEDGEOSHROOM:
      return "GROUNDEDGEOSHROOM";
    case Enemy.GROUNDEDHYDROSHROOM:
      return "GROUNDEDHYDROSHROOM";
    case Enemy.GUARDIANOFAPEPSOASIS:
      return "GUARDIANOFAPEPSOASIS";
    case Enemy.HALFTULPA:
      return "HALFTULPA";
    case Enemy.HATJELLYFISH:
      return "HATJELLYFISH";
    case Enemy.HILICHURL:
      return "HILICHURL";
    case Enemy.HILICHURLBERSERKER:
      return "HILICHURLBERSERKER";
    case Enemy.HILICHURLFIGHTER:
      return "HILICHURLFIGHTER";
    case Enemy.HILICHURLGRENADIER:
      return "HILICHURLGRENADIER";
    case Enemy.HILICHURLSHOOTER:
      return "HILICHURLSHOOTER";
    case Enemy.HUNTERSRAY:
      return "HUNTERSRAY";
    case Enemy.HYDROABYSSMAGE:
      return "HYDROABYSSMAGE";
    case Enemy.HYDROCICIN:
      return "HYDROCICIN";
    case Enemy.HYDROHILICHURLROGUE:
      return "HYDROHILICHURLROGUE";
    case Enemy.HYDROHYPOSTASIS:
      return "HYDROHYPOSTASIS";
    case Enemy.HYDROHYPOSTASISSUMMON:
      return "HYDROHYPOSTASISSUMMON";
    case Enemy.HYDROMIMICBOAR:
      return "HYDROMIMICBOAR";
    case Enemy.HYDROMIMICCRAB:
      return "HYDROMIMICCRAB";
    case Enemy.HYDROMIMICCRANE:
      return "HYDROMIMICCRANE";
    case Enemy.HYDROMIMICFINCH:
      return "HYDROMIMICFINCH";
    case Enemy.HYDROMIMICFROG:
      return "HYDROMIMICFROG";
    case Enemy.HYDROMIMICMALLARD:
      return "HYDROMIMICMALLARD";
    case Enemy.HYDROMIMICRAPTOR:
      return "HYDROMIMICRAPTOR";
    case Enemy.HYDROMIMICSQUIRREL:
      return "HYDROMIMICSQUIRREL";
    case Enemy.HYDROSAMACHURL:
      return "HYDROSAMACHURL";
    case Enemy.HYDROSLIME:
      return "HYDROSLIME";
    case Enemy.HYDROSPECTER:
      return "HYDROSPECTER";
    case Enemy.HYDROTULPA:
      return "HYDROTULPA";
    case Enemy.ICESHIELDHILICHURLGUARD:
      return "ICESHIELDHILICHURLGUARD";
    case Enemy.ICESHIELDWALLMITACHURL:
      return "ICESHIELDWALLMITACHURL";
    case Enemy.ICEWINDSUITE:
      return "ICEWINDSUITE";
    case Enemy.IKTOMISAURUS:
      return "IKTOMISAURUS";
    case Enemy.IKTOMISAURUSCHICK:
      return "IKTOMISAURUSCHICK";
    case Enemy.IKTOMISAURUSWARRIORCRYOCRYSTALCANNON:
      return "IKTOMISAURUSWARRIORCRYOCRYSTALCANNON";
    case Enemy.IKTOMISAURUSWARRIORICYTIDEBEARER:
      return "IKTOMISAURUSWARRIORICYTIDEBEARER";
    case Enemy.INIQUITOUSBAPTIST:
      return "INIQUITOUSBAPTIST";
    case Enemy.JADEPLUMETERRORSHROOM:
      return "JADEPLUMETERRORSHROOM";
    case Enemy.KAIRAGIDANCINGTHUNDER:
      return "KAIRAGIDANCINGTHUNDER";
    case Enemy.KAIRAGIFIERYMIGHT:
      return "KAIRAGIFIERYMIGHT";
    case Enemy.KOHOLASAURUS:
      return "KOHOLASAURUS";
    case Enemy.KOHOLASAURUSWARRIORREEFSPLITTER:
      return "KOHOLASAURUSWARRIORREEFSPLITTER";
    case Enemy.KOHOLASAURUSWARRIORWAVESHUTTLER:
      return "KOHOLASAURUSWARRIORWAVESHUTTLER";
    case Enemy.KOHOLASAURWHELP:
      return "KOHOLASAURWHELP";
    case Enemy.LARGEANEMOSLIME:
      return "LARGEANEMOSLIME";
    case Enemy.LARGECRYOSLIME:
      return "LARGECRYOSLIME";
    case Enemy.LARGEDENDROSLIME:
      return "LARGEDENDROSLIME";
    case Enemy.LARGEELECTROSLIME:
      return "LARGEELECTROSLIME";
    case Enemy.LARGEGEOSLIME:
      return "LARGEGEOSLIME";
    case Enemy.LARGEHYDROSLIME:
      return "LARGEHYDROSLIME";
    case Enemy.LARGEOVERGROWNBREACHERPRIMUS:
      return "LARGEOVERGROWNBREACHERPRIMUS";
    case Enemy.LARGEPYROSLIME:
      return "LARGEPYROSLIME";
    case Enemy.LARGESHATTERSTONEBREACHERPRIMUS:
      return "LARGESHATTERSTONEBREACHERPRIMUS";
    case Enemy.LASIGNORA:
      return "LASIGNORA";
    case Enemy.LAVADRAGONSTATUE:
      return "LAVADRAGONSTATUE";
    case Enemy.LEGATUSGOLEM:
      return "LEGATUSGOLEM";
    case Enemy.LOCALLEGENDARMOREDCRAB:
      return "LOCALLEGENDARMOREDCRAB";
    case Enemy.LOCALLEGENDBLUBBERBEAST:
      return "LOCALLEGENDBLUBBERBEAST";
    case Enemy.LOCALLEGENDCHERUBICSEAHARE:
      return "LOCALLEGENDCHERUBICSEAHARE";
    case Enemy.LOCALLEGENDHATJELLYFISH:
      return "LOCALLEGENDHATJELLYFISH";
    case Enemy.LOCALLEGENDHUNTERSRAY:
      return "LOCALLEGENDHUNTERSRAY";
    case Enemy.LORDOFERODEDPRIMALFIRE:
      return "LORDOFERODEDPRIMALFIRE";
    case Enemy.LUPUSBOREASDOMINATOROFWOLVES:
      return "LUPUSBOREASDOMINATOROFWOLVES";
    case Enemy.MAGATSUMITAKENARUKAMINOMIKOTO:
      return "MAGATSUMITAKENARUKAMINOMIKOTO";
    case Enemy.MAGUUKENKI:
      return "MAGUUKENKI";
    case Enemy.MAGUUKENKIGALLOPINGFROST:
      return "MAGUUKENKIGALLOPINGFROST";
    case Enemy.MAGUUKENKILONEGALE:
      return "MAGUUKENKILONEGALE";
    case Enemy.MAGUUKENKIMASKOFTERROR:
      return "MAGUUKENKIMASKOFTERROR";
    case Enemy.MILLELITHSERGEANT:
      return "MILLELITHSERGEANT";
    case Enemy.MILLELITHSOLDIER:
      return "MILLELITHSOLDIER";
    case Enemy.MILLENNIALPEARLSEAHORSE:
      return "MILLENNIALPEARLSEAHORSE";
    case Enemy.MIRRORMAIDEN:
      return "MIRRORMAIDEN";
    case Enemy.MUTANTELECTROSLIME:
      return "MUTANTELECTROSLIME";
    case Enemy.NIMBLEHARVESTERMEK:
      return "NIMBLEHARVESTERMEK";
    case Enemy.NOBUSHIHITSUKEBAN:
      return "NOBUSHIHITSUKEBAN";
    case Enemy.NOBUSHIJINTOUBAN:
      return "NOBUSHIJINTOUBAN";
    case Enemy.NOBUSHIKIKOUBAN:
      return "NOBUSHIKIKOUBAN";
    case Enemy.OCEANID:
      return "OCEANID";
    case Enemy.OCHIMUSHACANKEREDFLAME:
      return "OCHIMUSHACANKEREDFLAME";
    case Enemy.OCHIMUSHAENSORCELLEDTHUNDER:
      return "OCHIMUSHAENSORCELLEDTHUNDER";
    case Enemy.OVERGROWNBREACHERPRIMUS:
      return "OVERGROWNBREACHERPRIMUS";
    case Enemy.PERPETUALMECHANICALARRAY:
      return "PERPETUALMECHANICALARRAY";
    case Enemy.PRAETORIANGOLEM:
      return "PRAETORIANGOLEM";
    case Enemy.PRIMALCONSTRUCTPROSPECTOR:
      return "PRIMALCONSTRUCTPROSPECTOR";
    case Enemy.PRIMALCONSTRUCTREPULSOR:
      return "PRIMALCONSTRUCTREPULSOR";
    case Enemy.PRIMALCONSTRUCTRESHAPER:
      return "PRIMALCONSTRUCTRESHAPER";
    case Enemy.PRIMOGEOVISHAP:
      return "PRIMOGEOVISHAP";
    case Enemy.PRIMORDIALBATHYSMALVISHAP:
      return "PRIMORDIALBATHYSMALVISHAP";
    case Enemy.PYROABYSSMAGE:
      return "PYROABYSSMAGE";
    case Enemy.PYROHILICHURLSHOOTER:
      return "PYROHILICHURLSHOOTER";
    case Enemy.PYROHYPOSTASIS:
      return "PYROHYPOSTASIS";
    case Enemy.PYROREGISVINE:
      return "PYROREGISVINE";
    case Enemy.PYROSLIME:
      return "PYROSLIME";
    case Enemy.PYROSPECTER:
      return "PYROSPECTER";
    case Enemy.PYROWHOPPERFLOWER:
      return "PYROWHOPPERFLOWER";
    case Enemy.QUCUSAURUS:
      return "QUCUSAURUS";
    case Enemy.QUCUSAURUSCHICK:
      return "QUCUSAURUSCHICK";
    case Enemy.QUCUSAURUSWARRIORBLAZINGSKY:
      return "QUCUSAURUSWARRIORBLAZINGSKY";
    case Enemy.QUCUSAURUSWARRIORHEARTSTARHAMMER:
      return "QUCUSAURUSWARRIORHEARTSTARHAMMER";
    case Enemy.RECONLOGMEK:
      return "RECONLOGMEK";
    case Enemy.RIMEBITERBATHYSMALVISHAP:
      return "RIMEBITERBATHYSMALVISHAP";
    case Enemy.ROCKCAVERNOUSWAYOBMANIFESTATION:
      return "ROCKCAVERNOUSWAYOBMANIFESTATION";
    case Enemy.ROCKFONDRIFTHOUND:
      return "ROCKFONDRIFTHOUND";
    case Enemy.ROCKFONDRIFTHOUNDWHELP:
      return "ROCKFONDRIFTHOUNDWHELP";
    case Enemy.ROCKSHIELDHILICHURLGUARD:
      return "ROCKSHIELDHILICHURLGUARD";
    case Enemy.ROCKSHIELDWALLMITACHURL:
      return "ROCKSHIELDWALLMITACHURL";
    case Enemy.RUINCRUISER:
      return "RUINCRUISER";
    case Enemy.RUINDEFENDER:
      return "RUINDEFENDER";
    case Enemy.RUINDESTROYER:
      return "RUINDESTROYER";
    case Enemy.RUINDRAKEEARTHGUARD:
      return "RUINDRAKEEARTHGUARD";
    case Enemy.RUINDRAKESKYWATCH:
      return "RUINDRAKESKYWATCH";
    case Enemy.RUINGRADER:
      return "RUINGRADER";
    case Enemy.RUINGUARD:
      return "RUINGUARD";
    case Enemy.RUINHUNTER:
      return "RUINHUNTER";
    case Enemy.RUINSCOUT:
      return "RUINSCOUT";
    case Enemy.RUINSERPENT:
      return "RUINSERPENT";
    case Enemy.RULEROFTHECHIZHANGMOUNTAINSTIANYU:
      return "RULEROFTHECHIZHANGMOUNTAINSTIANYU";
    case Enemy.RULEROFTHECHIZHANGMOUNTAINSYIJI:
      return "RULEROFTHECHIZHANGMOUNTAINSYIJI";
    case Enemy.SAMACHURLBOSS:
      return "SAMACHURLBOSS";
    case Enemy.SANGONOMIYACOHORT:
      return "SANGONOMIYACOHORT";
    case Enemy.SECRETSOURCEAUTOMATONCONFIGURATIONDEVICE:
      return "SECRETSOURCEAUTOMATONCONFIGURATIONDEVICE";
    case Enemy.SECRETSOURCEAUTOMATONHUNTERSEEKER:
      return "SECRETSOURCEAUTOMATONHUNTERSEEKER";
    case Enemy.SECRETSOURCEAUTOMATONOVERSEERDEVICE:
      return "SECRETSOURCEAUTOMATONOVERSEERDEVICE";
    case Enemy.SETEKHWENUT:
      return "SETEKHWENUT";
    case Enemy.SHADOWYHUSKDEFENDER:
      return "SHADOWYHUSKDEFENDER";
    case Enemy.SHADOWYHUSKLINEBREAKER:
      return "SHADOWYHUSKLINEBREAKER";
    case Enemy.SHADOWYHUSKSTANDARDBEARER:
      return "SHADOWYHUSKSTANDARDBEARER";
    case Enemy.SHATTERSTONEBREACHERPRIMUS:
      return "SHATTERSTONEBREACHERPRIMUS";
    case Enemy.SHOGUNATEINFANTRY:
      return "SHOGUNATEINFANTRY";
    case Enemy.SHOGUNATEINFANTRYCAPTAIN:
      return "SHOGUNATEINFANTRYCAPTAIN";
    case Enemy.SHOUKINOKAMITHEPRODIGAL:
      return "SHOUKINOKAMITHEPRODIGAL";
    case Enemy.SOLITARYSUANNI:
      return "SOLITARYSUANNI";
    case Enemy.SPIRITOFOMENDENDROSPIRITSERPENT:
      return "SPIRITOFOMENDENDROSPIRITSERPENT";
    case Enemy.SPIRITOFOMENPYROSCORPION:
      return "SPIRITOFOMENPYROSCORPION";
    case Enemy.SPIRITOFOMENSTONEDRAKE:
      return "SPIRITOFOMENSTONEDRAKE";
    case Enemy.SPIRITOFOMENWINDGLEDE:
      return "SPIRITOFOMENWINDGLEDE";
    case Enemy.SPIRITSPEAKERWARRIORCONTEMPLATOR:
      return "SPIRITSPEAKERWARRIORCONTEMPLATOR";
    case Enemy.SPIRITSPEAKERWARRIORDETERMINATOR:
      return "SPIRITSPEAKERWARRIORDETERMINATOR";
    case Enemy.SPIRITSPEAKERWARRIORPSYCHOKINETIC:
      return "SPIRITSPEAKERWARRIORPSYCHOKINETIC";
    case Enemy.STERNSHIELDCRAB:
      return "STERNSHIELDCRAB";
    case Enemy.STONEHIDELAWACHURL:
      return "STONEHIDELAWACHURL";
    case Enemy.STORMTERROR:
      return "STORMTERROR";
    case Enemy.STRETCHYANEMOFUNGUS:
      return "STRETCHYANEMOFUNGUS";
    case Enemy.STRETCHYELECTROFUNGUS:
      return "STRETCHYELECTROFUNGUS";
    case Enemy.STRETCHYGEOFUNGUS:
      return "STRETCHYGEOFUNGUS";
    case Enemy.STRETCHYPYROFUNGUS:
      return "STRETCHYPYROFUNGUS";
    case Enemy.SUBLIMATEDQUEEN:
      return "SUBLIMATEDQUEEN";
    case Enemy.SUPPRESSIONSPECIALISTMEK:
      return "SUPPRESSIONSPECIALISTMEK";
    case Enemy.SWIFTSTEPARMEDCOURIER:
      return "SWIFTSTEPARMEDCOURIER";
    case Enemy.SWIFTSTEPSEEKER:
      return "SWIFTSTEPSEEKER";
    case Enemy.SWIFTSTEPSTORMSCOUT:
      return "SWIFTSTEPSTORMSCOUT";
    case Enemy.TAINTEDWATERSPLITTINGPHANTASM:
      return "TAINTEDWATERSPLITTINGPHANTASM";
    case Enemy.TAINTEDWATERSPOUTINGPHANTASM:
      return "TAINTEDWATERSPOUTINGPHANTASM";
    case Enemy.TATANKASAURUS:
      return "TATANKASAURUS";
    case Enemy.TATANKASAURUSWARRIORSKYBREAKER:
      return "TATANKASAURUSWARRIORSKYBREAKER";
    case Enemy.TATANKASAURUSWARRIORSPIRITLIGHTCHASER:
      return "TATANKASAURUSWARRIORSPIRITLIGHTCHASER";
    case Enemy.TATANKASAURWHELP:
      return "TATANKASAURWHELP";
    case Enemy.TENEBROUSMIMIFLORA:
      return "TENEBROUSMIMIFLORA";
    case Enemy.TENEBROUSPAPILLATYPEI:
      return "TENEBROUSPAPILLATYPEI";
    case Enemy.TEPETLISAURUS:
      return "TEPETLISAURUS";
    case Enemy.TEPETLISAURUSTRIBECHIEF:
      return "TEPETLISAURUSTRIBECHIEF";
    case Enemy.TEPETLISAURUSWARRIORROCKBREAKERBLADE:
      return "TEPETLISAURUSWARRIORROCKBREAKERBLADE";
    case Enemy.TEPETLISAURUSWARRIORSHARDSTRIKER:
      return "TEPETLISAURUSWARRIORSHARDSTRIKER";
    case Enemy.TEPETLISAURWHELP:
      return "TEPETLISAURWHELP";
    case Enemy.THEGAMEBEFORETHEGATE:
      return "THEGAMEBEFORETHEGATE";
    case Enemy.THEKNAVE:
      return "THEKNAVE";
    case Enemy.THUNDERCRAVENRIFTHOUND:
      return "THUNDERCRAVENRIFTHOUND";
    case Enemy.THUNDERCRAVENRIFTHOUNDWHELP:
      return "THUNDERCRAVENRIFTHOUNDWHELP";
    case Enemy.THUNDERHELMLAWACHURL:
      return "THUNDERHELMLAWACHURL";
    case Enemy.THUNDERINGWAYOBMANIFESTATION:
      return "THUNDERINGWAYOBMANIFESTATION";
    case Enemy.THUNDERMANIFESTATION:
      return "THUNDERMANIFESTATION";
    case Enemy.TREASUREHOARDERSBOSS:
      return "TREASUREHOARDERSBOSS";
    case Enemy.TREASUREHOARDERSCARMEN:
      return "TREASUREHOARDERSCARMEN";
    case Enemy.TREASUREHOARDERSCRUSHER:
      return "TREASUREHOARDERSCRUSHER";
    case Enemy.TREASUREHOARDERSCRYOPOTIONEER:
      return "TREASUREHOARDERSCRYOPOTIONEER";
    case Enemy.TREASUREHOARDERSELECTROPOTIONEER:
      return "TREASUREHOARDERSELECTROPOTIONEER";
    case Enemy.TREASUREHOARDERSGRAVEDIGGER:
      return "TREASUREHOARDERSGRAVEDIGGER";
    case Enemy.TREASUREHOARDERSHANDYMAN:
      return "TREASUREHOARDERSHANDYMAN";
    case Enemy.TREASUREHOARDERSHYDROPOTIONEER:
      return "TREASUREHOARDERSHYDROPOTIONEER";
    case Enemy.TREASUREHOARDERSLIULIU:
      return "TREASUREHOARDERSLIULIU";
    case Enemy.TREASUREHOARDERSMARKSMAN:
      return "TREASUREHOARDERSMARKSMAN";
    case Enemy.TREASUREHOARDERSPUGILIST:
      return "TREASUREHOARDERSPUGILIST";
    case Enemy.TREASUREHOARDERSPYROPOTIONEER:
      return "TREASUREHOARDERSPYROPOTIONEER";
    case Enemy.TREASUREHOARDERSRAPTOR:
      return "TREASUREHOARDERSRAPTOR";
    case Enemy.TREASUREHOARDERSSCOUT:
      return "TREASUREHOARDERSSCOUT";
    case Enemy.TREASUREHOARDERSSEAMAN:
      return "TREASUREHOARDERSSEAMAN";
    case Enemy.TREASUREHOARDERSWALLENSTEIN:
      return "TREASUREHOARDERSWALLENSTEIN";
    case Enemy.UNDERWATERPATROLMEK:
      return "UNDERWATERPATROLMEK";
    case Enemy.UNDERWATERSURVEYMEK:
      return "UNDERWATERSURVEYMEK";
    case Enemy.UNUSUALHILICHURL:
      return "UNUSUALHILICHURL";
    case Enemy.VETERANARITHMETICENHANCERMEK:
      return "VETERANARITHMETICENHANCERMEK";
    case Enemy.VETERANFATUIPYROAGENT:
      return "VETERANFATUIPYROAGENT";
    case Enemy.VETERANFATUISKIRMISHERCRYOGUNNERLEGIONNAIRE:
      return "VETERANFATUISKIRMISHERCRYOGUNNERLEGIONNAIRE";
    case Enemy.VETERANFATUISKIRMISHERELECTROHAMMERVANGUARD:
      return "VETERANFATUISKIRMISHERELECTROHAMMERVANGUARD";
    case Enemy.VETERANFATUISKIRMISHERPYROSLINGERBRACER:
      return "VETERANFATUISKIRMISHERPYROSLINGERBRACER";
    case Enemy.VETERANFROSTOPERATIVE:
      return "VETERANFROSTOPERATIVE";
    case Enemy.VETERANTAINTEDWATERSPLITTINGPHANTASM:
      return "VETERANTAINTEDWATERSPLITTINGPHANTASM";
    case Enemy.VETERANTAINTEDWATERSPOUTINGPHANTASM:
      return "VETERANTAINTEDWATERSPOUTINGPHANTASM";
    case Enemy.VETERANWINDOPERATIVE:
      return "VETERANWINDOPERATIVE";
    case Enemy.WAYWARDHERMETICSPIRITSPEAKER:
      return "WAYWARDHERMETICSPIRITSPEAKER";
    case Enemy.WHIRLINGCRYOFUNGUS:
      return "WHIRLINGCRYOFUNGUS";
    case Enemy.WHIRLINGELECTROFUNGUS:
      return "WHIRLINGELECTROFUNGUS";
    case Enemy.WHIRLINGPYROFUNGUS:
      return "WHIRLINGPYROFUNGUS";
    case Enemy.WINDOPERATIVE:
      return "WINDOPERATIVE";
    case Enemy.WINGEDCRYOSHROOM:
      return "WINGEDCRYOSHROOM";
    case Enemy.WINGEDDENDROSHROOM:
      return "WINGEDDENDROSHROOM";
    case Enemy.WINGEDWARRIORFEATHERSHEDDER:
      return "WINGEDWARRIORFEATHERSHEDDER";
    case Enemy.WINGEDWARRIORSKYMASTER:
      return "WINGEDWARRIORSKYMASTER";
    case Enemy.WINGEDWARRIORSKYSOARER:
      return "WINGEDWARRIORSKYSOARER";
    case Enemy.WOODENSHIELDHILICHURLGUARD:
      return "WOODENSHIELDHILICHURLGUARD";
    case Enemy.WOODENSHIELDWALLMITACHURL:
      return "WOODENSHIELDWALLMITACHURL";
    case Enemy.XUANWENBEAST:
      return "XUANWENBEAST";
    case Enemy.YORIKISAMURAI:
      return "YORIKISAMURAI";
    case Enemy.YUMKASAURUS:
      return "YUMKASAURUS";
    case Enemy.YUMKASAURUSWARRIORFLOWINGSKYFIRE:
      return "YUMKASAURUSWARRIORFLOWINGSKYFIRE";
    case Enemy.YUMKASAURUSWARRIORWHIRLINGLEAVES:
      return "YUMKASAURUSWARRIORWHIRLINGLEAVES";
    case Enemy.YUMKASAURWHELP:
      return "YUMKASAURWHELP";
    case Enemy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
