/** @type {import('tailwindcss').Config} */
const defaultTailwindTheme = require("tailwindcss/defaultTheme");
const characterThemes = require('./src/data/genshin_character_themes.json');

module.exports = {
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
  theme: {
    fontFamily: {
      sans: ["GS", ...defaultTailwindTheme.fontFamily.sans],
    },
    extend: {
      aspectRatio: {
        "2/3": "2 / 3",
        "5/8": "5 / 8",
      },
    },
  },
  plugins: ["daisyui", "@tailwindcss/typography"],
  daisyui: {
    themes: [
      {
        genshin: {
          primary: "#424f65",
          "primary-content": "#ece5d8",
          secondary: "#93806a",
          accent: "#f7ba3f",
          "accent-content": "#1c1c22",
          neutral: "#424f65",
          "neutral-content": "#ece5d8",
          "base-100": "#ece5d8",
          "base-200": "rgba(242, 242, 242, 0)",
          "base-300": "#d4d4d4",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
      },
      {
        genshin_dark: {
          primary: "#d3bc8e",
          "primary-content": "#424f65",
          secondary: "#93806a",
          accent: "#f7ba3f",
          "accent-content": "#1c1c22",
          neutral: "#424f65",
          "neutral-content": "#ece5d8",
          "base-100": "#1c1c22",
          "base-200": "#16161a",
          "base-300": "#0f0f12",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
      },
      ...characterThemes,
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
};
