syntax = "proto3";

package io.leishi.genshin.proto;

enum Enemy {
    ENEMY_UNSPECIFIED = 0;
    ABYSSHERALDFROSTFALL = 1;
    ABYSSHERALDWICKEDTORRENTS = 2;
    ABYSSLECTORFATHOMLESSFLAMES = 3;
    ABYSSLECTORVIOLETLIGHTNING = 4;
    ADVANCEDDEFENSIVEANEMOTOWER = 5;
    ADVANCEDDEFENSIVECRYOTOWER = 6;
    ADVANCEDDEFENSIVEELECTROTOWER = 7;
    ADVANCEDDEFENSIVEHYDROTOWER = 8;
    ADVANCEDDEFENSIVEPYROTOWER = 9;
    AEONBLIGHTDRAKE = 10;
    ALGORITHMOFSEMIINTRANSIENTMATRIXOFOVERSEERNETWORK = 11;
    ALLDEVOURINGNARWHAL = 12;
    ANEMOHILICHURLROGUE = 13;
    ANEMOHYPOSTASIS = 14;
    ANEMOSAMACHURL = 15;
    ANEMOSLIME = 16;
    ANEMOSPECTER = 17;
    ANGELICSEAHARE = 18;
    ANNIHILATIONSPECIALISTMEK = 19;
    AREAALERTMEK = 20;
    ARITHMETICENHANCERMEK = 21;
    ARMOREDCRAB = 22;
    ASCENDEDKING = 23;
    ASSAULTSPECIALISTMEK = 24;
    AUTOMATONFUNGUSBALLOON = 25;
    AUTOMATONLARGESLIMEBALLOON = 26;
    AUTOMATONSMALLSLIMEBALLOON = 27;
    AZHDAHA = 28;
    BALLOCTOPUS = 29;
    BASICDEFENSIVEANEMOTOWER = 30;
    BASICDEFENSIVECRYOTOWER = 31;
    BASICDEFENSIVEELECTROTOWER = 32;
    BASICDEFENSIVEHYDROTOWER = 33;
    BASICDEFENSIVEPYROTOWER = 34;
    BATTLEHARDENEDBITINGCOLDWAYOBMANIFESTATION = 35;
    BATTLEHARDENEDBURNINGAFLAMEWAYOBMANIFESTATION = 36;
    BATTLEHARDENEDFLOWINVERTEDWAYOBMANIFESTATION = 37;
    BATTLEHARDENEDFOLIARSWIFTWAYOBMANIFESTATION = 38;
    BATTLEHARDENEDIKTOMISAURUS = 39;
    BATTLEHARDENEDPRIMORDIALBATHYSMALVISHAP = 40;
    BATTLEHARDENEDROCKCAVERNOUSWAYOBMANIFESTATION = 41;
    BATTLEHARDENEDRUINDRAKEEARTHGUARD = 42;
    BATTLEHARDENEDTATANKASAURUS = 43;
    BATTLEHARDENEDTHUNDERINGWAYOBMANIFESTATION = 44;
    BEISHT = 45;
    BITINGCOLDWAYOBMANIFESTATION = 46;
    BLACKSERPENTKNIGHTROCKBREAKERAX = 47;
    BLACKSERPENTKNIGHTWINDCUTTER = 48;
    BLAZINGAXEMITACHURL = 49;
    BLUBBERBEAST = 50;
    BOLTEATERBATHYSMALVISHAP = 51;
    BUBBLERSEAHORSE = 52;
    BUBBLYSEAHORSE = 53;
    BURNINGAFLAMEWAYOBMANIFESTATION = 54;
    CHERUBICSEAHARE = 55;
    CHILDE = 56;
    CONSECRATEDFANGEDBEAST = 57;
    CONSECRATEDFLYINGSERPENT = 58;
    CONSECRATEDHORNEDCROCODILE = 59;
    CONSECRATEDREDVULTURE = 60;
    CONSECRATEDSCORPION = 61;
    CONSTRUCTIONSPECIALISTMEK = 62;
    CRACKLINGAXEMITACHURL = 63;
    CRYOABYSSMAGE = 64;
    CRYOCICIN = 65;
    CRYOHILICHURLGRENADIER = 66;
    CRYOHILICHURLSHOOTER = 67;
    CRYOHYPOSTASIS = 68;
    CRYOREGISVINE = 69;
    CRYOSAMACHURL = 70;
    CRYOSLIME = 71;
    CRYOSPECTER = 72;
    CRYOWHOPPERFLOWER = 73;
    DEEPWATERASSAULTMEK = 74;
    DEFENSIVEPHYSICALTOWER = 75;
    DEFENSIVEPOINT56PUSHCONTESTDEFENSE = 76;
    DENDROHYPOSTASIS = 77;
    DENDROSAMACHURL = 78;
    DENDROSLIME = 79;
    DENDROSPECTER = 80;
    ELECTROABYSSMAGE = 81;
    ELECTROCICIN = 82;
    ELECTROHILICHURLGRENADIER = 83;
    ELECTROHILICHURLSHOOTER = 84;
    ELECTROHYPOSTASIS = 85;
    ELECTROREGISVINE = 86;
    ELECTROSAMACHURL = 87;
    ELECTROSLIME = 88;
    ELECTROSPECTER = 89;
    ELECTROWHOPPERFLOWER = 90;
    EMPEROROFFIREANDIRON = 91;
    EREMITEAXEVANGUARD = 92;
    EREMITECROSSBOW = 93;
    EREMITEDAYTHUNDER = 94;
    EREMITEDESERTCLEARWATER = 95;
    EREMITEFLORALRINGDANCER = 96;
    EREMITEGALEHUNTER = 97;
    EREMITELINEBREAKER = 98;
    EREMITERAVENBEAKHALBERDIER = 99;
    EREMITESCORCHINGLOREMASTER = 100;
    EREMITESTONEENCHANTER = 101;
    EREMITESUNFROST = 102;
    EREMITESWORDDANCER = 103;
    ERODINGAVATAROFLAVA = 104;
    EXPERIMENTALFIELDGENERATOR = 105;
    EYEOFTHESTORM = 106;
    FATUICRYOCICINMAGE = 107;
    FATUIELECTROCICINMAGE = 108;
    FATUIPYROAGENT = 109;
    FATUISKIRMISHERANEMOBOXERVANGUARD = 110;
    FATUISKIRMISHERCRYOGUNNERLEGIONNAIRE = 111;
    FATUISKIRMISHERELECTROHAMMERVANGUARD = 112;
    FATUISKIRMISHERGEOCHANTERBRACER = 113;
    FATUISKIRMISHERHYDROGUNNERLEGIONNAIRE = 114;
    FATUISKIRMISHERPYROSLINGERBRACER = 115;
    FEROCIOUSWARRIORGRAPPLER = 116;
    FEROCIOUSWARRIORHUMANRAM = 117;
    FEROCIOUSWARRIORWRESTLER = 118;
    FLOATINGANEMOFUNGUS = 119;
    FLOATINGDENDROFUNGUS = 120;
    FLOATINGHYDROFUNGUS = 121;
    FLOWINGBLADEGREASESAW = 122;
    FLOWINGBLADEHARPOONTHROWER = 123;
    FLOWINGBLADESKIRMISHER = 124;
    FLOWINVERTEDWAYOBMANIFESTATION = 125;
    FLUIDAVATAROFLAVA = 126;
    FOLIARSWIFTWAYOBMANIFESTATION = 127;
    FORGEDSANDINTERROGATOR = 128;
    FORGEDSANDJAVELINEER = 129;
    FORGEDSANDSHIELDBREAKER = 130;
    FROSTARMLAWACHURL = 131;
    FROSTOPERATIVE = 132;
    FURNACESHELLMOUNTAINWEASEL = 133;
    GEOHYPOSTASIS = 134;
    GEOLOGICALSURVEYMEK = 135;
    GEOSAMACHURL = 136;
    GEOSLIME = 137;
    GEOSPECTER = 138;
    GEOVISHAP = 139;
    GEOVISHAPHATCHLING = 140;
    GLUTTONOUSYUMKASAURMOUNTAINKING = 141;
    GOLDENWOLFLORD = 142;
    GOLDFLAMEQUCUSAURTYRANT = 143;
    GROUNDEDGEOSHROOM = 144;
    GROUNDEDHYDROSHROOM = 145;
    GUARDIANOFAPEPSOASIS = 146;
    HALFTULPA = 147;
    HATJELLYFISH = 148;
    HILICHURL = 149;
    HILICHURLBERSERKER = 150;
    HILICHURLFIGHTER = 151;
    HILICHURLGRENADIER = 152;
    HILICHURLSHOOTER = 153;
    HUNTERSRAY = 154;
    HYDROABYSSMAGE = 155;
    HYDROCICIN = 156;
    HYDROHILICHURLROGUE = 157;
    HYDROHYPOSTASIS = 158;
    HYDROHYPOSTASISSUMMON = 159;
    HYDROMIMICBOAR = 160;
    HYDROMIMICCRAB = 161;
    HYDROMIMICCRANE = 162;
    HYDROMIMICFINCH = 163;
    HYDROMIMICFROG = 164;
    HYDROMIMICMALLARD = 165;
    HYDROMIMICRAPTOR = 166;
    HYDROMIMICSQUIRREL = 167;
    HYDROSAMACHURL = 168;
    HYDROSLIME = 169;
    HYDROSPECTER = 170;
    HYDROTULPA = 171;
    ICESHIELDHILICHURLGUARD = 172;
    ICESHIELDWALLMITACHURL = 173;
    ICEWINDSUITE = 174;
    IKTOMISAURUS = 175;
    IKTOMISAURUSCHICK = 176;
    IKTOMISAURUSWARRIORCRYOCRYSTALCANNON = 177;
    IKTOMISAURUSWARRIORICYTIDEBEARER = 178;
    INIQUITOUSBAPTIST = 179;
    JADEPLUMETERRORSHROOM = 180;
    KAIRAGIDANCINGTHUNDER = 181;
    KAIRAGIFIERYMIGHT = 182;
    KOHOLASAURUS = 183;
    KOHOLASAURUSWARRIORREEFSPLITTER = 184;
    KOHOLASAURUSWARRIORWAVESHUTTLER = 185;
    KOHOLASAURWHELP = 186;
    LARGEANEMOSLIME = 187;
    LARGECRYOSLIME = 188;
    LARGEDENDROSLIME = 189;
    LARGEELECTROSLIME = 190;
    LARGEGEOSLIME = 191;
    LARGEHYDROSLIME = 192;
    LARGEOVERGROWNBREACHERPRIMUS = 193;
    LARGEPYROSLIME = 194;
    LARGESHATTERSTONEBREACHERPRIMUS = 195;
    LASIGNORA = 196;
    LAVADRAGONSTATUE = 197;
    LEGATUSGOLEM = 198;
    LOCALLEGENDARMOREDCRAB = 199;
    LOCALLEGENDBLUBBERBEAST = 200;
    LOCALLEGENDCHERUBICSEAHARE = 201;
    LOCALLEGENDHATJELLYFISH = 202;
    LOCALLEGENDHUNTERSRAY = 203;
    LORDOFERODEDPRIMALFIRE = 204;
    LUPUSBOREASDOMINATOROFWOLVES = 205;
    MAGATSUMITAKENARUKAMINOMIKOTO = 206;
    MAGUUKENKI = 207;
    MAGUUKENKIGALLOPINGFROST = 208;
    MAGUUKENKILONEGALE = 209;
    MAGUUKENKIMASKOFTERROR = 210;
    MILLELITHSERGEANT = 211;
    MILLELITHSOLDIER = 212;
    MILLENNIALPEARLSEAHORSE = 213;
    MIRRORMAIDEN = 214;
    MUTANTELECTROSLIME = 215;
    NIMBLEHARVESTERMEK = 216;
    NOBUSHIHITSUKEBAN = 217;
    NOBUSHIJINTOUBAN = 218;
    NOBUSHIKIKOUBAN = 219;
    OCEANID = 220;
    OCHIMUSHACANKEREDFLAME = 221;
    OCHIMUSHAENSORCELLEDTHUNDER = 222;
    OVERGROWNBREACHERPRIMUS = 223;
    PERPETUALMECHANICALARRAY = 224;
    PRAETORIANGOLEM = 225;
    PRIMALCONSTRUCTPROSPECTOR = 226;
    PRIMALCONSTRUCTREPULSOR = 227;
    PRIMALCONSTRUCTRESHAPER = 228;
    PRIMOGEOVISHAP = 229;
    PRIMORDIALBATHYSMALVISHAP = 230;
    PYROABYSSMAGE = 231;
    PYROHILICHURLSHOOTER = 232;
    PYROHYPOSTASIS = 233;
    PYROREGISVINE = 234;
    PYROSLIME = 235;
    PYROSPECTER = 236;
    PYROWHOPPERFLOWER = 237;
    QUCUSAURUS = 238;
    QUCUSAURUSCHICK = 239;
    QUCUSAURUSWARRIORBLAZINGSKY = 240;
    QUCUSAURUSWARRIORHEARTSTARHAMMER = 241;
    RECONLOGMEK = 242;
    RIMEBITERBATHYSMALVISHAP = 243;
    ROCKCAVERNOUSWAYOBMANIFESTATION = 244;
    ROCKFONDRIFTHOUND = 245;
    ROCKFONDRIFTHOUNDWHELP = 246;
    ROCKSHIELDHILICHURLGUARD = 247;
    ROCKSHIELDWALLMITACHURL = 248;
    RUINCRUISER = 249;
    RUINDEFENDER = 250;
    RUINDESTROYER = 251;
    RUINDRAKEEARTHGUARD = 252;
    RUINDRAKESKYWATCH = 253;
    RUINGRADER = 254;
    RUINGUARD = 255;
    RUINHUNTER = 256;
    RUINSCOUT = 257;
    RUINSERPENT = 258;
    RULEROFTHECHIZHANGMOUNTAINSTIANYU = 259;
    RULEROFTHECHIZHANGMOUNTAINSYIJI = 260;
    SAMACHURLBOSS = 261;
    SANGONOMIYACOHORT = 262;
    SECRETSOURCEAUTOMATONCONFIGURATIONDEVICE = 263;
    SECRETSOURCEAUTOMATONHUNTERSEEKER = 264;
    SECRETSOURCEAUTOMATONOVERSEERDEVICE = 265;
    SETEKHWENUT = 266;
    SHADOWYHUSKDEFENDER = 267;
    SHADOWYHUSKLINEBREAKER = 268;
    SHADOWYHUSKSTANDARDBEARER = 269;
    SHATTERSTONEBREACHERPRIMUS = 270;
    SHOGUNATEINFANTRY = 271;
    SHOGUNATEINFANTRYCAPTAIN = 272;
    SHOUKINOKAMITHEPRODIGAL = 273;
    SOLITARYSUANNI = 274;
    SPIRITOFOMENDENDROSPIRITSERPENT = 275;
    SPIRITOFOMENPYROSCORPION = 276;
    SPIRITOFOMENSTONEDRAKE = 277;
    SPIRITOFOMENWINDGLEDE = 278;
    SPIRITSPEAKERWARRIORCONTEMPLATOR = 279;
    SPIRITSPEAKERWARRIORDETERMINATOR = 280;
    SPIRITSPEAKERWARRIORPSYCHOKINETIC = 281;
    STERNSHIELDCRAB = 282;
    STONEHIDELAWACHURL = 283;
    STORMTERROR = 284;
    STRETCHYANEMOFUNGUS = 285;
    STRETCHYELECTROFUNGUS = 286;
    STRETCHYGEOFUNGUS = 287;
    STRETCHYPYROFUNGUS = 288;
    SUBLIMATEDQUEEN = 289;
    SUPPRESSIONSPECIALISTMEK = 290;
    SWIFTSTEPARMEDCOURIER = 291;
    SWIFTSTEPSEEKER = 292;
    SWIFTSTEPSTORMSCOUT = 293;
    TAINTEDWATERSPLITTINGPHANTASM = 294;
    TAINTEDWATERSPOUTINGPHANTASM = 295;
    TATANKASAURUS = 296;
    TATANKASAURUSWARRIORSKYBREAKER = 297;
    TATANKASAURUSWARRIORSPIRITLIGHTCHASER = 298;
    TATANKASAURWHELP = 299;
    TENEBROUSMIMIFLORA = 300;
    TENEBROUSPAPILLATYPEI = 301;
    TEPETLISAURUS = 302;
    TEPETLISAURUSTRIBECHIEF = 303;
    TEPETLISAURUSWARRIORROCKBREAKERBLADE = 304;
    TEPETLISAURUSWARRIORSHARDSTRIKER = 305;
    TEPETLISAURWHELP = 306;
    THEGAMEBEFORETHEGATE = 307;
    THEKNAVE = 308;
    THUNDERCRAVENRIFTHOUND = 309;
    THUNDERCRAVENRIFTHOUNDWHELP = 310;
    THUNDERHELMLAWACHURL = 311;
    THUNDERINGWAYOBMANIFESTATION = 312;
    THUNDERMANIFESTATION = 313;
    TREASUREHOARDERSBOSS = 314;
    TREASUREHOARDERSCARMEN = 315;
    TREASUREHOARDERSCRUSHER = 316;
    TREASUREHOARDERSCRYOPOTIONEER = 317;
    TREASUREHOARDERSELECTROPOTIONEER = 318;
    TREASUREHOARDERSGRAVEDIGGER = 319;
    TREASUREHOARDERSHANDYMAN = 320;
    TREASUREHOARDERSHYDROPOTIONEER = 321;
    TREASUREHOARDERSLIULIU = 322;
    TREASUREHOARDERSMARKSMAN = 323;
    TREASUREHOARDERSPUGILIST = 324;
    TREASUREHOARDERSPYROPOTIONEER = 325;
    TREASUREHOARDERSRAPTOR = 326;
    TREASUREHOARDERSSCOUT = 327;
    TREASUREHOARDERSSEAMAN = 328;
    TREASUREHOARDERSWALLENSTEIN = 329;
    UNDERWATERPATROLMEK = 330;
    UNDERWATERSURVEYMEK = 331;
    UNUSUALHILICHURL = 332;
    VETERANARITHMETICENHANCERMEK = 333;
    VETERANFATUIPYROAGENT = 334;
    VETERANFATUISKIRMISHERCRYOGUNNERLEGIONNAIRE = 335;
    VETERANFATUISKIRMISHERELECTROHAMMERVANGUARD = 336;
    VETERANFATUISKIRMISHERPYROSLINGERBRACER = 337;
    VETERANFROSTOPERATIVE = 338;
    VETERANTAINTEDWATERSPLITTINGPHANTASM = 339;
    VETERANTAINTEDWATERSPOUTINGPHANTASM = 340;
    VETERANWINDOPERATIVE = 341;
    WAYWARDHERMETICSPIRITSPEAKER = 342;
    WHIRLINGCRYOFUNGUS = 343;
    WHIRLINGELECTROFUNGUS = 344;
    WHIRLINGPYROFUNGUS = 345;
    WINDOPERATIVE = 346;
    WINGEDCRYOSHROOM = 347;
    WINGEDDENDROSHROOM = 348;
    WINGEDWARRIORFEATHERSHEDDER = 349;
    WINGEDWARRIORSKYMASTER = 350;
    WINGEDWARRIORSKYSOARER = 351;
    WOODENSHIELDHILICHURLGUARD = 352;
    WOODENSHIELDWALLMITACHURL = 353;
    XUANWENBEAST = 354;
    YORIKISAMURAI = 355;
    YUMKASAURUS = 356;
    YUMKASAURUSWARRIORFLOWINGSKYFIRE = 357;
    YUMKASAURUSWARRIORWHIRLINGLEAVES = 358;
    YUMKASAURWHELP = 359;
}
