syntax = "proto3";

package io.leishi.genshin.proto;

enum Enemy {
    ENEMY_UNSPECIFIED = 0;
    ABYSSHERALDFROSTFALL = 1;
    ABYSSHERALDWICKEDTORRENTS = 2;
    ABYSSLECTORFATHOMLESSFLAMES = 3;
    ABYSSLECTORVIOLETLIGHTNING = 4;
    ADVANCEDDEFENSIVEANEMOTOWER = 5;
    ADVANCEDDEFENSIVECRYOTOWER = 6;
    ADVANCEDDEFENSIVEELECTROTOWER = 7;
    ADVANCEDDEFENSIVEHYDROTOWER = 8;
    ADVANCEDDEFENSIVEPYROTOWER = 9;
    AEONBLIGHTDRAKE = 10;
    ALGORITHMOFSEMIINTRANSIENTMATRIXOFOVERSEERNETWORK = 11;
    ALLDEVOURINGNARWHAL = 12;
    ANEMOHILICHURLROGUE = 13;
    ANEMOHYPOSTASIS = 14;
    ANEMOSAMACHURL = 15;
    ANEMOSLIME = 16;
    ANEMOSPECTER = 17;
    ANGELICSEAHARE = 18;
    ANNIHILATIONSPECIALISTMEK = 19;
    AREAALERTMEK = 20;
    ARITHMETICENHANCERMEK = 21;
    ARMOREDCRAB = 22;
    ASCENDEDKING = 23;
    ASSAULTSPECIALISTMEK = 24;
    AUTOMATONFUNGUSBALLOON = 25;
    AUTOMATONLARGESLIMEBALLOON = 26;
    AUTOMATONSMALLSLIMEBALLOON = 27;
    AZHDAHA = 28;
    BALLOCTOPUS = 29;
    BASICDEFENSIVEANEMOTOWER = 30;
    BASICDEFENSIVECRYOTOWER = 31;
    BASICDEFENSIVEELECTROTOWER = 32;
    BASICDEFENSIVEHYDROTOWER = 33;
    BASICDEFENSIVEPYROTOWER = 34;
    BATTLEHARDENEDBITINGCOLDWAYOBMANIFESTATION = 35;
    BATTLEHARDENEDBURNINGAFLAMEWAYOBMANIFESTATION = 36;
    BATTLEHARDENEDELITETREASUREHOARDER = 37;
    BATTLEHARDENEDFIREBLADESHOCKTROOPER = 38;
    BATTLEHARDENEDFLOWINVERTEDWAYOBMANIFESTATION = 39;
    BATTLEHARDENEDFOLIARSWIFTWAYOBMANIFESTATION = 40;
    BATTLEHARDENEDIKTOMISAURUS = 41;
    BATTLEHARDENEDLIGHTKEEPER = 42;
    BATTLEHARDENEDPIPILPANIDOL = 43;
    BATTLEHARDENEDPRIMORDIALBATHYSMALVISHAP = 44;
    BATTLEHARDENEDRADIANTGLACIALWOLF = 45;
    BATTLEHARDENEDROCKCAVERNOUSWAYOBMANIFESTATION = 46;
    BATTLEHARDENEDRUINDRAKEEARTHGUARD = 47;
    BATTLEHARDENEDTATANKASAURUS = 48;
    BATTLEHARDENEDTHUNDERINGWAYOBMANIFESTATION = 49;
    BATTLESCARREDROCKCRAB = 50;
    BEISHT = 51;
    BITINGCOLDWAYOBMANIFESTATION = 52;
    BLACKSERPENTKNIGHTROCKBREAKERAX = 53;
    BLACKSERPENTKNIGHTWINDCUTTER = 54;
    BLAZINGAXEMITACHURL = 55;
    BLAZINGBRILLIANCEFROSTNIGHTSCION = 56;
    BLUBBERBEAST = 57;
    BOLTEATERBATHYSMALVISHAP = 58;
    BUBBLERSEAHORSE = 59;
    BUBBLYSEAHORSE = 60;
    BURNINGAFLAMEWAYOBMANIFESTATION = 61;
    CHERUBICSEAHARE = 62;
    CHILDE = 63;
    CLOSECOMBATSCOUTLANDCRUISER = 64;
    CLOSECOMBATSTORMLANDCRUISER = 65;
    CONSECRATEDFANGEDBEAST = 66;
    CONSECRATEDFLYINGSERPENT = 67;
    CONSECRATEDHORNEDCROCODILE = 68;
    CONSECRATEDREDVULTURE = 69;
    CONSECRATEDSCORPION = 70;
    CONSTRUCTIONSPECIALISTMEK = 71;
    CRACKLINGAXEMITACHURL = 72;
    CRYOABYSSMAGE = 73;
    CRYOCICIN = 74;
    CRYOHILICHURLGRENADIER = 75;
    CRYOHILICHURLSHOOTER = 76;
    CRYOHYPOSTASIS = 77;
    CRYOREGISVINE = 78;
    CRYOSAMACHURL = 79;
    CRYOSLIME = 80;
    CRYOSPECTER = 81;
    CRYOWHOPPERFLOWER = 82;
    CUTTINGEDGEALLPURPOSESCOUTLANDCRUISER = 83;
    CUTTINGEDGEALLPURPOSESTORMLANDCRUISER = 84;
    CUTTINGEDGEFIRESUPPORTGROUNDEFFECTLANDCRUISER = 85;
    DEEPWATERASSAULTMEK = 86;
    DEFENSIVEPHYSICALTOWER = 87;
    DEFENSIVEPOINT56PUSHCONTESTDEFENSE = 88;
    DENDROHYPOSTASIS = 89;
    DENDROSAMACHURL = 90;
    DENDROSLIME = 91;
    DENDROSPECTER = 92;
    ELECTROABYSSMAGE = 93;
    ELECTROCICIN = 94;
    ELECTROHILICHURLGRENADIER = 95;
    ELECTROHILICHURLSHOOTER = 96;
    ELECTROHYPOSTASIS = 97;
    ELECTROREGISVINE = 98;
    ELECTROSAMACHURL = 99;
    ELECTROSLIME = 100;
    ELECTROSPECTER = 101;
    ELECTROWHOPPERFLOWER = 102;
    EMPEROROFFIREANDIRON = 103;
    EREMITEAXEVANGUARD = 104;
    EREMITECROSSBOW = 105;
    EREMITEDAYTHUNDER = 106;
    EREMITEDESERTCLEARWATER = 107;
    EREMITEFLORALRINGDANCER = 108;
    EREMITEGALEHUNTER = 109;
    EREMITELINEBREAKER = 110;
    EREMITERAVENBEAKHALBERDIER = 111;
    EREMITESCORCHINGLOREMASTER = 112;
    EREMITESTONEENCHANTER = 113;
    EREMITESUNFROST = 114;
    EREMITESWORDDANCER = 115;
    ERODINGAVATAROFLAVA = 116;
    EXPERIMENTALFIELDGENERATOR = 117;
    EYEOFTHESTORM = 118;
    FATUICRYOCICINMAGE = 119;
    FATUIELECTROCICINMAGE = 120;
    FATUIPYROAGENT = 121;
    FATUISKIRMISHERANEMOBOXERVANGUARD = 122;
    FATUISKIRMISHERCRYOGUNNERLEGIONNAIRE = 123;
    FATUISKIRMISHERELECTROHAMMERVANGUARD = 124;
    FATUISKIRMISHERGEOCHANTERBRACER = 125;
    FATUISKIRMISHERHYDROGUNNERLEGIONNAIRE = 126;
    FATUISKIRMISHERPYROSLINGERBRACER = 127;
    FEROCIOUSWARRIORGRAPPLER = 128;
    FEROCIOUSWARRIORHUMANRAM = 129;
    FEROCIOUSWARRIORWRESTLER = 130;
    FISHEROFHIDDENDEPTHS = 131;
    FLOATINGANEMOFUNGUS = 132;
    FLOATINGDENDROFUNGUS = 133;
    FLOATINGHYDROFUNGUS = 134;
    FLOWINGBLADEGREASESAW = 135;
    FLOWINGBLADEHARPOONTHROWER = 136;
    FLOWINGBLADESKIRMISHER = 137;
    FLOWINVERTEDWAYOBMANIFESTATION = 138;
    FLUIDAVATAROFLAVA = 139;
    FOLIARSWIFTWAYOBMANIFESTATION = 140;
    FORCERECONGROUNDEFFECTLANDCRUISER = 141;
    FORCERECONSCOUTLANDCRUISER = 142;
    FORCERECONSTORMLANDCRUISER = 143;
    FORGEDSANDINTERROGATOR = 144;
    FORGEDSANDJAVELINEER = 145;
    FORGEDSANDSHIELDBREAKER = 146;
    FROSTARMLAWACHURL = 147;
    FROSTNIGHTHERRA = 148;
    FROSTOPERATIVE = 149;
    FURNACESHELLMOUNTAINWEASEL = 150;
    GEOHYPOSTASIS = 151;
    GEOLOGICALSURVEYMEK = 152;
    GEOSAMACHURL = 153;
    GEOSLIME = 154;
    GEOSPECTER = 155;
    GEOVISHAP = 156;
    GEOVISHAPHATCHLING = 157;
    GILDEDSUNSHARDFROSTNIGHTSCION = 158;
    GLEAMINGCHARGEFROSTNIGHTSCION = 159;
    GLUTTONOUSYUMKASAURMOUNTAINKING = 160;
    GOLDENWOLFLORD = 161;
    GOLDFLAMEQUCUSAURTYRANT = 162;
    GROUNDEDGEOSHROOM = 163;
    GROUNDEDHYDROSHROOM = 164;
    GUARDIANOFAPEPSOASIS = 165;
    HALFTULPA = 166;
    HATJELLYFISH = 167;
    HEXADECATONICBATTLEHARDENEDMANDRAGORA = 168;
    HILICHURL = 169;
    HILICHURLBERSERKER = 170;
    HILICHURLFIGHTER = 171;
    HILICHURLGRENADIER = 172;
    HILICHURLSHOOTER = 173;
    HUNTERSRAY = 174;
    HYDROABYSSMAGE = 175;
    HYDROCICIN = 176;
    HYDROHILICHURLROGUE = 177;
    HYDROHYPOSTASIS = 178;
    HYDROHYPOSTASISSUMMON = 179;
    HYDROMIMICBOAR = 180;
    HYDROMIMICCRAB = 181;
    HYDROMIMICCRANE = 182;
    HYDROMIMICFINCH = 183;
    HYDROMIMICFROG = 184;
    HYDROMIMICMALLARD = 185;
    HYDROMIMICRAPTOR = 186;
    HYDROMIMICSQUIRREL = 187;
    HYDROSAMACHURL = 188;
    HYDROSLIME = 189;
    HYDROSPECTER = 190;
    HYDROTULPA = 191;
    ICESHIELDHILICHURLGUARD = 192;
    ICESHIELDWALLMITACHURL = 193;
    ICEWINDSUITE = 194;
    ICYCRYSTALFROSTNIGHTSCION = 195;
    IKTOMISAURUS = 196;
    IKTOMISAURUSCHICK = 197;
    IKTOMISAURUSWARRIORCRYOCRYSTALCANNON = 198;
    IKTOMISAURUSWARRIORICYTIDEBEARER = 199;
    INFINITESIMAL = 200;
    INIQUITOUSBAPTIST = 201;
    JADEPLUMETERRORSHROOM = 202;
    KAIRAGIDANCINGTHUNDER = 203;
    KAIRAGIFIERYMIGHT = 204;
    KNUCKLEDUCKLE = 205;
    KOHOLASAURUS = 206;
    KOHOLASAURUSWARRIORREEFSPLITTER = 207;
    KOHOLASAURUSWARRIORWAVESHUTTLER = 208;
    KOHOLASAURWHELP = 209;
    LARGEANEMOSLIME = 210;
    LARGECRYOSLIME = 211;
    LARGEDENDROSLIME = 212;
    LARGEELECTROSLIME = 213;
    LARGEGEOSLIME = 214;
    LARGEHYDROSLIME = 215;
    LARGEOVERGROWNBREACHERPRIMUS = 216;
    LARGEPYROSLIME = 217;
    LARGESHATTERSTONEBREACHERPRIMUS = 218;
    LASIGNORA = 219;
    LAVADRAGONSTATUE = 220;
    LEGATUSGOLEM = 221;
    LIAM = 222;
    LOCALLEGENDARMOREDCRAB = 223;
    LOCALLEGENDBLUBBERBEAST = 224;
    LOCALLEGENDCHERUBICSEAHARE = 225;
    LOCALLEGENDHATJELLYFISH = 226;
    LOCALLEGENDHUNTERSRAY = 227;
    LORDOFERODEDPRIMALFIRE = 228;
    LORDOFTHEHIDDENDEPTHSWHISPEREROFNIGHTMARES = 229;
    LUPUSBOREASDOMINATOROFWOLVES = 230;
    MAGATSUMITAKENARUKAMINOMIKOTO = 231;
    MAGUUKENKI = 232;
    MAGUUKENKIGALLOPINGFROST = 233;
    MAGUUKENKILONEGALE = 234;
    MAGUUKENKIMASKOFTERROR = 235;
    MILLELITHSERGEANT = 236;
    MILLELITHSOLDIER = 237;
    MILLENNIALPEARLSEAHORSE = 238;
    MIRRORMAIDEN = 239;
    MUTANTELECTROSLIME = 240;
    MYSTIFYINGMEGACHURL = 241;
    NIMBLEHARVESTERMEK = 242;
    NOBUSHIHITSUKEBAN = 243;
    NOBUSHIJINTOUBAN = 244;
    NOBUSHIKIKOUBAN = 245;
    OCEANID = 246;
    OCHIMUSHACANKEREDFLAME = 247;
    OCHIMUSHAENSORCELLEDTHUNDER = 248;
    OPRICHNIKIBOMBARDIER = 249;
    OPRICHNIKIFIREBLADESHOCKTROOPER = 250;
    OPRICHNIKIGRENADIER = 251;
    OPRICHNIKIHAILSTORMCANNONEER = 252;
    OPRICHNIKILINETROOPER = 253;
    OPRICHNIKIMEDIC = 254;
    OPRICHNIKISUPPORTTROOPER = 255;
    OPRICHNIKITHUNDERBLITZGVARDIYA = 256;
    OPRICHNIKIVANGUARD = 257;
    OVERGROWNBREACHERPRIMUS = 258;
    PERPETUALMECHANICALARRAY = 259;
    PRAETORIANGOLEM = 260;
    PRIMALCONSTRUCTPROSPECTOR = 261;
    PRIMALCONSTRUCTREPULSOR = 262;
    PRIMALCONSTRUCTRESHAPER = 263;
    PRIMEVALSOURCEDRAGONMECH = 264;
    PRIMOGEOVISHAP = 265;
    PRIMORDIALBATHYSMALVISHAP = 266;
    PYROABYSSMAGE = 267;
    PYROHILICHURLSHOOTER = 268;
    PYROHYPOSTASIS = 269;
    PYROREGISVINE = 270;
    PYROSLIME = 271;
    PYROSPECTER = 272;
    PYROWHOPPERFLOWER = 273;
    QUCUSAURUS = 274;
    QUCUSAURUSCHICK = 275;
    QUCUSAURUSWARRIORBLAZINGSKY = 276;
    QUCUSAURUSWARRIORHEARTSTARHAMMER = 277;
    RADIANTANTELOPE = 278;
    RADIANTBLADEHORN = 279;
    RADIANTGLACIALWOLF = 280;
    RADIANTLUNAPOD = 281;
    RADIANTMOONFLY = 282;
    RECONLOGMEK = 283;
    RIMEBITERBATHYSMALVISHAP = 284;
    ROCKCAVERNOUSWAYOBMANIFESTATION = 285;
    ROCKFONDRIFTHOUND = 286;
    ROCKFONDRIFTHOUNDWHELP = 287;
    ROCKSHIELDHILICHURLGUARD = 288;
    ROCKSHIELDWALLMITACHURL = 289;
    ROCKYAVILDSEN = 290;
    RUINCRUISER = 291;
    RUINDEFENDER = 292;
    RUINDESTROYER = 293;
    RUINDRAKEEARTHGUARD = 294;
    RUINDRAKESKYWATCH = 295;
    RUINGRADER = 296;
    RUINGUARD = 297;
    RUINHUNTER = 298;
    RUINSCOUT = 299;
    RUINSERPENT = 300;
    RULEROFTHECHIZHANGMOUNTAINSTIANYU = 301;
    RULEROFTHECHIZHANGMOUNTAINSYIJI = 302;
    SANGONOMIYACOHORT = 303;
    SECRETSOURCEAUTOMATONCONFIGURATIONDEVICE = 304;
    SECRETSOURCEAUTOMATONHUNTERSEEKER = 305;
    SECRETSOURCEAUTOMATONOVERSEERDEVICE = 306;
    SETEKHWENUT = 307;
    SHADOWYHUSKDEFENDER = 308;
    SHADOWYHUSKLINEBREAKER = 309;
    SHADOWYHUSKSTANDARDBEARER = 310;
    SHATTERSTONEBREACHERPRIMUS = 311;
    SHOGUNATEINFANTRY = 312;
    SHOGUNATEINFANTRYCAPTAIN = 313;
    SHOUKINOKAMITHEPRODIGAL = 314;
    SOLITARYSUANNI = 315;
    SPIRITOFOMENDENDROSPIRITSERPENT = 316;
    SPIRITOFOMENPYROSCORPION = 317;
    SPIRITOFOMENSTONEDRAKE = 318;
    SPIRITOFOMENWINDGLEDE = 319;
    SPIRITSPEAKERWARRIORCONTEMPLATOR = 320;
    SPIRITSPEAKERWARRIORDETERMINATOR = 321;
    SPIRITSPEAKERWARRIORPSYCHOKINETIC = 322;
    STERNSHIELDCRAB = 323;
    STONEHIDELAWACHURL = 324;
    STORMTERROR = 325;
    STRETCHYANEMOFUNGUS = 326;
    STRETCHYELECTROFUNGUS = 327;
    STRETCHYGEOFUNGUS = 328;
    STRETCHYPYROFUNGUS = 329;
    SUBLIMATEDQUEEN = 330;
    SUPERHEAVYLANDROVERMECHANIZEDFORTRESS = 331;
    SUPPRESSIONSPECIALISTMEK = 332;
    SURGINGCURRENTSFROSTNIGHTSCION = 333;
    SWIFTSTEPARMEDCOURIER = 334;
    SWIFTSTEPSEEKER = 335;
    SWIFTSTEPSTORMSCOUT = 336;
    TAINTEDWATERSPLITTINGPHANTASM = 337;
    TAINTEDWATERSPOUTINGPHANTASM = 338;
    TANGLEDVINESFROSTNIGHTSCION = 339;
    TATANKASAURUS = 340;
    TATANKASAURUSWARRIORSKYBREAKER = 341;
    TATANKASAURUSWARRIORSPIRITLIGHTCHASER = 342;
    TATANKASAURWHELP = 343;
    TENEBROUSMIMIFLORA = 344;
    TENEBROUSPAPILLATYPEI = 345;
    TEPETLISAURUS = 346;
    TEPETLISAURUSTRIBECHIEF = 347;
    TEPETLISAURUSWARRIORROCKBREAKERBLADE = 348;
    TEPETLISAURUSWARRIORSHARDSTRIKER = 349;
    TEPETLISAURWHELP = 350;
    TESTNODKRAIINFILTRATIONEVENTROBOT1 = 351;
    TESTNODKRAIINFILTRATIONEVENTROBOT2 = 352;
    THEDOCTOR = 353;
    THEGAMEBEFORETHEGATE = 354;
    THEKNAVE = 355;
    THUNDERCRAVENRIFTHOUND = 356;
    THUNDERCRAVENRIFTHOUNDWHELP = 357;
    THUNDERHELMLAWACHURL = 358;
    THUNDERINGWAYOBMANIFESTATION = 359;
    THUNDERMANIFESTATION = 360;
    TREASUREHOARDERSBOSS = 361;
    TREASUREHOARDERSCARMEN = 362;
    TREASUREHOARDERSCRUSHER = 363;
    TREASUREHOARDERSCRYOPOTIONEER = 364;
    TREASUREHOARDERSELECTROPOTIONEER = 365;
    TREASUREHOARDERSGRAVEDIGGER = 366;
    TREASUREHOARDERSHANDYMAN = 367;
    TREASUREHOARDERSHYDROPOTIONEER = 368;
    TREASUREHOARDERSLIULIU = 369;
    TREASUREHOARDERSMARKSMAN = 370;
    TREASUREHOARDERSPUGILIST = 371;
    TREASUREHOARDERSPYROPOTIONEER = 372;
    TREASUREHOARDERSRAPTOR = 373;
    TREASUREHOARDERSSCOUT = 374;
    TREASUREHOARDERSSEAMAN = 375;
    TREASUREHOARDERSWALLENSTEIN = 376;
    UNDERWATERPATROLMEK = 377;
    UNDERWATERSURVEYMEK = 378;
    UNUSUALHILICHURL = 379;
    VEILEDCLOUDCHASERFROSTNIGHTSCION = 380;
    VETERANARITHMETICENHANCERMEK = 381;
    VETERANFATUIPYROAGENT = 382;
    VETERANFATUISKIRMISHERCRYOGUNNERLEGIONNAIRE = 383;
    VETERANFATUISKIRMISHERELECTROHAMMERVANGUARD = 384;
    VETERANFATUISKIRMISHERPYROSLINGERBRACER = 385;
    VETERANFROSTOPERATIVE = 386;
    VETERANTAINTEDWATERSPLITTINGPHANTASM = 387;
    VETERANTAINTEDWATERSPOUTINGPHANTASM = 388;
    VETERANWINDOPERATIVE = 389;
    WAYWARDHERMETICSPIRITSPEAKER = 390;
    WHIRLINGCRYOFUNGUS = 391;
    WHIRLINGELECTROFUNGUS = 392;
    WHIRLINGPYROFUNGUS = 393;
    WILDERNESSEXILE = 394;
    WILDERNESSHUNTER = 395;
    WINDOPERATIVE = 396;
    WINGEDCRYOSHROOM = 397;
    WINGEDDENDROSHROOM = 398;
    WINGEDWARRIORFEATHERSHEDDER = 399;
    WINGEDWARRIORSKYMASTER = 400;
    WINGEDWARRIORSKYSOARER = 401;
    WOODENSHIELDHILICHURLGUARD = 402;
    WOODENSHIELDWALLMITACHURL = 403;
    XUANWENBEAST = 404;
    YORIKISAMURAI = 405;
    YUMKASAURUS = 406;
    YUMKASAURUSWARRIORFLOWINGSKYFIRE = 407;
    YUMKASAURUSWARRIORWHIRLINGLEAVES = 408;
    YUMKASAURWHELP = 409;
}
