import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { Build } from "../genshin/build.js";
import { recommendedPresetBuilds } from "../src/data/recommendedPresets.js";

const outputUrl = new URL(
  "../src/data/recommendedPresetHashes.js",
  import.meta.url
);

const encodedBuilds = recommendedPresetBuilds.map((build) =>
  Buffer.from(Build.encode(build).finish()).toString("hex")
);

const output = [
  "// Generated by `npm run generate:presets`; edit recommendedPresets.ts instead.",
  "const recommendedPresetHashes = [",
  ...encodedBuilds.map((encoded) => `  "${encoded}",`),
  "];",
  "",
  "export default recommendedPresetHashes;",
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const current = await readFile(outputUrl, "utf8").catch(() => "");
  if (current !== output) {
    throw new Error(
      `${fileURLToPath(outputUrl)} is stale; run npm run generate:presets`
    );
  }
} else {
  await writeFile(outputUrl, output, "utf8");
}
