import fs from "fs";

const generateVersion = (manifest) => {
  const genshinDbSource = manifest.sources.find(
    ({ id }) => id === "genshin-db"
  );
  if (!genshinDbSource?.version) {
    throw new Error("Game data manifest is missing the genshin-db version");
  }

  const content = `// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const GENSHIN_GAME_VERSION = "${manifest.gameVersion}";
export const GENSHIN_DB_VERSION = "${genshinDbSource.version}";
export const GENSHIN_DATA_SOURCES = ${JSON.stringify(
    manifest.sources,
    null,
    2
  )} as const;
`;

  fs.writeFileSync("./src/data/version.ts", content, "utf-8");
  console.log(
    `Generated version info: Game v${manifest.gameVersion}, ` +
      manifest.sources.map(({ id }) => id).join(" + ")
  );
};

export { generateVersion };
