import fs from "fs";
import { createRequire } from "module";

const require = createRequire(import.meta.url);

const generateVersion = () => {
  const genshinDbPackage = require("genshin-db/package.json");

  // Extract game version from description
  const match = genshinDbPackage.description.match(/Genshin Impact v([\d.]+)/);
  const gameVersion = match ? match[1] : genshinDbPackage.version;

  const versionData = {
    gameVersion,
    genshinDbVersion: genshinDbPackage.version,
    lastUpdated: new Date().toISOString(),
  };

  // Generate TypeScript constant file
  const content = `// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const GENSHIN_GAME_VERSION = "${gameVersion}";
export const GENSHIN_DB_VERSION = "${genshinDbPackage.version}";
export const LAST_UPDATED = "${versionData.lastUpdated}";
`;

  fs.writeFileSync("./src/data/version.ts", content, "utf-8");
  console.log(`Generated version info: Game v${gameVersion}, DB v${genshinDbPackage.version}`);
};

generateVersion();
export { generateVersion };
