// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.20.3
// source: gcsim.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal.js";
import { AttributeType, attributeTypeFromJSON, attributeTypeToJSON } from "./attribute.js";
import { Character, characterFromJSON, characterToJSON } from "./character.js";
import { Element, elementFromJSON, elementToJSON } from "./element.js";
import { Set, setFromJSON, setToJSON } from "./set.js";
import { Weapon, weaponFromJSON, weaponToJSON } from "./weapon.js";

export const protobufPackage = "io.leishi.genshin.proto";

/** Key-value parameter for character/weapon/set customization */
export interface GCSimScriptParam {
  key: string;
  value: string;
}

/** Weapon configuration */
export interface GCSimScriptWeaponInfo {
  weapon: Weapon;
  level: number;
  maxLevel: number;
  refinement: number;
  params: GCSimScriptParam[];
}

/** Artifact set configuration */
export interface GCSimScriptSetInfo {
  set: Set;
  /** Number of pieces (2 or 4) */
  count: number;
  params: GCSimScriptParam[];
}

/** Character stat with optional label for grouping (e.g., "flower", "feather") */
export interface GCSimScriptCharacterStat {
  type: AttributeType;
  value: number;
  /** Label for stat grouping (e.g., "flower", "sands") */
  label: string;
}

/**
 * Random substat generation based on artifact main stats
 * Example: diluc add stats random rarity=5 sand=hp% goblet=pyro% circlet=cr;
 */
export interface GCSimScriptRandomSubstats {
  /** Artifact rarity (4 or 5) */
  rarity: number;
  /** Sands main stat */
  sand: AttributeType;
  /** Goblet main stat */
  goblet: AttributeType;
  /** Circlet main stat */
  circlet: AttributeType;
}

/** Character configuration */
export interface GCSimScriptCharacterInfo {
  character: Character;
  level: number;
  maxLevel: number;
  constellation: number;
  /** [attack, skill, burst] */
  talents: number[];
  weaponInfo: GCSimScriptWeaponInfo | undefined;
  setInfos: GCSimScriptSetInfo[];
  stats: GCSimScriptCharacterStat[];
  params: GCSimScriptParam[];
  startHp: number;
  /** Random substat config */
  randomSubstats:
    | GCSimScriptRandomSubstats
    | undefined;
  /** Preserve the engine identity (for example Aether vs Lumine) */
  gcsimName: string;
}

/** Simulation options */
export interface GCSimScriptOptions {
  defhalt: boolean;
  hitlag: boolean;
  iteration: number;
  duration: number;
  workers: number;
  swapDelay: number;
  attackDelay: number;
  chargeDelay: number;
  skillDelay: number;
  burstDelay: number;
  jumpDelay: number;
  dashDelay: number;
  aimDelay: number;
  /** Ignore energy requirements for bursts */
  ignoreBurstEnergy: boolean;
  /** Preset delay config (e.g., "human") */
  frameDefaults: string;
}

/**
 * Energy settings for periodic energy generation
 * Example: energy once interval=300 amount=1
 * Example: energy every interval=300,600 amount=1
 */
export interface GCSimScriptEnergySettings {
  type: GCSimScriptEnergySettings_EnergyType;
  /** For ONCE: the frame. For EVERY: min interval */
  start: number;
  /** For EVERY: max interval (random between start and end) */
  end: number;
  /** Energy amount per drop */
  amount: number;
}

export enum GCSimScriptEnergySettings_EnergyType {
  /** ONCE - One-time energy drop at specific frame */
  ONCE = 0,
  /** EVERY - Periodic energy drops */
  EVERY = 1,
  UNRECOGNIZED = -1,
}

export function gCSimScriptEnergySettings_EnergyTypeFromJSON(object: any): GCSimScriptEnergySettings_EnergyType {
  switch (object) {
    case 0:
    case "ONCE":
      return GCSimScriptEnergySettings_EnergyType.ONCE;
    case 1:
    case "EVERY":
      return GCSimScriptEnergySettings_EnergyType.EVERY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GCSimScriptEnergySettings_EnergyType.UNRECOGNIZED;
  }
}

export function gCSimScriptEnergySettings_EnergyTypeToJSON(object: GCSimScriptEnergySettings_EnergyType): string {
  switch (object) {
    case GCSimScriptEnergySettings_EnergyType.ONCE:
      return "ONCE";
    case GCSimScriptEnergySettings_EnergyType.EVERY:
      return "EVERY";
    case GCSimScriptEnergySettings_EnergyType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Hurt settings for periodic damage to active character
 * Example: hurt once interval=300 amount=1,300 element=physical
 * Example: hurt every interval=480,720 amount=1,300 element=physical
 */
export interface GCSimScriptHurtSettings {
  type: GCSimScriptHurtSettings_HurtType;
  /** For ONCE: the frame. For EVERY: min interval */
  start: number;
  /** For EVERY: max interval (random between start and end) */
  end: number;
  /** Damage range (random between min and max) */
  amount: GCSimScriptHurtSettings_HurtAmount | undefined;
  element: Element;
}

export enum GCSimScriptHurtSettings_HurtType {
  /** ONCE - One-time damage at specific frame */
  ONCE = 0,
  /** EVERY - Periodic damage */
  EVERY = 1,
  UNRECOGNIZED = -1,
}

export function gCSimScriptHurtSettings_HurtTypeFromJSON(object: any): GCSimScriptHurtSettings_HurtType {
  switch (object) {
    case 0:
    case "ONCE":
      return GCSimScriptHurtSettings_HurtType.ONCE;
    case 1:
    case "EVERY":
      return GCSimScriptHurtSettings_HurtType.EVERY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GCSimScriptHurtSettings_HurtType.UNRECOGNIZED;
  }
}

export function gCSimScriptHurtSettings_HurtTypeToJSON(object: GCSimScriptHurtSettings_HurtType): string {
  switch (object) {
    case GCSimScriptHurtSettings_HurtType.ONCE:
      return "ONCE";
    case GCSimScriptHurtSettings_HurtType.EVERY:
      return "EVERY";
    case GCSimScriptHurtSettings_HurtType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface GCSimScriptHurtSettings_HurtAmount {
  min: number;
  max: number;
}

/**
 * Predefined enemy type configuration
 * Example: target type=hilichurl[hp_mult=2.0,particles=1];
 */
export interface GCSimScriptTargetType {
  /** Enemy type name (e.g., "hilichurl", "ruin_guard") */
  typeName: string;
  /** HP multiplier */
  hpMultiplier: number;
  /** Whether to drop particles */
  particles: boolean;
}

/** Target/enemy configuration */
export interface GCSimScriptTarget {
  /** Position [x, y] - exactly 2 values */
  position: number[];
  /** Hitbox radius */
  radius: number;
  /** Enemy level (1-100) */
  level: number;
  /** Base resistance for all elements */
  resist: number;
  /** Enemy HP */
  hp: number;
  /** Drop particle every X damage dealt */
  particleThreshold: number;
  /** Number of particles to drop */
  particleDropCount: number;
  /** Freeze resistance */
  freezeResist: number;
  /** Electro resistance */
  electroResist: number;
  /** Hydro resistance */
  hydroResist: number;
  /** Pyro resistance */
  pyroResist: number;
  /** Cryo resistance */
  cryoResist: number;
  /** Dendro resistance */
  dendroResist: number;
  /** Physical resistance */
  physicalResist: number;
  /** Anemo resistance */
  anemoResist: number;
  /** Geo resistance */
  geoResist: number;
  /** Predefined enemy type */
  type:
    | GCSimScriptTargetType
    | undefined;
  /** Element of dropped particles */
  particleElement: Element;
  /** Global target HP multiplier */
  hpMult: number;
}

/** Complete GCSim script configuration */
export interface GCSimScript {
  options: GCSimScriptOptions | undefined;
  characterInfos: GCSimScriptCharacterInfo[];
  targets: GCSimScriptTarget[];
  energySettings: GCSimScriptEnergySettings | undefined;
  hurtSettings:
    | GCSimScriptHurtSettings
    | undefined;
  /** Action script lines (not parsed) */
  scripts: string[];
}

/** Collection of GCSim scripts */
export interface GCSim {
  scripts: GCSimScript[];
}

function createBaseGCSimScriptParam(): GCSimScriptParam {
  return { key: "", value: "" };
}

export const GCSimScriptParam = {
  encode(message: GCSimScriptParam, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptParam {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptParam();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptParam {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: GCSimScriptParam): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptParam>, I>>(base?: I): GCSimScriptParam {
    return GCSimScriptParam.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptParam>, I>>(object: I): GCSimScriptParam {
    const message = createBaseGCSimScriptParam();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseGCSimScriptWeaponInfo(): GCSimScriptWeaponInfo {
  return { weapon: 0, level: 0, maxLevel: 0, refinement: 0, params: [] };
}

export const GCSimScriptWeaponInfo = {
  encode(message: GCSimScriptWeaponInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.weapon !== 0) {
      writer.uint32(8).int32(message.weapon);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    if (message.maxLevel !== 0) {
      writer.uint32(24).int32(message.maxLevel);
    }
    if (message.refinement !== 0) {
      writer.uint32(32).int32(message.refinement);
    }
    for (const v of message.params) {
      GCSimScriptParam.encode(v!, writer.uint32(42).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptWeaponInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptWeaponInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.weapon = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.maxLevel = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.refinement = reader.int32();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.params.push(GCSimScriptParam.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptWeaponInfo {
    return {
      weapon: isSet(object.weapon) ? weaponFromJSON(object.weapon) : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      maxLevel: isSet(object.maxLevel) ? globalThis.Number(object.maxLevel) : 0,
      refinement: isSet(object.refinement) ? globalThis.Number(object.refinement) : 0,
      params: globalThis.Array.isArray(object?.params)
        ? object.params.map((e: any) => GCSimScriptParam.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GCSimScriptWeaponInfo): unknown {
    const obj: any = {};
    if (message.weapon !== 0) {
      obj.weapon = weaponToJSON(message.weapon);
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.maxLevel !== 0) {
      obj.maxLevel = Math.round(message.maxLevel);
    }
    if (message.refinement !== 0) {
      obj.refinement = Math.round(message.refinement);
    }
    if (message.params?.length) {
      obj.params = message.params.map((e) => GCSimScriptParam.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptWeaponInfo>, I>>(base?: I): GCSimScriptWeaponInfo {
    return GCSimScriptWeaponInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptWeaponInfo>, I>>(object: I): GCSimScriptWeaponInfo {
    const message = createBaseGCSimScriptWeaponInfo();
    message.weapon = object.weapon ?? 0;
    message.level = object.level ?? 0;
    message.maxLevel = object.maxLevel ?? 0;
    message.refinement = object.refinement ?? 0;
    message.params = object.params?.map((e) => GCSimScriptParam.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGCSimScriptSetInfo(): GCSimScriptSetInfo {
  return { set: 0, count: 0, params: [] };
}

export const GCSimScriptSetInfo = {
  encode(message: GCSimScriptSetInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.set !== 0) {
      writer.uint32(8).int32(message.set);
    }
    if (message.count !== 0) {
      writer.uint32(16).int32(message.count);
    }
    for (const v of message.params) {
      GCSimScriptParam.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptSetInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptSetInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.set = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.count = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.params.push(GCSimScriptParam.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptSetInfo {
    return {
      set: isSet(object.set) ? setFromJSON(object.set) : 0,
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      params: globalThis.Array.isArray(object?.params)
        ? object.params.map((e: any) => GCSimScriptParam.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GCSimScriptSetInfo): unknown {
    const obj: any = {};
    if (message.set !== 0) {
      obj.set = setToJSON(message.set);
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.params?.length) {
      obj.params = message.params.map((e) => GCSimScriptParam.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptSetInfo>, I>>(base?: I): GCSimScriptSetInfo {
    return GCSimScriptSetInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptSetInfo>, I>>(object: I): GCSimScriptSetInfo {
    const message = createBaseGCSimScriptSetInfo();
    message.set = object.set ?? 0;
    message.count = object.count ?? 0;
    message.params = object.params?.map((e) => GCSimScriptParam.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGCSimScriptCharacterStat(): GCSimScriptCharacterStat {
  return { type: 0, value: 0, label: "" };
}

export const GCSimScriptCharacterStat = {
  encode(message: GCSimScriptCharacterStat, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.value !== 0) {
      writer.uint32(21).float(message.value);
    }
    if (message.label !== "") {
      writer.uint32(26).string(message.label);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptCharacterStat {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptCharacterStat();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.value = reader.float();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.label = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptCharacterStat {
    return {
      type: isSet(object.type) ? attributeTypeFromJSON(object.type) : 0,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      label: isSet(object.label) ? globalThis.String(object.label) : "",
    };
  },

  toJSON(message: GCSimScriptCharacterStat): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = attributeTypeToJSON(message.type);
    }
    if (message.value !== 0) {
      obj.value = message.value;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptCharacterStat>, I>>(base?: I): GCSimScriptCharacterStat {
    return GCSimScriptCharacterStat.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptCharacterStat>, I>>(object: I): GCSimScriptCharacterStat {
    const message = createBaseGCSimScriptCharacterStat();
    message.type = object.type ?? 0;
    message.value = object.value ?? 0;
    message.label = object.label ?? "";
    return message;
  },
};

function createBaseGCSimScriptRandomSubstats(): GCSimScriptRandomSubstats {
  return { rarity: 0, sand: 0, goblet: 0, circlet: 0 };
}

export const GCSimScriptRandomSubstats = {
  encode(message: GCSimScriptRandomSubstats, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.rarity !== 0) {
      writer.uint32(8).int32(message.rarity);
    }
    if (message.sand !== 0) {
      writer.uint32(16).int32(message.sand);
    }
    if (message.goblet !== 0) {
      writer.uint32(24).int32(message.goblet);
    }
    if (message.circlet !== 0) {
      writer.uint32(32).int32(message.circlet);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptRandomSubstats {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptRandomSubstats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.rarity = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.sand = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.goblet = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.circlet = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptRandomSubstats {
    return {
      rarity: isSet(object.rarity) ? globalThis.Number(object.rarity) : 0,
      sand: isSet(object.sand) ? attributeTypeFromJSON(object.sand) : 0,
      goblet: isSet(object.goblet) ? attributeTypeFromJSON(object.goblet) : 0,
      circlet: isSet(object.circlet) ? attributeTypeFromJSON(object.circlet) : 0,
    };
  },

  toJSON(message: GCSimScriptRandomSubstats): unknown {
    const obj: any = {};
    if (message.rarity !== 0) {
      obj.rarity = Math.round(message.rarity);
    }
    if (message.sand !== 0) {
      obj.sand = attributeTypeToJSON(message.sand);
    }
    if (message.goblet !== 0) {
      obj.goblet = attributeTypeToJSON(message.goblet);
    }
    if (message.circlet !== 0) {
      obj.circlet = attributeTypeToJSON(message.circlet);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptRandomSubstats>, I>>(base?: I): GCSimScriptRandomSubstats {
    return GCSimScriptRandomSubstats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptRandomSubstats>, I>>(object: I): GCSimScriptRandomSubstats {
    const message = createBaseGCSimScriptRandomSubstats();
    message.rarity = object.rarity ?? 0;
    message.sand = object.sand ?? 0;
    message.goblet = object.goblet ?? 0;
    message.circlet = object.circlet ?? 0;
    return message;
  },
};

function createBaseGCSimScriptCharacterInfo(): GCSimScriptCharacterInfo {
  return {
    character: 0,
    level: 0,
    maxLevel: 0,
    constellation: 0,
    talents: [],
    weaponInfo: undefined,
    setInfos: [],
    stats: [],
    params: [],
    startHp: 0,
    randomSubstats: undefined,
    gcsimName: "",
  };
}

export const GCSimScriptCharacterInfo = {
  encode(message: GCSimScriptCharacterInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.character !== 0) {
      writer.uint32(8).int32(message.character);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    if (message.maxLevel !== 0) {
      writer.uint32(24).int32(message.maxLevel);
    }
    if (message.constellation !== 0) {
      writer.uint32(32).int32(message.constellation);
    }
    writer.uint32(42).fork();
    for (const v of message.talents) {
      writer.int32(v);
    }
    writer.ldelim();
    if (message.weaponInfo !== undefined) {
      GCSimScriptWeaponInfo.encode(message.weaponInfo, writer.uint32(50).fork()).ldelim();
    }
    for (const v of message.setInfos) {
      GCSimScriptSetInfo.encode(v!, writer.uint32(58).fork()).ldelim();
    }
    for (const v of message.stats) {
      GCSimScriptCharacterStat.encode(v!, writer.uint32(66).fork()).ldelim();
    }
    for (const v of message.params) {
      GCSimScriptParam.encode(v!, writer.uint32(74).fork()).ldelim();
    }
    if (message.startHp !== 0) {
      writer.uint32(80).int32(message.startHp);
    }
    if (message.randomSubstats !== undefined) {
      GCSimScriptRandomSubstats.encode(message.randomSubstats, writer.uint32(90).fork()).ldelim();
    }
    if (message.gcsimName !== "") {
      writer.uint32(98).string(message.gcsimName);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptCharacterInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptCharacterInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.character = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.maxLevel = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.constellation = reader.int32();
          continue;
        case 5:
          if (tag === 40) {
            message.talents.push(reader.int32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.talents.push(reader.int32());
            }

            continue;
          }

          break;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.weaponInfo = GCSimScriptWeaponInfo.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.setInfos.push(GCSimScriptSetInfo.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.stats.push(GCSimScriptCharacterStat.decode(reader, reader.uint32()));
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.params.push(GCSimScriptParam.decode(reader, reader.uint32()));
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.startHp = reader.int32();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.randomSubstats = GCSimScriptRandomSubstats.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.gcsimName = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptCharacterInfo {
    return {
      character: isSet(object.character) ? characterFromJSON(object.character) : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      maxLevel: isSet(object.maxLevel) ? globalThis.Number(object.maxLevel) : 0,
      constellation: isSet(object.constellation) ? globalThis.Number(object.constellation) : 0,
      talents: globalThis.Array.isArray(object?.talents) ? object.talents.map((e: any) => globalThis.Number(e)) : [],
      weaponInfo: isSet(object.weaponInfo) ? GCSimScriptWeaponInfo.fromJSON(object.weaponInfo) : undefined,
      setInfos: globalThis.Array.isArray(object?.setInfos)
        ? object.setInfos.map((e: any) => GCSimScriptSetInfo.fromJSON(e))
        : [],
      stats: globalThis.Array.isArray(object?.stats)
        ? object.stats.map((e: any) => GCSimScriptCharacterStat.fromJSON(e))
        : [],
      params: globalThis.Array.isArray(object?.params)
        ? object.params.map((e: any) => GCSimScriptParam.fromJSON(e))
        : [],
      startHp: isSet(object.startHp) ? globalThis.Number(object.startHp) : 0,
      randomSubstats: isSet(object.randomSubstats)
        ? GCSimScriptRandomSubstats.fromJSON(object.randomSubstats)
        : undefined,
      gcsimName: isSet(object.gcsimName) ? globalThis.String(object.gcsimName) : "",
    };
  },

  toJSON(message: GCSimScriptCharacterInfo): unknown {
    const obj: any = {};
    if (message.character !== 0) {
      obj.character = characterToJSON(message.character);
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.maxLevel !== 0) {
      obj.maxLevel = Math.round(message.maxLevel);
    }
    if (message.constellation !== 0) {
      obj.constellation = Math.round(message.constellation);
    }
    if (message.talents?.length) {
      obj.talents = message.talents.map((e) => Math.round(e));
    }
    if (message.weaponInfo !== undefined) {
      obj.weaponInfo = GCSimScriptWeaponInfo.toJSON(message.weaponInfo);
    }
    if (message.setInfos?.length) {
      obj.setInfos = message.setInfos.map((e) => GCSimScriptSetInfo.toJSON(e));
    }
    if (message.stats?.length) {
      obj.stats = message.stats.map((e) => GCSimScriptCharacterStat.toJSON(e));
    }
    if (message.params?.length) {
      obj.params = message.params.map((e) => GCSimScriptParam.toJSON(e));
    }
    if (message.startHp !== 0) {
      obj.startHp = Math.round(message.startHp);
    }
    if (message.randomSubstats !== undefined) {
      obj.randomSubstats = GCSimScriptRandomSubstats.toJSON(message.randomSubstats);
    }
    if (message.gcsimName !== "") {
      obj.gcsimName = message.gcsimName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptCharacterInfo>, I>>(base?: I): GCSimScriptCharacterInfo {
    return GCSimScriptCharacterInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptCharacterInfo>, I>>(object: I): GCSimScriptCharacterInfo {
    const message = createBaseGCSimScriptCharacterInfo();
    message.character = object.character ?? 0;
    message.level = object.level ?? 0;
    message.maxLevel = object.maxLevel ?? 0;
    message.constellation = object.constellation ?? 0;
    message.talents = object.talents?.map((e) => e) || [];
    message.weaponInfo = (object.weaponInfo !== undefined && object.weaponInfo !== null)
      ? GCSimScriptWeaponInfo.fromPartial(object.weaponInfo)
      : undefined;
    message.setInfos = object.setInfos?.map((e) => GCSimScriptSetInfo.fromPartial(e)) || [];
    message.stats = object.stats?.map((e) => GCSimScriptCharacterStat.fromPartial(e)) || [];
    message.params = object.params?.map((e) => GCSimScriptParam.fromPartial(e)) || [];
    message.startHp = object.startHp ?? 0;
    message.randomSubstats = (object.randomSubstats !== undefined && object.randomSubstats !== null)
      ? GCSimScriptRandomSubstats.fromPartial(object.randomSubstats)
      : undefined;
    message.gcsimName = object.gcsimName ?? "";
    return message;
  },
};

function createBaseGCSimScriptOptions(): GCSimScriptOptions {
  return {
    defhalt: false,
    hitlag: false,
    iteration: 0,
    duration: 0,
    workers: 0,
    swapDelay: 0,
    attackDelay: 0,
    chargeDelay: 0,
    skillDelay: 0,
    burstDelay: 0,
    jumpDelay: 0,
    dashDelay: 0,
    aimDelay: 0,
    ignoreBurstEnergy: false,
    frameDefaults: "",
  };
}

export const GCSimScriptOptions = {
  encode(message: GCSimScriptOptions, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.defhalt !== false) {
      writer.uint32(8).bool(message.defhalt);
    }
    if (message.hitlag !== false) {
      writer.uint32(16).bool(message.hitlag);
    }
    if (message.iteration !== 0) {
      writer.uint32(24).int32(message.iteration);
    }
    if (message.duration !== 0) {
      writer.uint32(32).int32(message.duration);
    }
    if (message.workers !== 0) {
      writer.uint32(40).int32(message.workers);
    }
    if (message.swapDelay !== 0) {
      writer.uint32(48).int32(message.swapDelay);
    }
    if (message.attackDelay !== 0) {
      writer.uint32(56).int32(message.attackDelay);
    }
    if (message.chargeDelay !== 0) {
      writer.uint32(64).int32(message.chargeDelay);
    }
    if (message.skillDelay !== 0) {
      writer.uint32(72).int32(message.skillDelay);
    }
    if (message.burstDelay !== 0) {
      writer.uint32(80).int32(message.burstDelay);
    }
    if (message.jumpDelay !== 0) {
      writer.uint32(88).int32(message.jumpDelay);
    }
    if (message.dashDelay !== 0) {
      writer.uint32(96).int32(message.dashDelay);
    }
    if (message.aimDelay !== 0) {
      writer.uint32(104).int32(message.aimDelay);
    }
    if (message.ignoreBurstEnergy !== false) {
      writer.uint32(112).bool(message.ignoreBurstEnergy);
    }
    if (message.frameDefaults !== "") {
      writer.uint32(122).string(message.frameDefaults);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptOptions {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.defhalt = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.hitlag = reader.bool();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.iteration = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.duration = reader.int32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.workers = reader.int32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.swapDelay = reader.int32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.attackDelay = reader.int32();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.chargeDelay = reader.int32();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.skillDelay = reader.int32();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.burstDelay = reader.int32();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.jumpDelay = reader.int32();
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.dashDelay = reader.int32();
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.aimDelay = reader.int32();
          continue;
        case 14:
          if (tag !== 112) {
            break;
          }

          message.ignoreBurstEnergy = reader.bool();
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.frameDefaults = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptOptions {
    return {
      defhalt: isSet(object.defhalt) ? globalThis.Boolean(object.defhalt) : false,
      hitlag: isSet(object.hitlag) ? globalThis.Boolean(object.hitlag) : false,
      iteration: isSet(object.iteration) ? globalThis.Number(object.iteration) : 0,
      duration: isSet(object.duration) ? globalThis.Number(object.duration) : 0,
      workers: isSet(object.workers) ? globalThis.Number(object.workers) : 0,
      swapDelay: isSet(object.swapDelay) ? globalThis.Number(object.swapDelay) : 0,
      attackDelay: isSet(object.attackDelay) ? globalThis.Number(object.attackDelay) : 0,
      chargeDelay: isSet(object.chargeDelay) ? globalThis.Number(object.chargeDelay) : 0,
      skillDelay: isSet(object.skillDelay) ? globalThis.Number(object.skillDelay) : 0,
      burstDelay: isSet(object.burstDelay) ? globalThis.Number(object.burstDelay) : 0,
      jumpDelay: isSet(object.jumpDelay) ? globalThis.Number(object.jumpDelay) : 0,
      dashDelay: isSet(object.dashDelay) ? globalThis.Number(object.dashDelay) : 0,
      aimDelay: isSet(object.aimDelay) ? globalThis.Number(object.aimDelay) : 0,
      ignoreBurstEnergy: isSet(object.ignoreBurstEnergy) ? globalThis.Boolean(object.ignoreBurstEnergy) : false,
      frameDefaults: isSet(object.frameDefaults) ? globalThis.String(object.frameDefaults) : "",
    };
  },

  toJSON(message: GCSimScriptOptions): unknown {
    const obj: any = {};
    if (message.defhalt !== false) {
      obj.defhalt = message.defhalt;
    }
    if (message.hitlag !== false) {
      obj.hitlag = message.hitlag;
    }
    if (message.iteration !== 0) {
      obj.iteration = Math.round(message.iteration);
    }
    if (message.duration !== 0) {
      obj.duration = Math.round(message.duration);
    }
    if (message.workers !== 0) {
      obj.workers = Math.round(message.workers);
    }
    if (message.swapDelay !== 0) {
      obj.swapDelay = Math.round(message.swapDelay);
    }
    if (message.attackDelay !== 0) {
      obj.attackDelay = Math.round(message.attackDelay);
    }
    if (message.chargeDelay !== 0) {
      obj.chargeDelay = Math.round(message.chargeDelay);
    }
    if (message.skillDelay !== 0) {
      obj.skillDelay = Math.round(message.skillDelay);
    }
    if (message.burstDelay !== 0) {
      obj.burstDelay = Math.round(message.burstDelay);
    }
    if (message.jumpDelay !== 0) {
      obj.jumpDelay = Math.round(message.jumpDelay);
    }
    if (message.dashDelay !== 0) {
      obj.dashDelay = Math.round(message.dashDelay);
    }
    if (message.aimDelay !== 0) {
      obj.aimDelay = Math.round(message.aimDelay);
    }
    if (message.ignoreBurstEnergy !== false) {
      obj.ignoreBurstEnergy = message.ignoreBurstEnergy;
    }
    if (message.frameDefaults !== "") {
      obj.frameDefaults = message.frameDefaults;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptOptions>, I>>(base?: I): GCSimScriptOptions {
    return GCSimScriptOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptOptions>, I>>(object: I): GCSimScriptOptions {
    const message = createBaseGCSimScriptOptions();
    message.defhalt = object.defhalt ?? false;
    message.hitlag = object.hitlag ?? false;
    message.iteration = object.iteration ?? 0;
    message.duration = object.duration ?? 0;
    message.workers = object.workers ?? 0;
    message.swapDelay = object.swapDelay ?? 0;
    message.attackDelay = object.attackDelay ?? 0;
    message.chargeDelay = object.chargeDelay ?? 0;
    message.skillDelay = object.skillDelay ?? 0;
    message.burstDelay = object.burstDelay ?? 0;
    message.jumpDelay = object.jumpDelay ?? 0;
    message.dashDelay = object.dashDelay ?? 0;
    message.aimDelay = object.aimDelay ?? 0;
    message.ignoreBurstEnergy = object.ignoreBurstEnergy ?? false;
    message.frameDefaults = object.frameDefaults ?? "";
    return message;
  },
};

function createBaseGCSimScriptEnergySettings(): GCSimScriptEnergySettings {
  return { type: 0, start: 0, end: 0, amount: 0 };
}

export const GCSimScriptEnergySettings = {
  encode(message: GCSimScriptEnergySettings, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.start !== 0) {
      writer.uint32(16).int32(message.start);
    }
    if (message.end !== 0) {
      writer.uint32(24).int32(message.end);
    }
    if (message.amount !== 0) {
      writer.uint32(32).int32(message.amount);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptEnergySettings {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptEnergySettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.start = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.end = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.amount = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptEnergySettings {
    return {
      type: isSet(object.type) ? gCSimScriptEnergySettings_EnergyTypeFromJSON(object.type) : 0,
      start: isSet(object.start) ? globalThis.Number(object.start) : 0,
      end: isSet(object.end) ? globalThis.Number(object.end) : 0,
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
    };
  },

  toJSON(message: GCSimScriptEnergySettings): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = gCSimScriptEnergySettings_EnergyTypeToJSON(message.type);
    }
    if (message.start !== 0) {
      obj.start = Math.round(message.start);
    }
    if (message.end !== 0) {
      obj.end = Math.round(message.end);
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptEnergySettings>, I>>(base?: I): GCSimScriptEnergySettings {
    return GCSimScriptEnergySettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptEnergySettings>, I>>(object: I): GCSimScriptEnergySettings {
    const message = createBaseGCSimScriptEnergySettings();
    message.type = object.type ?? 0;
    message.start = object.start ?? 0;
    message.end = object.end ?? 0;
    message.amount = object.amount ?? 0;
    return message;
  },
};

function createBaseGCSimScriptHurtSettings(): GCSimScriptHurtSettings {
  return { type: 0, start: 0, end: 0, amount: undefined, element: 0 };
}

export const GCSimScriptHurtSettings = {
  encode(message: GCSimScriptHurtSettings, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.start !== 0) {
      writer.uint32(16).int32(message.start);
    }
    if (message.end !== 0) {
      writer.uint32(24).int32(message.end);
    }
    if (message.amount !== undefined) {
      GCSimScriptHurtSettings_HurtAmount.encode(message.amount, writer.uint32(34).fork()).ldelim();
    }
    if (message.element !== 0) {
      writer.uint32(40).int32(message.element);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptHurtSettings {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptHurtSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.start = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.end = reader.int32();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.amount = GCSimScriptHurtSettings_HurtAmount.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.element = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptHurtSettings {
    return {
      type: isSet(object.type) ? gCSimScriptHurtSettings_HurtTypeFromJSON(object.type) : 0,
      start: isSet(object.start) ? globalThis.Number(object.start) : 0,
      end: isSet(object.end) ? globalThis.Number(object.end) : 0,
      amount: isSet(object.amount) ? GCSimScriptHurtSettings_HurtAmount.fromJSON(object.amount) : undefined,
      element: isSet(object.element) ? elementFromJSON(object.element) : 0,
    };
  },

  toJSON(message: GCSimScriptHurtSettings): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = gCSimScriptHurtSettings_HurtTypeToJSON(message.type);
    }
    if (message.start !== 0) {
      obj.start = Math.round(message.start);
    }
    if (message.end !== 0) {
      obj.end = Math.round(message.end);
    }
    if (message.amount !== undefined) {
      obj.amount = GCSimScriptHurtSettings_HurtAmount.toJSON(message.amount);
    }
    if (message.element !== 0) {
      obj.element = elementToJSON(message.element);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptHurtSettings>, I>>(base?: I): GCSimScriptHurtSettings {
    return GCSimScriptHurtSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptHurtSettings>, I>>(object: I): GCSimScriptHurtSettings {
    const message = createBaseGCSimScriptHurtSettings();
    message.type = object.type ?? 0;
    message.start = object.start ?? 0;
    message.end = object.end ?? 0;
    message.amount = (object.amount !== undefined && object.amount !== null)
      ? GCSimScriptHurtSettings_HurtAmount.fromPartial(object.amount)
      : undefined;
    message.element = object.element ?? 0;
    return message;
  },
};

function createBaseGCSimScriptHurtSettings_HurtAmount(): GCSimScriptHurtSettings_HurtAmount {
  return { min: 0, max: 0 };
}

export const GCSimScriptHurtSettings_HurtAmount = {
  encode(message: GCSimScriptHurtSettings_HurtAmount, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.min !== 0) {
      writer.uint32(13).float(message.min);
    }
    if (message.max !== 0) {
      writer.uint32(21).float(message.max);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptHurtSettings_HurtAmount {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptHurtSettings_HurtAmount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 13) {
            break;
          }

          message.min = reader.float();
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.max = reader.float();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptHurtSettings_HurtAmount {
    return {
      min: isSet(object.min) ? globalThis.Number(object.min) : 0,
      max: isSet(object.max) ? globalThis.Number(object.max) : 0,
    };
  },

  toJSON(message: GCSimScriptHurtSettings_HurtAmount): unknown {
    const obj: any = {};
    if (message.min !== 0) {
      obj.min = message.min;
    }
    if (message.max !== 0) {
      obj.max = message.max;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptHurtSettings_HurtAmount>, I>>(
    base?: I,
  ): GCSimScriptHurtSettings_HurtAmount {
    return GCSimScriptHurtSettings_HurtAmount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptHurtSettings_HurtAmount>, I>>(
    object: I,
  ): GCSimScriptHurtSettings_HurtAmount {
    const message = createBaseGCSimScriptHurtSettings_HurtAmount();
    message.min = object.min ?? 0;
    message.max = object.max ?? 0;
    return message;
  },
};

function createBaseGCSimScriptTargetType(): GCSimScriptTargetType {
  return { typeName: "", hpMultiplier: 0, particles: false };
}

export const GCSimScriptTargetType = {
  encode(message: GCSimScriptTargetType, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.typeName !== "") {
      writer.uint32(10).string(message.typeName);
    }
    if (message.hpMultiplier !== 0) {
      writer.uint32(21).float(message.hpMultiplier);
    }
    if (message.particles !== false) {
      writer.uint32(24).bool(message.particles);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptTargetType {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptTargetType();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.typeName = reader.string();
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.hpMultiplier = reader.float();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.particles = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptTargetType {
    return {
      typeName: isSet(object.typeName) ? globalThis.String(object.typeName) : "",
      hpMultiplier: isSet(object.hpMultiplier) ? globalThis.Number(object.hpMultiplier) : 0,
      particles: isSet(object.particles) ? globalThis.Boolean(object.particles) : false,
    };
  },

  toJSON(message: GCSimScriptTargetType): unknown {
    const obj: any = {};
    if (message.typeName !== "") {
      obj.typeName = message.typeName;
    }
    if (message.hpMultiplier !== 0) {
      obj.hpMultiplier = message.hpMultiplier;
    }
    if (message.particles !== false) {
      obj.particles = message.particles;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptTargetType>, I>>(base?: I): GCSimScriptTargetType {
    return GCSimScriptTargetType.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptTargetType>, I>>(object: I): GCSimScriptTargetType {
    const message = createBaseGCSimScriptTargetType();
    message.typeName = object.typeName ?? "";
    message.hpMultiplier = object.hpMultiplier ?? 0;
    message.particles = object.particles ?? false;
    return message;
  },
};

function createBaseGCSimScriptTarget(): GCSimScriptTarget {
  return {
    position: [],
    radius: 0,
    level: 0,
    resist: 0,
    hp: 0,
    particleThreshold: 0,
    particleDropCount: 0,
    freezeResist: 0,
    electroResist: 0,
    hydroResist: 0,
    pyroResist: 0,
    cryoResist: 0,
    dendroResist: 0,
    physicalResist: 0,
    anemoResist: 0,
    geoResist: 0,
    type: undefined,
    particleElement: 0,
    hpMult: 0,
  };
}

export const GCSimScriptTarget = {
  encode(message: GCSimScriptTarget, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.position) {
      writer.float(v);
    }
    writer.ldelim();
    if (message.radius !== 0) {
      writer.uint32(21).float(message.radius);
    }
    if (message.level !== 0) {
      writer.uint32(24).int32(message.level);
    }
    if (message.resist !== 0) {
      writer.uint32(37).float(message.resist);
    }
    if (message.hp !== 0) {
      writer.uint32(45).float(message.hp);
    }
    if (message.particleThreshold !== 0) {
      writer.uint32(48).int32(message.particleThreshold);
    }
    if (message.particleDropCount !== 0) {
      writer.uint32(56).int32(message.particleDropCount);
    }
    if (message.freezeResist !== 0) {
      writer.uint32(69).float(message.freezeResist);
    }
    if (message.electroResist !== 0) {
      writer.uint32(77).float(message.electroResist);
    }
    if (message.hydroResist !== 0) {
      writer.uint32(85).float(message.hydroResist);
    }
    if (message.pyroResist !== 0) {
      writer.uint32(93).float(message.pyroResist);
    }
    if (message.cryoResist !== 0) {
      writer.uint32(101).float(message.cryoResist);
    }
    if (message.dendroResist !== 0) {
      writer.uint32(109).float(message.dendroResist);
    }
    if (message.physicalResist !== 0) {
      writer.uint32(117).float(message.physicalResist);
    }
    if (message.anemoResist !== 0) {
      writer.uint32(125).float(message.anemoResist);
    }
    if (message.geoResist !== 0) {
      writer.uint32(133).float(message.geoResist);
    }
    if (message.type !== undefined) {
      GCSimScriptTargetType.encode(message.type, writer.uint32(138).fork()).ldelim();
    }
    if (message.particleElement !== 0) {
      writer.uint32(144).int32(message.particleElement);
    }
    if (message.hpMult !== 0) {
      writer.uint32(157).float(message.hpMult);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScriptTarget {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScriptTarget();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 13) {
            message.position.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.position.push(reader.float());
            }

            continue;
          }

          break;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.radius = reader.float();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.level = reader.int32();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.resist = reader.float();
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.hp = reader.float();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.particleThreshold = reader.int32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.particleDropCount = reader.int32();
          continue;
        case 8:
          if (tag !== 69) {
            break;
          }

          message.freezeResist = reader.float();
          continue;
        case 9:
          if (tag !== 77) {
            break;
          }

          message.electroResist = reader.float();
          continue;
        case 10:
          if (tag !== 85) {
            break;
          }

          message.hydroResist = reader.float();
          continue;
        case 11:
          if (tag !== 93) {
            break;
          }

          message.pyroResist = reader.float();
          continue;
        case 12:
          if (tag !== 101) {
            break;
          }

          message.cryoResist = reader.float();
          continue;
        case 13:
          if (tag !== 109) {
            break;
          }

          message.dendroResist = reader.float();
          continue;
        case 14:
          if (tag !== 117) {
            break;
          }

          message.physicalResist = reader.float();
          continue;
        case 15:
          if (tag !== 125) {
            break;
          }

          message.anemoResist = reader.float();
          continue;
        case 16:
          if (tag !== 133) {
            break;
          }

          message.geoResist = reader.float();
          continue;
        case 17:
          if (tag !== 138) {
            break;
          }

          message.type = GCSimScriptTargetType.decode(reader, reader.uint32());
          continue;
        case 18:
          if (tag !== 144) {
            break;
          }

          message.particleElement = reader.int32() as any;
          continue;
        case 19:
          if (tag !== 157) {
            break;
          }

          message.hpMult = reader.float();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScriptTarget {
    return {
      position: globalThis.Array.isArray(object?.position) ? object.position.map((e: any) => globalThis.Number(e)) : [],
      radius: isSet(object.radius) ? globalThis.Number(object.radius) : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      resist: isSet(object.resist) ? globalThis.Number(object.resist) : 0,
      hp: isSet(object.hp) ? globalThis.Number(object.hp) : 0,
      particleThreshold: isSet(object.particleThreshold) ? globalThis.Number(object.particleThreshold) : 0,
      particleDropCount: isSet(object.particleDropCount) ? globalThis.Number(object.particleDropCount) : 0,
      freezeResist: isSet(object.freezeResist) ? globalThis.Number(object.freezeResist) : 0,
      electroResist: isSet(object.electroResist) ? globalThis.Number(object.electroResist) : 0,
      hydroResist: isSet(object.hydroResist) ? globalThis.Number(object.hydroResist) : 0,
      pyroResist: isSet(object.pyroResist) ? globalThis.Number(object.pyroResist) : 0,
      cryoResist: isSet(object.cryoResist) ? globalThis.Number(object.cryoResist) : 0,
      dendroResist: isSet(object.dendroResist) ? globalThis.Number(object.dendroResist) : 0,
      physicalResist: isSet(object.physicalResist) ? globalThis.Number(object.physicalResist) : 0,
      anemoResist: isSet(object.anemoResist) ? globalThis.Number(object.anemoResist) : 0,
      geoResist: isSet(object.geoResist) ? globalThis.Number(object.geoResist) : 0,
      type: isSet(object.type) ? GCSimScriptTargetType.fromJSON(object.type) : undefined,
      particleElement: isSet(object.particleElement) ? elementFromJSON(object.particleElement) : 0,
      hpMult: isSet(object.hpMult) ? globalThis.Number(object.hpMult) : 0,
    };
  },

  toJSON(message: GCSimScriptTarget): unknown {
    const obj: any = {};
    if (message.position?.length) {
      obj.position = message.position;
    }
    if (message.radius !== 0) {
      obj.radius = message.radius;
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.resist !== 0) {
      obj.resist = message.resist;
    }
    if (message.hp !== 0) {
      obj.hp = message.hp;
    }
    if (message.particleThreshold !== 0) {
      obj.particleThreshold = Math.round(message.particleThreshold);
    }
    if (message.particleDropCount !== 0) {
      obj.particleDropCount = Math.round(message.particleDropCount);
    }
    if (message.freezeResist !== 0) {
      obj.freezeResist = message.freezeResist;
    }
    if (message.electroResist !== 0) {
      obj.electroResist = message.electroResist;
    }
    if (message.hydroResist !== 0) {
      obj.hydroResist = message.hydroResist;
    }
    if (message.pyroResist !== 0) {
      obj.pyroResist = message.pyroResist;
    }
    if (message.cryoResist !== 0) {
      obj.cryoResist = message.cryoResist;
    }
    if (message.dendroResist !== 0) {
      obj.dendroResist = message.dendroResist;
    }
    if (message.physicalResist !== 0) {
      obj.physicalResist = message.physicalResist;
    }
    if (message.anemoResist !== 0) {
      obj.anemoResist = message.anemoResist;
    }
    if (message.geoResist !== 0) {
      obj.geoResist = message.geoResist;
    }
    if (message.type !== undefined) {
      obj.type = GCSimScriptTargetType.toJSON(message.type);
    }
    if (message.particleElement !== 0) {
      obj.particleElement = elementToJSON(message.particleElement);
    }
    if (message.hpMult !== 0) {
      obj.hpMult = message.hpMult;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScriptTarget>, I>>(base?: I): GCSimScriptTarget {
    return GCSimScriptTarget.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScriptTarget>, I>>(object: I): GCSimScriptTarget {
    const message = createBaseGCSimScriptTarget();
    message.position = object.position?.map((e) => e) || [];
    message.radius = object.radius ?? 0;
    message.level = object.level ?? 0;
    message.resist = object.resist ?? 0;
    message.hp = object.hp ?? 0;
    message.particleThreshold = object.particleThreshold ?? 0;
    message.particleDropCount = object.particleDropCount ?? 0;
    message.freezeResist = object.freezeResist ?? 0;
    message.electroResist = object.electroResist ?? 0;
    message.hydroResist = object.hydroResist ?? 0;
    message.pyroResist = object.pyroResist ?? 0;
    message.cryoResist = object.cryoResist ?? 0;
    message.dendroResist = object.dendroResist ?? 0;
    message.physicalResist = object.physicalResist ?? 0;
    message.anemoResist = object.anemoResist ?? 0;
    message.geoResist = object.geoResist ?? 0;
    message.type = (object.type !== undefined && object.type !== null)
      ? GCSimScriptTargetType.fromPartial(object.type)
      : undefined;
    message.particleElement = object.particleElement ?? 0;
    message.hpMult = object.hpMult ?? 0;
    return message;
  },
};

function createBaseGCSimScript(): GCSimScript {
  return {
    options: undefined,
    characterInfos: [],
    targets: [],
    energySettings: undefined,
    hurtSettings: undefined,
    scripts: [],
  };
}

export const GCSimScript = {
  encode(message: GCSimScript, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.options !== undefined) {
      GCSimScriptOptions.encode(message.options, writer.uint32(10).fork()).ldelim();
    }
    for (const v of message.characterInfos) {
      GCSimScriptCharacterInfo.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    for (const v of message.targets) {
      GCSimScriptTarget.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    if (message.energySettings !== undefined) {
      GCSimScriptEnergySettings.encode(message.energySettings, writer.uint32(34).fork()).ldelim();
    }
    if (message.hurtSettings !== undefined) {
      GCSimScriptHurtSettings.encode(message.hurtSettings, writer.uint32(42).fork()).ldelim();
    }
    for (const v of message.scripts) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSimScript {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSimScript();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.options = GCSimScriptOptions.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.characterInfos.push(GCSimScriptCharacterInfo.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.targets.push(GCSimScriptTarget.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.energySettings = GCSimScriptEnergySettings.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.hurtSettings = GCSimScriptHurtSettings.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.scripts.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSimScript {
    return {
      options: isSet(object.options) ? GCSimScriptOptions.fromJSON(object.options) : undefined,
      characterInfos: globalThis.Array.isArray(object?.characterInfos)
        ? object.characterInfos.map((e: any) => GCSimScriptCharacterInfo.fromJSON(e))
        : [],
      targets: globalThis.Array.isArray(object?.targets)
        ? object.targets.map((e: any) => GCSimScriptTarget.fromJSON(e))
        : [],
      energySettings: isSet(object.energySettings)
        ? GCSimScriptEnergySettings.fromJSON(object.energySettings)
        : undefined,
      hurtSettings: isSet(object.hurtSettings) ? GCSimScriptHurtSettings.fromJSON(object.hurtSettings) : undefined,
      scripts: globalThis.Array.isArray(object?.scripts) ? object.scripts.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: GCSimScript): unknown {
    const obj: any = {};
    if (message.options !== undefined) {
      obj.options = GCSimScriptOptions.toJSON(message.options);
    }
    if (message.characterInfos?.length) {
      obj.characterInfos = message.characterInfos.map((e) => GCSimScriptCharacterInfo.toJSON(e));
    }
    if (message.targets?.length) {
      obj.targets = message.targets.map((e) => GCSimScriptTarget.toJSON(e));
    }
    if (message.energySettings !== undefined) {
      obj.energySettings = GCSimScriptEnergySettings.toJSON(message.energySettings);
    }
    if (message.hurtSettings !== undefined) {
      obj.hurtSettings = GCSimScriptHurtSettings.toJSON(message.hurtSettings);
    }
    if (message.scripts?.length) {
      obj.scripts = message.scripts;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSimScript>, I>>(base?: I): GCSimScript {
    return GCSimScript.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSimScript>, I>>(object: I): GCSimScript {
    const message = createBaseGCSimScript();
    message.options = (object.options !== undefined && object.options !== null)
      ? GCSimScriptOptions.fromPartial(object.options)
      : undefined;
    message.characterInfos = object.characterInfos?.map((e) => GCSimScriptCharacterInfo.fromPartial(e)) || [];
    message.targets = object.targets?.map((e) => GCSimScriptTarget.fromPartial(e)) || [];
    message.energySettings = (object.energySettings !== undefined && object.energySettings !== null)
      ? GCSimScriptEnergySettings.fromPartial(object.energySettings)
      : undefined;
    message.hurtSettings = (object.hurtSettings !== undefined && object.hurtSettings !== null)
      ? GCSimScriptHurtSettings.fromPartial(object.hurtSettings)
      : undefined;
    message.scripts = object.scripts?.map((e) => e) || [];
    return message;
  },
};

function createBaseGCSim(): GCSim {
  return { scripts: [] };
}

export const GCSim = {
  encode(message: GCSim, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.scripts) {
      GCSimScript.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GCSim {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGCSim();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.scripts.push(GCSimScript.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GCSim {
    return {
      scripts: globalThis.Array.isArray(object?.scripts) ? object.scripts.map((e: any) => GCSimScript.fromJSON(e)) : [],
    };
  },

  toJSON(message: GCSim): unknown {
    const obj: any = {};
    if (message.scripts?.length) {
      obj.scripts = message.scripts.map((e) => GCSimScript.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GCSim>, I>>(base?: I): GCSim {
    return GCSim.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GCSim>, I>>(object: I): GCSim {
    const message = createBaseGCSim();
    message.scripts = object.scripts?.map((e) => GCSimScript.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
