# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: attribute.proto, character.proto, set.proto, artifact.proto, suit.proto, weapon.proto, build.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class AttributeType(betterproto.Enum):
    ATTRIBUTE_TYPE_UNSPECIFIED = 0
    HP = 1
    ATK = 2
    DEF = 3
    ELEMENTAL_MASTERY = 4
    ENERGY_RECHARGE = 5
    HP_PERCENT = 6
    ATK_PERCENT = 7
    DEF_PERCENT = 8
    CRIT_RATE = 9
    CRIT_DAMAGE = 10
    HEALING_BONUS = 11
    ANEMO_DAMAGE_BONUS = 12
    CRYO_DAMAGE_BONUS = 13
    DENDRO_DAMAGE_BONUS = 14
    ELECTRO_DAMAGE_BONUS = 15
    GEO_DAMAGE_BONUS = 16
    HYDRO_DAMAGE_BONUS = 17
    PHYSICAL_DAMAGE_BONUS = 18
    PYRO_DAMAGE_BONUS = 19


class AttributePosition(betterproto.Enum):
    ATTRIBUTE_POSITION_UNSPECIFIED = 0
    FLOWER = 1
    PLUME = 2
    SANDS = 3
    GOBLET = 4
    CIRCLET = 5
    SUB = 6


class Character(betterproto.Enum):
    CHARACTER_UNSPECIFIED = 0
    TRAVELER_ANEMO = 1
    TRAVELER_GEO = 2
    TRAVELER_ELECTRO = 3
    TRAVELER_DENDRO = 4
    AETHER = 5
    LUMINE = 6
    ALBEDO = 7
    ALOY = 8
    AMBER = 9
    BARBARA = 10
    BEIDOU = 11
    BENNETT = 12
    CHONGYUN = 13
    DILUC = 14
    DIONA = 15
    EULA = 16
    FISCHL = 17
    GANYU = 18
    HU_TAO = 19
    JEAN = 20
    KAEDEHARA_KAZUHA = 21
    KAEYA = 22
    KAMISATO_AYAKA = 23
    KEQING = 24
    KLEE = 25
    KUJOU_SARA = 26
    LISA = 27
    MONA = 28
    NINGGUANG = 29
    NOELLE = 30
    QIQI = 31
    RAIDEN_SHOGUN = 32
    RAZOR = 33
    ROSARIA = 34
    SANGONOMIYA_KOKOMI = 35
    SAYU = 36
    SUCROSE = 37
    TARTAGLIA = 38
    THOMA = 39
    VENTI = 40
    XIANGLING = 41
    XIAO = 42
    XINGQIU = 43
    XINYAN = 44
    YANFEI = 45
    YOIMIYA = 46
    ZHONGLI = 47
    GOROU = 48
    ARATAKI_ITTO = 49
    SHENHE = 50
    YUN_JIN = 51
    YAE_MIKO = 52
    KAMISATO_AYATO = 53
    YELAN = 54
    KUKI_SHINOBU = 55
    SHIKANOIN_HEIZOU = 56
    COLLEI = 57
    DORI = 58
    TIGHNARI = 59
    CANDACE = 60
    CYNO = 61
    NILOU = 62
    NAHIDA = 63
    LAYLA = 64
    FARUZAN = 65
    WANDERER = 66
    ALHAITHAM = 67
    YAOYAO = 68
    DEHYA = 69


class Set(betterproto.Enum):
    SET_UNSPECIFIED = 0
    ARCHAIC_PETRA = 1
    BERSERKER = 2
    BLIZZARD_STRAYER = 3
    BLOODSTAINED_CHIVALRY = 4
    BRAVE_HEART = 5
    CRIMSON_WITCH_OF_FLAMES = 6
    DEEPWOOD_MEMORIES = 7
    DEFENDERS_WILL = 8
    DESERT_PAVILION_CHRONICLE = 9
    ECHOES_OF_AN_OFFERING = 10
    EMBLEM_OF_SEVERED_FATE = 11
    FLOWER_OF_PARADISE_LOST = 12
    GAMBLER = 13
    GILDED_DREAMS = 14
    GLADIATORS_FINALE = 15
    HEART_OF_DEPTH = 16
    HUSK_OF_OPULENT_DREAMS = 17
    INSTRUCTOR = 18
    LAVAWALKER = 19
    MAIDEN_BELOVED = 20
    MARTIAL_ARTIST = 21
    NOBLESSE_OBLIGE = 22
    OCEAN_HUED_CLAM = 23
    PALE_FLAME = 24
    PRAYERS_FOR_DESTINY = 25
    PRAYERS_FOR_ILLUMINATION = 26
    PRAYERS_FOR_WISDOM = 27
    PRAYERS_TO_SPRINGTIME = 28
    RESOLUTION_OF_SOJOURNER = 29
    RETRACING_BOLIDE = 30
    SCHOLAR = 31
    SHIMENAWAS_REMINISCENCE = 32
    TENACITY_OF_THE_MILLELITH = 33
    THE_EXILE = 34
    THUNDERING_FURY = 35
    THUNDERSOOTHER = 36
    TINY_MIRACLE = 37
    VERMILLION_HEREAFTER = 38
    VIRIDESCENT_VENERER = 39
    WANDERERS_TROUPE = 40


class WeaponType(betterproto.Enum):
    WEAPON_TYPE_UNSPECIFIED = 0
    BOW = 1
    CLAYMORE = 2
    CATALYST = 3
    POLEARM = 4
    SWORD = 5


class Weapon(betterproto.Enum):
    WEAPON_UNSPECIFIED = 0
    AKUOUMARU = 1
    ALLEY_HUNTER = 2
    AMENOMA_KAGEUCHI = 3
    AMOS_BOW = 4
    APPRENTICES_NOTES = 5
    AQUA_SIMULACRA = 6
    AQUILA_FAVONIA = 7
    A_THOUSAND_FLOATING_DREAMS = 8
    BEGINNERS_PROTECTOR = 9
    BLACKCLIFF_AGATE = 10
    BLACKCLIFF_LONGSWORD = 11
    BLACKCLIFF_POLE = 12
    BLACKCLIFF_SLASHER = 13
    BLACKCLIFF_WARBOW = 14
    BLACK_TASSEL = 15
    BLOODTAINTED_GREATSWORD = 16
    CALAMITY_QUELLER = 17
    CINNABAR_SPINDLE = 18
    COMPOUND_BOW = 19
    COOL_STEEL = 20
    CRESCENT_PIKE = 21
    DARK_IRON_SWORD = 22
    DEATHMATCH = 23
    DEBATE_CLUB = 24
    DODOCO_TALES = 25
    DRAGONS_BANE = 26
    DRAGONSPINE_SPEAR = 27
    DULL_BLADE = 28
    ELEGY_FOR_THE_END = 29
    EMERALD_ORB = 30
    END_OF_THE_LINE = 31
    ENGULFING_LIGHTNING = 32
    EVERLASTING_MOONGLOW = 33
    EYE_OF_PERCEPTION = 34
    FADING_TWILIGHT = 35
    FAVONIUS_CODEX = 36
    FAVONIUS_GREATSWORD = 37
    FAVONIUS_LANCE = 38
    FAVONIUS_SWORD = 39
    FAVONIUS_WARBOW = 40
    FERROUS_SHADOW = 41
    FESTERING_DESIRE = 42
    FILLET_BLADE = 43
    FOREST_REGALIA = 44
    FREEDOM_SWORN = 45
    FROSTBEARER = 46
    FRUIT_OF_FULFILLMENT = 47
    HAKUSHIN_RING = 48
    HALBERD = 49
    HAMAYUMI = 50
    HARAN_GEPPAKU_FUTSU = 51
    HARBINGER_OF_DAWN = 52
    HUNTERS_BOW = 53
    HUNTERS_PATH = 54
    IRON_POINT = 55
    IRON_STING = 56
    KAGOTSURUBE_ISSHIN = 57
    KAGURAS_VERITY = 58
    KATSURAGIKIRI_NAGAMASA = 59
    KEY_OF_KHAJ_NISUT = 60
    KINGS_SQUIRE = 61
    KITAIN_CROSS_SPEAR = 62
    LIONS_ROAR = 63
    LITHIC_BLADE = 64
    LITHIC_SPEAR = 65
    LOST_PRAYER_TO_THE_SACRED_WINDS = 66
    LUXURIOUS_SEA_LORD = 67
    MAGIC_GUIDE = 68
    MAKHAIRA_AQUAMARINE = 69
    MAPPA_MARE = 70
    MEMORY_OF_DUST = 71
    MESSENGER = 72
    MISSIVE_WINDSPEAR = 73
    MISTSPLITTER_REFORGED = 74
    MITTERNACHTS_WALTZ = 75
    MOONPIERCER = 76
    MOUUNS_MOON = 77
    OATHSWORN_EYE = 78
    OLD_MERCS_PAL = 79
    OTHERWORLDLY_STORY = 80
    POCKET_GRIMOIRE = 81
    POLAR_STAR = 82
    PREDATOR = 83
    PRIMORDIAL_JADE_CUTTER = 84
    PRIMORDIAL_JADE_WINGED_SPEAR = 85
    PRIZED_ISSHIN_BLADE = 86
    PROTOTYPE_AMBER = 87
    PROTOTYPE_ARCHAIC = 88
    PROTOTYPE_CRESCENT = 89
    PROTOTYPE_RANCOUR = 90
    PROTOTYPE_STARGLITTER = 91
    RAINSLASHER = 92
    RAVEN_BOW = 93
    RECURVE_BOW = 94
    REDHORN_STONETHRESHER = 95
    ROYAL_BOW = 96
    ROYAL_GREATSWORD = 97
    ROYAL_GRIMOIRE = 98
    ROYAL_LONGSWORD = 99
    ROYAL_SPEAR = 100
    RUST = 101
    SACRIFICIAL_BOW = 102
    SACRIFICIAL_FRAGMENTS = 103
    SACRIFICIAL_GREATSWORD = 104
    SACRIFICIAL_SWORD = 105
    SAPWOOD_BLADE = 106
    SEASONED_HUNTERS_BOW = 107
    SERPENT_SPINE = 108
    SHARPSHOOTERS_OATH = 109
    SILVER_SWORD = 110
    SKYRIDER_GREATSWORD = 111
    SKYRIDER_SWORD = 112
    SKYWARD_ATLAS = 113
    SKYWARD_BLADE = 114
    SKYWARD_HARP = 115
    SKYWARD_PRIDE = 116
    SKYWARD_SPINE = 117
    SLINGSHOT = 118
    SNOW_TOMBED_STARSILVER = 119
    SOLAR_PEARL = 120
    SONG_OF_BROKEN_PINES = 121
    STAFF_OF_HOMA = 122
    STAFF_OF_THE_SCARLET_SANDS = 123
    SUMMIT_SHAPER = 124
    SWORD_OF_DESCENSION = 125
    THE_ALLEY_FLASH = 126
    THE_BELL = 127
    THE_BLACK_SWORD = 128
    THE_CATCH = 129
    THE_FLUTE = 130
    THE_STRINGLESS = 131
    THE_UNFORGED = 132
    THE_VIRIDESCENT_HUNT = 133
    THE_WIDSITH = 134
    THRILLING_TALES_OF_DRAGON_SLAYERS = 135
    THUNDERING_PULSE = 136
    TOUKABOU_SHIGURE = 137
    TRAVELERS_HANDY_SWORD = 138
    TULAYTULLAHS_REMEMBRANCE = 139
    TWIN_NEPHRITE = 140
    VORTEX_VANQUISHER = 141
    WANDERING_EVENSTAR = 142
    WASTER_GREATSWORD = 143
    WAVEBREAKERS_FIN = 144
    WHITEBLIND = 145
    WHITE_IRON_GREATSWORD = 146
    WHITE_TASSEL = 147
    WINDBLUME_ODE = 148
    WINE_AND_SONG = 149
    WOLFS_GRAVESTONE = 150
    XIPHOS_MOONLIGHT = 151
    LIGHT_OF_FOLIAR_INCISION = 152
    BEACON_OF_THE_REED_SEA = 153
    MAILED_FLOWER = 154


@dataclass
class Attribute(betterproto.Message):
    type: "AttributeType" = betterproto.enum_field(1)
    value: float = betterproto.float_field(2)


@dataclass
class Artifact(betterproto.Message):
    set: "Set" = betterproto.enum_field(1)
    star: int = betterproto.int32_field(2)
    level: int = betterproto.int32_field(3)
    position: "AttributePosition" = betterproto.enum_field(4)
    main_attribute: "Attribute" = betterproto.message_field(5)
    sub_attributes: List["Attribute"] = betterproto.message_field(6)
    character: "Character" = betterproto.enum_field(7)
    locked: bool = betterproto.bool_field(8)


@dataclass
class SetCombo(betterproto.Message):
    set: "Set" = betterproto.enum_field(1)
    count: int = betterproto.int32_field(2)


@dataclass
class Suit(betterproto.Message):
    set_combos: List["SetCombo"] = betterproto.message_field(1)


@dataclass
class Build(betterproto.Message):
    name: str = betterproto.string_field(1)
    character: "Character" = betterproto.enum_field(2)
    weapons: List["Weapon"] = betterproto.enum_field(3)
    suits: List["Suit"] = betterproto.message_field(4)
    flower_attributes: List["AttributeType"] = betterproto.enum_field(5)
    plume_attributes: List["AttributeType"] = betterproto.enum_field(6)
    sands_attributes: List["AttributeType"] = betterproto.enum_field(7)
    goblet_attributes: List["AttributeType"] = betterproto.enum_field(8)
    circlet_attributes: List["AttributeType"] = betterproto.enum_field(9)
    sub_attributes: List["Attribute"] = betterproto.message_field(10)
