// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const GENSHIN_GAME_VERSION = "6.1";
export const GENSHIN_DB_VERSION = "5.2.6";
export const LAST_UPDATED = "2025-11-16T16:54:46.503Z";
