// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const GENSHIN_GAME_VERSION = "6.4";
export const GENSHIN_DB_VERSION = "5.2.9";
export const LAST_UPDATED = "2026-03-08T18:58:47.753Z";
