// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const GENSHIN_GAME_VERSION = "6.6";
export const GENSHIN_DB_VERSION = "5.2.11";
export const LAST_UPDATED = "2026-06-09T21:10:10.028Z";
